// GENERATED FILE. Do not edit by hand.
// Built from docs/CHANGELOG.md by scripts/gen-updates.ts; regenerate with
// `npm run gen:updates` (and `npm run test:updates` verifies it is current).

import type { GeneratedUpdate } from "./updates";

export const GENERATED_UPDATES: GeneratedUpdate[] = [
  {
    date: "2026-09-05",
    title: "Sweep-sized retiers, profile and notification fixes",
    summary: "The targeted win-rate re-measure of the 336 cards moved by the full pass is in, and four of them move one more step.",
    anchor: "u-20260905-2050",
    bullets: [
      "Two shards at 12 paired games per card measured all 336 moved cards; 334 fired and 18 resolved outside two standard errors. The tier ladder over the moved set rises from tier 1 to tier 8.",
      "Sized up one step each on that data: Deal with the Devil to Tier 5, Ascension (small) to Tier 7, Dragon Pawn to Tier 4, Mirror of Souls to Tier 5.",
      "Amazon Army measured against its holder and is flagged for a play-policy check before any tier change.",
      "Game rows resolve which seat you held by user id, so a renamed player's history no longer shows every result flipped.",
      "The report dialog recovers from a failed request instead of sticking on Sending; a dead extra fetch on every profile view is gone.",
      "A renamed sender's bell entries swap only the leading name (a short name is also a substring of the copy).",
      "The leaderboard no longer pins a duplicate of your own row while your account loads.",
      "The codex tier filter resets when you switch between buffs and nerfs, so a tier the other family lacks cannot blank the list.",
    ],
  },
  {
    date: "2026-09-05",
    title: "Round four: bot game, analysis, inbox, clubs and tournament fixes",
    summary: "Another sweep over the pages the earlier passes skipped.",
    anchor: "u-20260905-2010",
    bullets: [
      "With premoves off, the board no longer shows premove dots during the bot's think, and the clock pill freezes at its live value across a draft pause instead of jumping back to the banked time (it...",
      "The board's low-time effects now watch the live clock, waking exactly when the active side crosses the 15s line, rather than the banked figure that only moved after the pressure was over.",
      "The end screen no longer re-hides an opponent rule a reveal card already showed you all game.",
      "Arrow-key move review stays off while the result panel, buff targeting or a front-and-center draft owns the board, matching the wheel navigation.",
      "The analysis board's eval, bar and best-move squares only render for the position they were searched from, so a move no longer flips the eval sign for a frame or highlights a piece that is not there.",
      "Message bell entries are matched by the sender's id, so a renamed sender's notification clears when you read the thread and does not multiply.",
      "Joining checks the stored finished status (an arena that played all its rounds early) and, for club events, club membership, the same rule creation already enforced.",
      "A refused create on the tournaments page no longer blanks the directory behind the form.",
      "Club pages show the true member count for clubs past the 200-row leaderboard and derive each event's phase from its schedule instead of printing a stale stored status.",
      "Sub-minute and half-minute clocks (30s+0, 1.5+0) are labelled correctly in open challenges, live games, the watch rail and TV, instead of rounding to 1+0 and 2+0.",
      "Quick pairing shows \"?\" for a mode you have not played rather than the frozen legacy rating.",
    ],
  },
  {
    date: "2026-09-05",
    title: "Round three: worker, engine and match-flow bug fixes",
    summary: "A second sweep over the areas the first two passes skipped: the game server's clock and rematch paths, the engine's chained-move guard and notation, and the match page's reconnect and draft flows.",
    anchor: "u-20260905-1924",
    bullets: [
      "A disconnect pause taken during a move or a draft deadline is billed again: both resume paths now check the live pause before restarting the clock, the same way draft actions did.",
      "Rematch requests claim the slot before any database await, so a double tap makes one rematch game and a cancel during the await is not lost; the cancel frame carries the canceller's colour so only...",
      "Aborting a game re-reads the match after the abort-history await, so a game that ended in between is not aborted twice.",
      "A resync clears the in-flight connect handle, so a reconnect no longer waits out the full eight-second fail timer.",
      "A move buffered during a disconnect is dropped along with any premove when the board rolls back, and sending now reports sent, held or failed so the optimistic board is only kept on sent.",
      "A free action that grants no extra move (Warp Home) no longer arms the chained-move king guard, so the activator's own king capture stays legal.",
      "Move numbers no longer double-increment on two consecutive Black moves.",
      "Move-risk lookups key on castle and drop as well as from/to, so a castling move and a king step to the same square no longer share a risk badge.",
      "Settings pulled from the server are validated before they touch local storage, and pushes adopt the server's timestamp so a change no longer reverts on reload when the clocks disagree.",
      "The minimized draft panel has a Tuck control; its double-tap guard now measures real elapsed time. The phone move strip rests at the left edge when reviewing from the start of the line.",
      "Dock rows show one Use button, dragging a card with no target no longer fires it, and an expanded row stays open while a copy's countdown ticks.",
      "Analyze is hidden for card games (the analysis board would silently truncate them) and the analysis page says when a line stops early. Tournament pages clear a stale error on a successful load.",
    ],
  },
  {
    date: "2026-09-05",
    title: "Redesign follow-up: defaults, premoves, dock, profile, search, balance pass",
    summary: "The default look is Lichess dark with the midnight board, premoves behave like Lichess, the dock has hotkeys and inline Use, the profile and search pages are fixed, and every card in play was re-priced against its own family.",
    anchor: "u-20260905-1505",
    bullets: [
      "The site theme default goes back to Lichess dark; the board default is the dark grey-blue midnight set. The navy Midnight site theme stays as an option.",
      "The vault's rings and caps burn in the exact tier colour of the best card inside, the caption carries the tier numeral, and tier 9/10 cards get their own deal-glow rows (they fell back to brass...",
      "Premoves are Lichess-exact: one slot, a new premove replaces it, and any click or refused drop that is not a premove cancels it.",
      "The dock flips between You and Them with y / t, and a collapsed row keeps its Use button.",
      "Profile games tab: stat tiles, one labelled filter row, 48px grid rows; clubs are plain accent links.",
      "Hero TV frame is token-only, so no black halo on light and no doubled edge on dark.",
      "Friends list shows 12 with Show all, presence computed once, an overflow menu on narrow rails.",
      "Codex lists only cards in play and no longer says Showing N of M; the show-retired toggle is gone.",
    ],
  },
  {
    date: "2026-09-05",
    title: "UI redesign and bug sweep",
    summary: "New Midnight site theme (navy take on the Lichess ladder, cooler text ramp, accent lifted to #4c9ff0) and it is the default. Dark, Light and System stay; System resolves to Midnight or Light.",
    anchor: "u-20260905-1325",
    bullets: [
      "Piece glide is now a millisecond setting (Settings > Board > Motion, presets Off / 60 / 100 / 150 / 250 ms, default 100) with a curve that finishes its travel by the stated time instead of creeping.",
      "The check highlight reads the optimistic board, so the enemy king turns red when your piece lands, not one round trip later.",
      "A move played during a socket blip is held and flushed on reconnect instead of being dropped with an error toast.",
      "New Lichess prefs: Tenths of seconds (never / under 10s / always), Material difference, Show ratings.",
      "The treasure chest is gone. Opening (~920ms): spin-up, rings flare and lift, faces shear away, core blooms into a flash and shockwave, cards deal out of the light.",
      "When the 20s window ends the draft no longer auto-picks or vanishes, online or against a bot: it shrinks into the corner panel and STAYS there (the 12s auto-tuck fuse is gone) until the player...",
      "Headers are 44-48px on phones, chat and clock labels come up to 12px, corner overlays sit at the edge.",
    ],
  },
  {
    date: "2026-08-03",
    title: "Animation quality pass on the three entrance systems the owner flagged as basic",
    summary: "Nerf entrances: the category arrival is now a 9-layer verdict stamp (warning under-glow and judicial seal tell, two-part stamp head with a one-frame squash, ink shards, emboss afterglow, drips and...",
    anchor: "u-20260803-0958",
    bullets: [
      "Creator cards: the one shared ring-and-step-in entrance is gone; each of the five cards arrives as its play in miniature (bait tips over and SPROINGs out of the snare; the rook slams in behind...",
      "Passive spawns: every activation now announces itself with a tell (color under-bloom plus anchor inhale), an announce ring with rising motes, and a slow settle, fitted inside each visual's...",
    ],
  },
  {
    date: "2026-08-03",
    title: "Card animations now default ON even when the device asks apps to reduce motion",
    summary: "\"Follow system motion\" flips to default OFF: card plays are gameplay information (they are how you see what a card just did), so the OS prefers-reduced-motion flag no longer stands them down...",
    anchor: "u-20260803-0926",
    bullets: [
      "On a reduced-motion device with the new default, a one-time notice explains that effects are on by default and offers to turn them off, labelled not recommended since quiet plays are easy to miss.",
      "Settings hints for \"Follow system motion\" (Interface and Accessibility) now say it is off by default and that turning it on is not recommended.",
    ],
  },
  {
    date: "2026-07-28",
    title: "The misaligned draft box, clock tier 1, exploit, mobile leaderboard",
    summary: "Clock rebalance, tier 1: 13 cards down to 2. Kept Polite Cough and Pinch of Sand, where time IS the card. Eight were pure riders on cards already complete without them.",
    anchor: "u-20260728-2320",
    bullets: [
      "The lock-in bar transitioned width at 10Hz for the whole 20 second window, relayouting inside an overflow-hidden parent on every tick.",
      "The most blocking surface in the product had no dialog semantics at all: a keyboard user tabbed straight out of a forced decision into the board.",
      "The reduced-motion notice added last session could render over the draft cards. It now waits before asking for a slot.",
    ],
  },
  {
    date: "2026-07-28",
    title: "Rating bug, board render, rounded corners, I Hate My Ex",
    summary: "I Hate My Ex: was a tier 1 card freezing one pawn each side. Now destroys every piece on the board, both armies, leaving only the two kings. Tier 1 to 8, passive to instant.",
    anchor: "u-20260728-1940",
    bullets: [],
  },
  {
    date: "2026-07-28",
    title: "Dead cards, notation, animation reliability, draft escalation",
    summary: "Machinery fixed three ways: the restriction is live from the moment the curse lands (only the first affected piece keeps its forbidden moves, once); spending the escape no longer ticks the...",
    anchor: "u-20260728-1411",
    bullets: [
      "The move list was ambiguous and every PGN from the Download PGN button was unreplayable by any reader.",
      "Analysis board numbered moves by ply parity, so any FEN with black to move numbered the whole line wrong and never showed the leading \"N...\".",
      "Phones enable reduced motion for battery saving and accessibility defaults, so a large share of players saw no card animations at all with nothing explaining it.",
      "Each now carries a constellation varying by arrangement (orbit, arc, column, corners, spiral, cross) and count, 36 distinct geometries, assigned so no two cards sharing a template share one.",
      "A game runs about eleven drafts per player, so six or seven were statistically identical. Rounds 1 to 5 are byte-identical; round 8 onward lands tier 8 about 64% of the time.",
      "Only positions since the last irreversible move can match, so the earlier keys are skipped: 0.43ms to 0.17ms on a 150-ply board.",
    ],
  },
  {
    date: "2026-07-23",
    title: "Animations, draft picker selection ring",
    summary: "Animations: summon/morph/convert/promote signature cards fell back to a generic poof (or nothing) because the board suppressed their bespoke board-wide lead unconditionally; the suppress now...",
    anchor: "u-20260723-0410",
    bullets: [
      "Draft picker selection ring: on hover-capable devices the gold ring sat 3px below the lifted card; the ring now lifts in lockstep (and the minimized panel's ring rides the card itself via glow).",
      "Starfields now paint once, the ambient set follows the FX intensity dial, and sustained sub-30fps auto-downgrades the ambience for the session.",
    ],
  },
  {
    date: "2026-07-23",
    title: "Balance overhaul",
    summary: "Balance overhaul (owner doc \"Nerf Chess Balance Overhaul\", 2228 named card changes).",
    anchor: "u-20260723-0311",
    bullets: [
      "Full-library balance pass across all four sections: 949 buffs, 527 hexes, 404 boons, 348 nerfs. 837 tier moves, 1372 mechanical tweaks, 12 replacements, 7 renames (ids never change).",
      "Recurring templates applied consistently: duration shortenings (minimum one; exactly-one-turn effects grant one defender exemption instead), delayed activations (effects begin after the opponent's...",
      "Tier 9 is now a valid apex band for hexes (special: true, never in the normal curve): The Curse Engine, Peace of the Grave, Mirror of Winter.",
      "Codex: every touched card gains a dated balance-history event merged into each card page's timeline.",
      "Living Board's targeting chain terminates after the optional king-step pick.",
      "Guardian-family openers enforce protection via move filters (the shared shield effect expired the turn it was added); flagged for a wider shield-family fix.",
      "Draft picker: the gold selection ring now follows the card's hover lift on desktop (it sat 3px low); the minimized panel's ring rides the card itself.",
    ],
  },
  {
    date: "2026-07-20",
    title: "Sound for every effect, whole-library card review",
    summary: "Every card's persistent effect (a nerf reveal, a buff/boon/hex acquisition) already carried a sound family in its passive composition that nothing ever played.",
    anchor: "u-20260720-0429",
    bullets: [
      "Result: all 677 passive effects (360 nerfs + 317 passive buffs) are voiced; the other 689 buffs are instant/activated and already voice through the cast/signature system.",
    ],
  },
  {
    date: "2026-07-20",
    title: "Draft preview, knight/bishop overlap, em-dash guard, rule accuracy",
    summary: "Fixed three nerf descriptions that misdescribed their own code: Thunderdome now says a piece in the center 16 can never leave the zone (the code makes it impossible, not \"rarely\"); Quicksand now...",
    anchor: "u-20260720-0320",
    bullets: [],
  },
  {
    date: "2026-07-18",
    title: "Codex rule completeness: two orphaned nerfs restored",
    summary: "All 1006 buffs and 358 nerfs already surfaced; found five nerf rules defined in source but absent from the Codex, two of them accidental.",
    anchor: "u-20260718-1708",
    bullets: [
      "Left the deliberately retired rules retired: Foot Soldiers Only (verified exact mechanical duplicate of the live Serf Labor, identical move filter), Number of the Beast, and Hand and Gigabrain.",
    ],
  },
  {
    date: "2026-07-17",
    title: "Dungeon lobby",
    summary: "+44 boons and +40 hexes in the genuinely open mechanic families (turncoat/possession, summoned hazards, sympathetic links, contracts, contagion, comeback, clocks, terrain, miracles); zero...",
    anchor: "u-20260717-1745",
    bullets: [],
  },
  {
    date: "2026-07-17",
    title: "Dungeon gate lobby CTA, chest reveal ledger, nerf-mode wave 2",
    summary: "The Open Lobby CTA is now a full dungeon gate: carved granite courses, iron corner braces with rivets, an Elder-Futhark rune lintel that ignites on hover, torch-pooled jambs, and a clipped...",
    anchor: "u-20260717-1330",
    bullets: [
      "Leaderboard podium keeps the same three-across treasure-dais silhouette on phones instead of the squished vertical stack.",
      "New reveal-state ledger: the treasure chest plays exactly once per unique offer version (scope game id + offer index + reroll count).",
      "+28 boons, +27 hexes, +16 nerfs. Family totals: boons 60->88, hexes 180->207, nerfs 342->358.",
      "Animation coverage: five boon templates + five curse templates, 41 unique per-card flourish dressings, 14 fully bespoke tier 7-8 scenes; shared-flagship ratchet unchanged at 381/45, every new card...",
    ],
  },
  {
    date: "2026-07-12",
    title: "Codex card insights: stats + history on every card page",
    summary: "Hexes and boons get their own URL namespaces, statically generated like the buff/nerf pages.",
    anchor: "u-20260712-0018",
    bullets: [
      "Every card page gains a server-rendered \"History\" timeline: wave-introduction line plus room for curated per-card balance notes.",
      "Copy fix: hex/item category blurbs were missing their verb (\"As a hex card, it a curse...\").",
    ],
  },
  {
    date: "2026-07-05",
    title: "Walnut hex: lifetime fix + walnut-piece visual",
    summary: "Fix: a walnut (and freeze) is bound to the piece on its square, but the effect was only removed when its turn timer expired, so when the walnutted piece was captured or removed the marker lingered...",
    anchor: "u-20260705-2139",
    bullets: [
      "Visual: a walnutted piece now renders as the whole piece becoming a plump, glossy walnut with the original piece shrunk down and nestled inside the shell so you can still tell what it was.",
      "Animation: the walnut pops in with a comedic crunch, then gives a periodic little shudder as if the trapped piece is rattling to crack out.",
    ],
  },
  {
    date: "2026-07-05",
    title: "Turn-cost labels on every card",
    summary: "Feature: every draftable card now states whether using it uses up a turn, with a small badge in four states: Uses your turn (activated, playing it is your move), Free action (activated but...",
    anchor: "u-20260705-2102",
    bullets: [
      "Audit: swept all 419 cards for turn-cost mislabels. Deterministic pass: zero description-vs-behavior contradictions. No flags changed: the derived badge is correct by construction.",
    ],
  },
  {
    date: "2026-07-05",
    title: "Count-based cards no longer soft-lock with few targets",
    summary: "Fix: cards that collect N targets soft-locked when the board had fewer than N eligible targets: you picked the few that existed, then got stranded on an empty step you could neither complete nor...",
    anchor: "u-20260705-2050",
    bullets: [],
  },
  {
    date: "2026-07-05",
    title: "Homepage copy + 3 nerf and 3 buff clickable cards to the codex",
    summary: "Homepage copy (Nerf = secret handicaps revealed at end; drafting; Buff = no nerfs, draft power-ups; win by capturing the king) + 3 nerf and 3 buff clickable cards to the codex.",
    anchor: "u-20260705-2",
    bullets: [
      "Draft settings on /play + fixed Play-vs-Bot (it silently gave both sides hidden nerfs) + true Plain chess vs bot.",
    ],
  },
  {
    date: "2026-07-05",
    title: "Tournaments, feature wave",
    summary: "Cooler draft: glass reveal FX (drama scales with tier) + Surprise-your-friend stacked preset.",
    anchor: "u-20260705-1839",
    bullets: [
      "UI redesign: research, mode-seam signature, fluid type scale, de-bland home/lobby, lichess rating chart, snappier search.",
      "Low-time warning sound synced to the visible clock.",
      "Profile polish + custom emoji flairs + avatar/flair rejection messaging.",
      "Rule audit (judgment): correctness / tier-fit / clarity fixes.",
      "Board bugs: mobile premove cancel, illegal-move arrows, fullscreen/resize.",
    ],
  },
  {
    date: "2026-07-05",
    title: "Opponent-hexes: 104 new, 10 to 16 per tier",
    summary: "Opponent-hexes (curses on your opponent): 104 new, 10 to 16 per tier. Reshipped missing tier 5-8 hexes (53 cards).",
    anchor: "u-20260705-1",
    bullets: [
      "Nerf-relief boons (soften your own nerf): 32 new, pool 25 to 52.",
      "Expanded nerfs: 82 new across all 8 tiers (implemented count 232 to 302).",
      "Draggable hotbar (drag an activated card onto its target).",
      "Per-effect board animations (king-only, no-pawn-advance, hex cast).",
      "Jargon glossary tooltips.",
      "Mobile draft/UX fixes.",
      "Tutorial \"The four cards\" section (nerf/buff/hex/boon, who-it-hits distinction).",
      "Codex: buff cards get the difficulty ornament; hex and boon become their own tabs; \"Suggest a nerf\" becomes \"Suggest a rule\".",
      "Client connection resilience (retry/backoff, reconnect during matchmaking, seat at pairing).",
    ],
  },
];
