// Funny set: SUMMONS & REINFORCEMENTS. Most cards grant a piece to your
// crazyhouse-style pocket (grantInventory, a free instant): you draft it now
// and spend a later turn to DROP it, so the summon itself costs no move. The
// rest reuse summonTemp (a rental that expires), lineSweep (a charging piece),
// or a conditional passive modeled on the library's trade_up / insurance
// pattern. The engine's drop generator already refuses to drop a pawn on rank
// 1 or 8, and a king is never bankable.

import { Buff } from "./shared";
import {
  card,
  summonTemp,
  lineSweep,
  activated,
  grantInventory,
  instant,
  mySquares,
  myHalfZone,
  ORTHO_DIRS,
  SQ,
} from "./shared";

export const FUNNY_SUMMONS: Buff[] = [
  card(
    {
      id: "summon_intern",
      icon: "UserPlus",
      name: "Summon Intern",
      description: "A new pawn joins your pocket. Later, spend a turn to drop it onto any empty square.",
      tier: 2,
      category: "pieces",
      flavor: "It brought its own lanyard.",
    },
    instant((_inst, api) => grantInventory(api, "p", 1)),
  ),
  card(
    {
      id: "pizza_delivery",
      icon: "Pizza",
      name: "Pizza Delivery",
      description: "A knight zips in on a scooter delivering pizza: it parks in your pocket, ready to drop onto any empty square on a later turn.",
      tier: 4,
      category: "pieces",
      flavor: "Thirty minutes or the fork is free.",
    },
    instant((_inst, api) => grantInventory(api, "n", 1)),
  ),
  card(
    {
      id: "reinforcements",
      icon: "Users",
      name: "Reinforcements",
      description: "Two pawns parachute into your pocket: drop them onto empty squares on later turns.",
      tier: 4,
      category: "pieces",
      flavor: "Geronimo.",
    },
    instant((_inst, api) => grantInventory(api, "p", 2)),
  ),
  card(
    {
      id: "supply_drop",
      icon: "Package",
      name: "Supply Drop",
      description: "A knight is airlifted into your reserves. Later, spend a turn to drop it onto any empty square.",
      tier: 3,
      category: "pieces",
      flavor: "Batteries not included.",
    },
    // Grants a knight to the crazyhouse-style pocket instead of placing it now;
    // the drop is a normal turn-consuming move generated by the engine.
    instant((_inst, api) => grantInventory(api, "n", 1)),
  ),
  card(
    {
      id: "clone_army",
      icon: "CopyPlus",
      name: "Clone Army",
      description: "Three photocopier flashes in a row: three new pawns land in your pocket, ready to drop onto empty squares on later turns.",
      tier: 5,
      category: "pieces",
      flavor: "Roll call is going to take a while.",
    },
    instant((_inst, api) => grantInventory(api, "p", 3)),
  ),
  card(
    {
      id: "rent_a_rook",
      icon: "Building2",
      name: "Rent-a-Rook",
      description: "A rook arrives on loan: place it on an empty square in your half, then it drives off after 4 of your turns.",
      tier: 4,
      category: "pieces",
      flavor: "Please return it with a full tank.",
    },
    summonTemp("r", 4, myHalfZone),
  ),
  card(
    {
      id: "cavalry_charge",
      icon: "Rabbit",
      name: "Cavalry Charge",
      description: "Choose one of your knights. It charges in one horizontal or vertical direction, removes the first enemy piece (not a king) in that line, and lands on that square or on an empty square beyond it, stopping before the next piece or the board edge. A friendly piece or an enemy king in the path blocks the charge. Once.",
      tier: 5,
      category: "attack",
      requires: ["n"],
      flavor: "Sound the bugle.",
    },
    lineSweep("n", ORTHO_DIRS, 1),
  ),
  card(
    {
      id: "insurance",
      icon: "Umbrella",
      name: "Insurance",
      description: "The first time your queen is captured, a new knight appears on your queen's starting square (d1 for White, d8 for Black), but only if that square is empty. Triggers once.",
      tier: 4,
      category: "pieces",
      flavor: "Read the fine print, they always do.",
    },
    {
      kind: "passive",
      onMovePlayed: (inst, move, api) => {
        if (move.color !== api.opp || move.captured !== "q") return;
        const home = SQ(3, api.me === "w" ? 0 : 7);
        if (!api.board.pieces[home]) api.place(home, "n", api.me);
        inst.spent = true;
      },
      status: () => "policy active",
    },
  ),
  card(
    {
      id: "blood_pact",
      icon: "Droplets",
      name: "Blood Pact",
      description: "Sign in blood: promote one of your pawns to a queen at once, but a random other pawn of yours bursts and is lost.",
      tier: 7,
      category: "pieces",
      requires: ["p"],
      flavor: "The wax seal is still warm.",
    },
    activated(
      (_inst, api, picks) =>
        picks.length > 0
          ? null
          : {
              kind: "square",
              label: "Choose the pawn to promote",
              squares: mySquares(api.board, api.me, "p"),
            },
      (_inst, api, picks) => {
        const sq = picks[0]?.square;
        if (sq == null) return;
        api.setPieceType(sq, "q");
        const others = mySquares(api.board, api.me, "p").filter((s) => s !== sq);
        if (others.length) api.removePiece(others[api.rng.int(others.length)]);
      },
    ),
  ),
];
