// Funny set: SUMMONS & REINFORCEMENTS. Most cards grant a piece to your
// crazyhouse-style pocket (grantInventory, a free instant): you draft it now
// and spend a later turn to DROP it, so the summon itself costs no move. The
// rest reuse summonTemp (a rental that expires), lineSweep (a charging piece),
// or a conditional passive modeled on the library's trade_up / insurance
// pattern. The engine's drop generator already refuses to drop a pawn on rank
// 1 or 8, and a king is never bankable.

import { Buff, Mech, Square } from "./shared";
import {
  card,
  summonTemp,
  lineSweep,
  activated,
  grantInventory,
  instant,
  mySquares,
  myHalfZone,
  addEffect,
  pawnRankOk,
  KNIGHT_LEAPS,
  ORTHO_DIRS,
  FILE,
  RANK,
  SQ,
  inBoard,
} from "./shared";

/** Cavalry Charge: the ortho line-sweep charge, then a landing shockwave. After
 * the knight lands, every enemy piece (never a king) a knight-leap from the
 * landing square is bonked one square back toward that piece's home rank; a
 * piece that cannot be pushed (edge, blocked, or an illegal pawn square) still
 * takes the impact flash. Pure function of state (fixed leap order, no RNG), so
 * it replays identically on both clients. */
function cavalryCharge(): Mech {
  const base = lineSweep("n", ORTHO_DIRS, 2);
  const charged: Mech = {
    ...base,
    effect: (inst, api, picks) => {
      base.effect?.(inst, api, picks);
      const to = picks[1]?.square;
      if (to == null) return;
      const knight = api.board.pieces[to];
      if (!knight || knight.color !== api.me || knight.type !== "n") return;
      const back = api.opp === "w" ? -8 : 8;
      const hit: Square[] = [];
      for (const [df, dr] of KNIGHT_LEAPS) {
        const f = FILE(to) + df, r = RANK(to) + dr;
        if (!inBoard(f, r)) continue;
        const sq = SQ(f, r);
        const p = api.board.pieces[sq];
        if (!p || p.color !== api.opp || p.type === "k") continue;
        const dest = sq + back;
        if (
          dest >= 0 &&
          dest < 64 &&
          !api.board.pieces[dest] &&
          (p.type !== "p" || pawnRankOk(dest))
        ) {
          api.relocate(sq, dest);
          hit.push(dest);
        } else {
          hit.push(sq);
        }
      }
      if (hit.length) addEffect(api, { kind: "bonk", squares: hit, owner: api.me, turns: 1 });
    },
  };
  return charged;
}

export const FUNNY_SUMMONS: Buff[] = [
  card(
    {
      id: "summon_intern",
      icon: "UserPlus",
      name: "Summon Intern",
      description: "Two new pawns join your pocket. Later, spend turns to drop them onto empty squares.",
      tier: 2,
      category: "pieces",
      flavor: "They brought their own lanyards.",
    },
    instant((_inst, api) => grantInventory(api, "p", 2)),
  ),
  card(
    {
      id: "pizza_delivery",
      icon: "Pizza",
      name: "Pizza Delivery",
      description: "A knight zips in on a scooter delivering pizza, and the garlic bread on the side is a pawn: both park in your pocket, ready to drop onto empty squares on later turns.",
      tier: 4,
      category: "pieces",
      flavor: "Thirty minutes or the fork is free.",
    },
    instant((_inst, api) => {
      grantInventory(api, "n", 1);
      grantInventory(api, "p", 1);
    }),
  ),
  card(
    {
      id: "reinforcements",
      icon: "Users",
      name: "Reinforcements",
      description: "Three pawns parachute into your pocket: drop them onto empty squares on later turns.",
      tier: 4,
      category: "pieces",
      flavor: "Geronimo.",
    },
    instant((_inst, api) => grantInventory(api, "p", 3)),
  ),
  card(
    {
      id: "supply_drop",
      icon: "Package",
      name: "Supply Drop",
      description: "A knight is airlifted into your reserves, and a crate of spares lands with it as a pawn. Later, spend turns to drop them onto empty squares.",
      tier: 3,
      category: "pieces",
      flavor: "Batteries not included.",
    },
    // Grants a knight (plus a spare pawn) to the crazyhouse-style pocket
    // instead of placing them now; each drop is a normal turn-consuming move
    // generated by the engine.
    instant((_inst, api) => {
      grantInventory(api, "n", 1);
      grantInventory(api, "p", 1);
    }),
  ),
  card(
    {
      id: "clone_army",
      icon: "CopyPlus",
      name: "Clone Army",
      description: "Four photocopier flashes in a row: four new pawns land in your pocket, ready to drop onto empty squares on later turns.",
      tier: 5,
      category: "pieces",
      flavor: "Roll call is going to take a while.",
    },
    instant((_inst, api) => grantInventory(api, "p", 4)),
  ),
  card(
    {
      id: "rent_a_rook",
      icon: "Building2",
      name: "Rent-a-Rook",
      description: "A rook arrives on loan: place it on an empty square in your half. It cannot be captured while it is on loan (it is not yours to lose), then it drives off after 5 of your turns.",
      tier: 5,
      category: "pieces",
      flavor: "Please return it with a full tank.",
    },
    summonTemp("r", 5, myHalfZone, { shield: true }),
  ),
  card(
    {
      id: "cavalry_charge",
      icon: "Rabbit",
      name: "Cavalry Charge",
      description: "Choose one of your knights. It charges in one horizontal or vertical direction, removes up to the first two enemy pieces (not kings) in that line, and lands on the last cleared square or on an empty square beyond it, stopping before the next piece or the board edge. As it lands, the shock bonks every enemy piece a knight's leap from the landing square one square back toward that piece's home rank. A friendly piece or an enemy king in the path blocks the charge. Once.",
      tier: 5,
      category: "attack",
      requires: ["n"],
      flavor: "Sound the bugle.",
    },
    cavalryCharge(),
  ),
  card(
    {
      id: "insurance",
      icon: "Umbrella",
      name: "Insurance",
      description: "The first time your queen is captured, a new knight appears on your queen's starting square (d1 for White, d8 for Black), or on the nearest empty square of that rank if her home is taken. Triggers once.",
      tier: 4,
      category: "pieces",
      flavor: "Read the fine print, they always do.",
    },
    {
      kind: "passive",
      onMovePlayed: (inst, move, api) => {
        if (move.color !== api.opp || move.captured !== "q") return;
        // Pay out on the home square, or the nearest empty back-rank square if
        // it is taken (ties break toward the a-file, deterministic on every
        // replica).
        const rank = api.me === "w" ? 0 : 7;
        let spot = api.board.pieces[SQ(3, rank)] ? -1 : SQ(3, rank);
        if (spot < 0) {
          let bestD = Infinity;
          for (let f = 0; f < 8; f++) {
            const sq = SQ(f, rank);
            if (api.board.pieces[sq]) continue;
            const d = Math.abs(f - 3);
            if (d < bestD) {
              bestD = d;
              spot = sq;
            }
          }
        }
        if (spot >= 0) api.place(spot, "n", api.me);
        inst.spent = true;
      },
      status: () => "policy active",
    },
  ),
  card(
    {
      id: "blood_pact",
      icon: "Droplets",
      name: "Blood Pact",
      description: "Sign in blood: promote one of your pawns to a queen at once, but another pawn of yours, you choose which, bursts and is lost.",
      tier: 7,
      category: "pieces",
      requires: ["p"],
      flavor: "The wax seal is still warm.",
    },
    // You pick the sacrifice now (it used to burst at random), so the pact
    // never pops a pawn you still needed. With no second pawn there is no
    // second pick and nothing bursts.
    activated(
      (_inst, api, picks) => {
        if (picks.length === 0) {
          return {
            kind: "square",
            label: "Choose the pawn to promote",
            squares: mySquares(api.board, api.me, "p"),
          };
        }
        if (picks.length === 1) {
          const others = mySquares(api.board, api.me, "p").filter(
            (s) => s !== picks[0].square,
          );
          if (!others.length) return null;
          return {
            kind: "square",
            label: "Choose the pawn that bursts",
            squares: others,
          };
        }
        return null;
      },
      (_inst, api, picks) => {
        const sq = picks[0]?.square;
        if (sq == null) return;
        api.setPieceType(sq, "q");
        const burst = picks[1]?.square;
        if (burst != null && burst !== sq && api.board.pieces[burst]) {
          api.removePiece(burst);
        }
      },
    ),
  ),
];
