/// <reference types="@cloudflare/workers-types" />

import { DurableObject } from "cloudflare:workers";
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import { default as handler } from "./.open-next/worker.js";
import { moveToUCI } from "./src/engine/board";
import { PLAYABLE_NERFS, pickNerfPair } from "./src/engine/nerfs/library";
import {
  NerfGame,
  activateBuff,
  bankDraft,
  buffNextTarget,
  enableDraftMode,
  legalMoves,
  newGame,
  pickDraftCard,
  playMove,
  resign,
} from "./src/engine/game";
import type { BuffPick } from "./src/engine/buff";
import { RNG } from "./src/engine/rng";
import { Color } from "./src/engine/types";
import { sessionTokenFromCookieHeader, userForSession } from "./src/lib/server/auth";
import { ensureSchema } from "./src/lib/server/schema";
import { loadCategoryRatings, recordFinishedGame, RatingChange } from "./src/lib/server/games";
import { categoryForTimeControl, type SpeedCategory } from "./src/lib/speed";
import { censorText, findProfanity } from "./src/lib/profanity";
import { glickoUpdatePair } from "./src/lib/glicko";

type Result = NerfGame["result"];
type Setup = {
  whiteNerfId: string;
  blackNerfId: string;
  seed: number;
  timeSec: number;
  incrementSec: number;
};
type SeatUser = { id: string; name: string; rating: number; rd?: number; vol?: number; avatar?: string | null };
type ChatEntry = { color: Color; name: string; text: string; at: number };
// Spectator-room chat: watchers only, players never see it.
type SpectatorChatEntry = { name: string; text: string; at: number };
// One resolved draft interaction, stored in order. `ply` is the number of
// accepted moves at the moment the action happened, so replaying moves and
// actions interleaved through the engine rebuilds the exact game state
// (board mutations, RNG stream, and all) on reconnects and DO restarts.
type StoredDraftAction =
  | { ply: number; color: Color; a: "pick"; index: number; cards: { id: string; tier: number }[] }
  | { ply: number; color: Color; a: "bank" }
  | { ply: number; color: Color; a: "use"; buffIndex: number; picks: BuffPick[] };
type StoredMatch = {
  id: string;
  setup: Setup;
  tokens: Record<Color, string>;
  disconnectedAt: Partial<Record<Color, number>>;
  opponentGoneNotified: Partial<Record<Color, boolean>>;
  moves: string[];
  result: Result;
  clocks: Record<Color, number>;
  runningSince: number | null;
  drawOfferBy: Color | null;
  // Pending takeback request (casual games only).
  takebackOfferBy?: Color | null;
  createdAt: number;
  startedAt: number | null;
  completedAt: number | null;
  // Rated matchmade games carry the two accounts; friend games may carry them
  // too (for history) but stay casual.
  rated?: boolean;
  users?: Partial<Record<Color, SeatUser>>;
  recorded?: boolean;
  // Matchmade and rematch games start automatically once both seats connect
  // (friend games wait in the lobby for a join instead).
  autoStart?: boolean;
  // Direct challenge: only this username may join as black. Never listed as
  // an open challenge in the lobby.
  invitedUsername?: string;
  rematchOfferBy?: Color | null;
  // Set once a rematch match has been created from this one.
  rematchedTo?: string | null;
  chat?: ChatEntry[];
  spectatorChat?: SpectatorChatEntry[];
  // Colors that voluntarily revealed their rule to the table mid-game.
  revealed?: Partial<Record<Color, boolean>>;
  // Draft ruleset games. Draft matches are always casual: createMatch never
  // honors a rated request for them and the queue never creates them.
  draft?: boolean;
  // Friend-game setting: both seats see each other's pending offer cards.
  picksVisible?: boolean;
  // Seed for the draft engine RNG (offer rolls). Never sent to any client:
  // it would let a client predict every future offer.
  draftSeed?: number;
  draftActions?: StoredDraftAction[];
  // Opening nerf draft (Draft games only). Dealt when the second seat
  // arrives; the match stays un-started (clocks off, moves rejected) until
  // both seats have picked. Options are public to both seats; each pick's
  // identity follows the usual reveal rules.
  nerfOptions?: Record<Color, string[]>;
  nerfPicks?: Partial<Record<Color, number>>;
};
type SessionAttachment = {
  id: string;
  matchId?: string;
  color?: Color;
  token?: string;
  // Account attached at websocket upgrade from the session cookie.
  userId?: string;
  username?: string;
  // Chat mute (moderation): timestamp the mute expires, read at connect time.
  mutedUntil?: number;
  // Match id this socket spectates (mutually exclusive with a seat).
  watching?: string;
};
type QueueEntry = {
  attachmentId: string;
  userId: string;
  username: string;
  rating: number;
  rd?: number;
  vol?: number;
  avatar?: string | null;
  at: number;
};
type ClientFrame =
  | { t: "create"; d?: { timeSec?: unknown; incrementSec?: unknown; draft?: unknown; picksVisible?: unknown; invite?: unknown } }
  | { t: "join"; d?: { id?: unknown } }
  | { t: "reconnect"; d?: { id?: unknown; color?: unknown; token?: unknown } }
  | { t: "move"; d?: { u?: unknown; ply?: unknown } }
  | { t: "resign" }
  | { t: "claimWin" }
  | { t: "claimDraw" }
  | { t: "drawOffer" }
  | { t: "drawAccept" }
  | { t: "drawDecline" }
  | { t: "takebackOffer" }
  | { t: "takebackAccept" }
  | { t: "takebackDecline" }
  | { t: "queue"; d?: { pool?: unknown } }
  | { t: "queueCancel" }
  | { t: "watch"; d?: { id?: unknown } }
  | { t: "watchLeave" }
  | { t: "lobby" }
  | { t: "rematch" }
  | { t: "chat"; d?: { text?: unknown } }
  | { t: "schat"; d?: { text?: unknown } }
  | { t: "reveal" }
  | { t: "dtPick"; d?: { index?: unknown } }
  | { t: "dtBank" }
  | { t: "dtUse"; d?: { buffIndex?: unknown; picks?: unknown } }
  | { t: "dtTarget"; d?: { buffIndex?: unknown; picks?: unknown } }
  | { t: "dtNerfPick"; d?: { index?: unknown } }
  | { t: "p" };

export interface Env {
  GAME_SERVER: DurableObjectNamespace<GameServer>;
  GAME_SERVER_ORIGINS?: string;
  DB: D1Database;
}

// Quick-pairing pools for rated matchmaking. Keys are the wire names clients
// send; keep them in sync with QUEUE_POOL_OPTIONS in the QueueButton UI.
const QUEUE_POOLS: Record<string, { timeSec: number; incrementSec: number }> = {
  "1+0": { timeSec: 60, incrementSec: 0 },
  "2+1": { timeSec: 120, incrementSec: 1 },
  "3+0": { timeSec: 180, incrementSec: 0 },
  "3+2": { timeSec: 180, incrementSec: 2 },
  "5+0": { timeSec: 300, incrementSec: 0 },
  "5+3": { timeSec: 300, incrementSec: 3 },
  "10+0": { timeSec: 600, incrementSec: 0 },
  "10+5": { timeSec: 600, incrementSec: 5 },
  "15+10": { timeSec: 900, incrementSec: 10 },
};

const socketPath = "/socket/v1";
const globalServerName = "nerfchess-global";
const disconnectGraceMs = 15 * 1000;
// How long the opponent must have been disconnected before the remaining
// player may claim the game by abandonment (claimWin / claimDraw).
const abandonmentClaimMs = 30 * 1000;
// Leftover Durable Object storage from the retired house-player system,
// cleared on first alarm/health check so the lobby never resurrects them.
const legacyBotKeys = ["bots:seeks", "bots:seeded:v1", "bots:nextGameAt"];
// Bumped whenever the worker changes in a way we want to confirm shipped.
// Surfaced at GET /healthz so a deploy can be verified without Cloudflare
// dashboard access (compare the value there against this one).
const buildVersion = "no-bots-1";
// Lichess-style start-of-game grace: a player's clock only starts charging 10
// seconds into their first move, so nobody loses time to a slow page load.
const firstMoveGraceMs = 10 * 1000;

function randomInt(max: number): number {
  const values = new Uint32Array(1);
  crypto.getRandomValues(values);
  return values[0] % max;
}

function randomCode(length = 5): string {
  const chars = "BCDFGHJKMNPQRSTVWXYZ23456789";
  let code = "";
  for (let i = 0; i < length; i++) code += chars[randomInt(chars.length)];
  return code;
}

function newToken(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

function makeSeed(): number {
  return randomInt(2 ** 31);
}

function pickNerfIds(): { whiteNerfId: string; blackNerfId: string } {
  return pickNerfPair(randomInt);
}

function isColor(value: unknown): value is Color {
  return value === "w" || value === "b";
}

function matchKey(id: string): string {
  return `match:${id}`;
}

function send(ws: WebSocket | undefined, t: string, d?: unknown) {
  if (!ws || ws.readyState !== WebSocket.OPEN) return;
  ws.send(JSON.stringify(d === undefined ? { t } : { t, d }));
}

function error(ws: WebSocket, code: string, message: string) {
  send(ws, "error", { code, message });
}

function moveByUci(game: NerfGame, uci: string) {
  return legalMoves(game).find((candidate) => moveToUCI(candidate) === uci);
}

export class GameServer extends DurableObject<Env> {
  private sessions = new Map<WebSocket, SessionAttachment>();
  private dbReady: Promise<boolean> | null = null;

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    for (const ws of this.ctx.getWebSockets()) {
      const attachment = ws.deserializeAttachment() as SessionAttachment | null;
      if (attachment) this.sessions.set(ws, attachment);
    }
  }

  // Resolves to true when D1 is configured and its schema is in place.
  // Account features degrade to anonymous play when it isn't.
  private async db(): Promise<D1Database | null> {
    if (!this.env.DB) return null;
    if (!this.dbReady) {
      this.dbReady = ensureSchema(this.env.DB).then(
        () => true,
        () => false,
      );
    }
    return (await this.dbReady) ? this.env.DB : null;
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/healthz") {
      await this.purgeLegacyBotState();
      await this.cleanupExpired();

      const matches = [...(await this.ctx.storage.list<StoredMatch>({ prefix: "match:" })).values()];
      const alarmAt = await this.ctx.storage.getAlarm();

      return Response.json({
        ok: true,
        version: buildVersion,
        sockets: this.sessions.size,
        games: matches.length,
        alarmAt, // ms epoch of the next scheduled maintenance pass, if any
        alarmInMs: alarmAt ? alarmAt - Date.now() : null,
      });
    }

    if (url.pathname !== socketPath) return new Response("Not found", { status: 404 });
    if (request.headers.get("Upgrade") !== "websocket") {
      return new Response("Expected WebSocket", { status: 426 });
    }
    if (!this.originAllowed(request)) {
      return new Response("Forbidden", { status: 403 });
    }

    // Same-origin websocket upgrades carry the session cookie; attach the
    // account (if any) so queueing and rated games know who this socket is.
    const attachment: SessionAttachment = { id: crypto.randomUUID() };
    const db = await this.db();
    if (db) {
      try {
        const token = sessionTokenFromCookieHeader(request.headers.get("Cookie"));
        const user = await userForSession(db, token);
        if (user) {
          attachment.userId = user.id;
          attachment.username = user.username;
          if (user.muted_until && user.muted_until > Date.now()) {
            attachment.mutedUntil = user.muted_until;
          }
        }
      } catch {
        // Anonymous on any auth failure.
      }
    }

    const pair = new WebSocketPair();
    const [client, server] = Object.values(pair);
    server.serializeAttachment(attachment);
    this.sessions.set(server, attachment);
    this.ctx.acceptWebSocket(server);

    return new Response(null, { status: 101, webSocket: client });
  }

  async webSocketMessage(ws: WebSocket, message: ArrayBuffer | string) {
    let frame: ClientFrame;
    try {
      frame = JSON.parse(typeof message === "string" ? message : new TextDecoder().decode(message)) as ClientFrame;
    } catch {
      return error(ws, "bad_json", "Messages must be JSON objects.");
    }

    switch (frame.t) {
      case "create":
        return this.createMatch(ws, frame.d);
      case "join":
        return this.joinMatch(ws, frame.d);
      case "reconnect":
        return this.reconnectMatch(ws, frame.d);
      case "move":
        return this.playClientMove(ws, frame.d);
      case "resign":
        return this.resignGame(ws);
      case "claimWin":
        return this.claimAbandonment(ws, false);
      case "claimDraw":
        return this.claimAbandonment(ws, true);
      case "drawOffer":
        return this.offerDraw(ws);
      case "drawAccept":
        return this.acceptDraw(ws);
      case "drawDecline":
        return this.declineDraw(ws);
      case "takebackOffer":
        return this.offerTakeback(ws);
      case "takebackAccept":
        return this.acceptTakeback(ws);
      case "takebackDecline":
        return this.declineTakeback(ws);
      case "queue":
        return this.queueJoin(ws, frame.d);
      case "queueCancel":
        return this.queueLeave(ws, true);
      case "watch":
        return this.watchMatch(ws, frame.d);
      case "watchLeave":
        return this.watchLeave(ws);
      case "lobby":
        return this.lobbySnapshot(ws);
      case "rematch":
        return this.rematchRequest(ws);
      case "chat":
        return this.chatMessage(ws, frame.d);
      case "schat":
        return this.spectatorChatMessage(ws, frame.d);
      case "reveal":
        return this.revealRule(ws);
      case "dtPick":
        return this.draftPick(ws, frame.d);
      case "dtBank":
        return this.draftBank(ws);
      case "dtUse":
        return this.draftUse(ws, frame.d);
      case "dtTarget":
        return this.draftTarget(ws, frame.d);
      case "dtNerfPick":
        return this.nerfDraftPick(ws, frame.d);
      case "p":
        return this.sendClocks(ws);
      default:
        return error(ws, "unknown_message", "Unknown message type.");
    }
  }

  async webSocketClose(ws: WebSocket) {
    await this.queueLeave(ws, false);
    this.notifyWatcherCount(ws);
    await this.detachSession(ws);
  }

  async webSocketError(ws: WebSocket) {
    await this.queueLeave(ws, false);
    this.notifyWatcherCount(ws);
    await this.detachSession(ws);
  }

  // When a spectating socket goes away, tell the remaining watchers the new
  // count. Must run before the session is dropped from the map.
  private notifyWatcherCount(ws: WebSocket) {
    const session = this.sessions.get(ws);
    if (!session?.watching) return;
    const id = session.watching;
    this.sessions.delete(ws);
    this.broadcastWatchers(id);
  }

  private watcherCount(matchId: string): number {
    return this.watcherInfo(matchId).n;
  }

  // Count plus the signed-in watchers' usernames (deduped across tabs);
  // anonymous watchers only contribute to the count.
  private watcherInfo(matchId: string): { n: number; names: string[] } {
    let n = 0;
    const names = new Set<string>();
    for (const [ws, session] of this.sessions) {
      if (session.watching === matchId && ws.readyState === WebSocket.OPEN) {
        n++;
        if (session.username) names.add(session.username);
      }
    }
    return { n, names: [...names].slice(0, 30) };
  }

  private broadcastWatchers(matchId: string) {
    const { n, names } = this.watcherInfo(matchId);
    for (const [ws, session] of this.sessions) {
      if (ws.readyState !== WebSocket.OPEN) continue;
      if (session.watching === matchId || session.matchId === matchId) {
        send(ws, "watchers", { n, names });
      }
    }
  }

  async alarm() {
    // Nothing in here may throw out of the handler: an uncaught alarm error
    // stops rescheduling until the next external event (no flag enforcement).
    try {
      await this.purgeLegacyBotState();
    } catch (err) {
      console.error("legacy bot purge failed", err);
    }
    try {
      await this.maintenanceAll();
    } catch (err) {
      console.error("maintenanceAll failed", err);
    }
  }

  // The retired house-player system left seeks/seed markers in DO storage and
  // unfinished bot matches that no longer have anything to move for them.
  // Drop both once so old state can't wedge or clutter the lobby.
  private legacyBotStatePurged = false;

  private async purgeLegacyBotState() {
    if (this.legacyBotStatePurged) return;
    this.legacyBotStatePurged = true;
    await this.ctx.storage.delete(legacyBotKeys);
    const matches = await this.ctx.storage.list<StoredMatch & { bots?: unknown }>({ prefix: "match:" });
    for (const match of matches.values()) {
      if (match.bots && !match.completedAt) await this.deleteMatch(match);
    }
  }

  private originAllowed(request: Request): boolean {
    const origin = request.headers.get("Origin");
    const configured = (this.env.GAME_SERVER_ORIGINS || "")
      .split(",")
      .map((allowed) => allowed.trim())
      .filter(Boolean);

    // Explicit allowlist: only the configured origins may connect.
    if (configured.length > 0) {
      return !!origin && configured.includes(origin);
    }

    // No allowlist configured: fail closed to same-origin only. Requests
    // without an Origin header (non-browser clients, which cannot be targets
    // of browser CSRF) are still permitted; cross-origin browser requests are
    // rejected instead of being allowed unconditionally.
    if (!origin) return true;
    try {
      return new URL(origin).host === new URL(request.url).host;
    } catch {
      return false;
    }
  }

  private async loadMatch(id: string): Promise<StoredMatch | null> {
    return (await this.ctx.storage.get<StoredMatch>(matchKey(id))) ?? null;
  }

  private async saveMatch(match: StoredMatch, schedule = true) {
    await this.ctx.storage.put(matchKey(match.id), match);
    if (schedule) await this.scheduleAlarmForMatch(match);
  }

  private async deleteMatch(match: StoredMatch) {
    for (const [ws, session] of this.sessions) {
      if (session.matchId === match.id) {
        this.sessions.delete(ws);
        ws.close(1000, "Game expired");
      }
    }
    await this.ctx.storage.delete(matchKey(match.id));
  }

  private connectedSession(matchId: string, color: Color): WebSocket | undefined {
    for (const [ws, session] of this.sessions) {
      if (session.matchId === matchId && session.color === color && ws.readyState === WebSocket.OPEN) return ws;
    }
    return undefined;
  }

  private connectedSessions(matchId: string): WebSocket[] {
    return [...this.sessions]
      .filter(([ws, session]) => session.matchId === matchId && ws.readyState === WebSocket.OPEN)
      .map(([ws]) => ws);
  }

  private session(ws: WebSocket): SessionAttachment {
    const restored = ws.deserializeAttachment() as SessionAttachment | null;
    const session = this.sessions.get(ws) ?? restored;
    if (!session) {
      const next = { id: crypto.randomUUID() };
      this.sessions.set(ws, next);
      ws.serializeAttachment(next);
      return next;
    }
    this.sessions.set(ws, session);
    return session;
  }

  private async attachSession(ws: WebSocket, match: StoredMatch, color: Color) {
    const existing = this.connectedSession(match.id, color);
    if (existing && existing !== ws) existing.close(1000, "Reconnected from another tab");

    const session = { ...this.session(ws), matchId: match.id, color, token: match.tokens[color] };
    delete session.watching;
    this.sessions.set(ws, session);
    ws.serializeAttachment(session);
    delete match.disconnectedAt[color];
    delete match.opponentGoneNotified[color];

    // Remember which account holds this seat (used for names in the UI and
    // for game history). Matchmade seats are assigned at pairing and are
    // never overwritten here.
    if (session.userId && session.username && !match.users?.[color]) {
      let rating = 1500;
      let rd = 350;
      let vol = 0.06;
      let avatar: string | null = null;
      const db = await this.db();
      if (db) {
        const row = await this.seatCategoryRating(
          db,
          session.userId,
          categoryForTimeControl(match.setup.timeSec, match.setup.incrementSec),
        );
        if (row) {
          rating = row.rating;
          rd = row.rd;
          vol = row.vol;
          avatar = row.avatar;
        }
      }
      match.users = {
        ...(match.users ?? {}),
        [color]: { id: session.userId, name: session.username, rating, rd, vol, avatar },
      };
    }
  }

  private async detachSession(ws: WebSocket) {
    const session = this.sessions.get(ws) ?? (ws.deserializeAttachment() as SessionAttachment | null);
    this.sessions.delete(ws);
    if (!session?.matchId || !session.color) return;
    if (this.connectedSession(session.matchId, session.color)) return;

    const match = await this.loadMatch(session.matchId);
    if (!match) return;
    match.disconnectedAt[session.color] = Date.now();
    match.opponentGoneNotified[session.color] = false;
    await this.saveMatch(match);
  }

  private async newCode(length = 5): Promise<string> {
    let code = randomCode(length);
    while (await this.loadMatch(code)) code = randomCode(length);
    return code;
  }

  private socketForAttachment(id: string): WebSocket | undefined {
    for (const [ws, session] of this.sessions) {
      if (session.id === id && ws.readyState === WebSocket.OPEN) return ws;
    }
    return undefined;
  }

  // Rating shown/staked for a seat, from the independent per-time-control
  // buckets (seeded from the legacy shared rating on first contact).
  private async seatCategoryRating(
    db: D1Database,
    userId: string,
    category: SpeedCategory,
  ): Promise<{ rating: number; rd: number; vol: number; avatar: string | null } | null> {
    try {
      const ratings = await loadCategoryRatings(db, [userId], category);
      const r = ratings.get(userId);
      if (!r) return null;
      const row = await db
        .prepare("SELECT avatar FROM users WHERE id = ?")
        .bind(userId)
        .first<{ avatar: string | null }>();
      return { rating: r.rating, rd: r.rd, vol: r.vol, avatar: row?.avatar ?? null };
    } catch {
      return null;
    }
  }

  private playersPayload(match: StoredMatch) {
    const seat = (color: Color) => {
      const user = match.users?.[color];
      return user
        ? { name: user.name, rating: Math.round(user.rating), avatar: user.avatar ?? null }
        : { name: "Anonymous", rating: null, avatar: null };
    };
    return { w: seat("w"), b: seat("b") };
  }

  private sendWatchers(match: StoredMatch, t: string, d?: unknown) {
    for (const [ws, session] of this.sessions) {
      if (session.watching === match.id && ws.readyState === WebSocket.OPEN) send(ws, t, d);
    }
  }

  // Projected rating movement for each seat before the game is decided, so
  // players can see what a win/draw/loss is worth ("+8 / +0 / -8").
  private ratingPreview(match: StoredMatch): Record<Color, { win: number; draw: number; loss: number }> | null {
    if (!match.rated || !match.users?.w || !match.users?.b) return null;
    const w = { rating: match.users.w.rating, rd: match.users.w.rd ?? 350, vol: match.users.w.vol ?? 0.06 };
    const b = { rating: match.users.b.rating, rd: match.users.b.rd ?? 350, vol: match.users.b.vol ?? 0.06 };
    const whiteWins = glickoUpdatePair(w, b, 1);
    const draw = glickoUpdatePair(w, b, 0.5);
    const blackWins = glickoUpdatePair(w, b, 0);
    const delta = (after: number, before: number) => Math.round(after - before);
    return {
      w: {
        win: delta(whiteWins.a.rating, w.rating),
        draw: delta(draw.a.rating, w.rating),
        loss: delta(blackWins.a.rating, w.rating),
      },
      b: {
        win: delta(blackWins.b.rating, b.rating),
        draw: delta(draw.b.rating, b.rating),
        loss: delta(whiteWins.b.rating, b.rating),
      },
    };
  }

  private startPayload(match: StoredMatch, color: Color) {
    const clocks = this.currentClocks(match);
    const myNerfId = color === "w" ? match.setup.whiteNerfId : match.setup.blackNerfId;
    const masterRng = new RNG(match.setup.seed);
    const wSeed = masterRng.fork().getState();
    const bSeed = masterRng.fork().getState();
    const nerfSeed = color === "w" ? wSeed : bSeed;
    const preview = this.ratingPreview(match);
    const revealed: Partial<Record<Color, string>> = {};
    if (match.revealed?.w) revealed.w = match.setup.whiteNerfId;
    if (match.revealed?.b) revealed.b = match.setup.blackNerfId;
    // Draft matches ship the public action record (for exact board replay)
    // plus this seat's filtered view of the live draft state.
    let draftExtras: Record<string, unknown> | null = null;
    if (match.draft) {
      const game = match.startedAt ? this.gameFromMatch(match) : null;
      const opp: Color = color === "w" ? "b" : "w";
      draftExtras = {
        draft: true,
        picksVisible: !!match.picksVisible,
        dtActions: this.publicDraftActions(match),
        ...(game?.buffs ? { dtState: this.draftStateFor(game, match, color) } : {}),
        // The opening nerf draft, while unresolved. Both sides' options are
        // public; only this seat's own pick index is included.
        ...(match.nerfOptions && !match.startedAt
          ? {
              nerfDraft: {
                options: match.nerfOptions,
                myPick: match.nerfPicks?.[color] ?? null,
                oppPicked: match.nerfPicks?.[opp] != null,
              },
            }
          : {}),
      };
    }
    return {
      id: match.id,
      color,
      token: match.tokens[color],
      nerfId: myNerfId,
      nerfSeed,
      timeSec: match.setup.timeSec,
      incrementSec: match.setup.incrementSec,
      wc: Math.round(clocks.w),
      bc: Math.round(clocks.b),
      moves: match.moves,
      players: this.playersPayload(match),
      rated: !!match.rated,
      chat: match.chat ?? [],
      ...(Object.keys(revealed).length ? { revealed } : {}),
      ...(preview ? { preview } : {}),
      ...(draftExtras ?? {}),
    };
  }

  private sendStart(match: StoredMatch, color: Color) {
    const ws = this.connectedSession(match.id, color);
    send(ws, "start", this.startPayload(match, color));
    if (match.result) {
      const clocks = this.currentClocks(match);
      send(ws, "end", {
        result: match.result,
        wc: Math.round(clocks.w),
        bc: Math.round(clocks.b),
        nerfs: { w: match.setup.whiteNerfId, b: match.setup.blackNerfId },
      });
    }
  }

  private broadcast(match: StoredMatch, t: string, d?: unknown) {
    send(this.connectedSession(match.id, "w"), t, d);
    send(this.connectedSession(match.id, "b"), t, d);
  }

  private gameFromMatch(match: StoredMatch): NerfGame | null {
    if (!match.startedAt) return null;
    const white = PLAYABLE_NERFS.find((nerf) => nerf.id === match.setup.whiteNerfId);
    const black = PLAYABLE_NERFS.find((nerf) => nerf.id === match.setup.blackNerfId);
    if (!white || !black) return null;

    let game = newGame(white, black, match.setup.seed);
    if (match.draft) enableDraftMode(game, match.draftSeed ?? match.setup.seed);
    // Draft actions replay interleaved with moves: an action recorded at ply
    // N happened after N accepted moves, so replaying both streams through
    // the engine reproduces the RNG stream, offers, and board mutations
    // exactly. Classic matches carry no actions and take the same path.
    const actions = match.draftActions ?? [];
    let cursor = 0;
    const applyActionsUpTo = (ply: number) => {
      while (cursor < actions.length && actions[cursor].ply <= ply) {
        this.applyStoredDraftAction(game, actions[cursor]);
        cursor += 1;
      }
    };
    for (let i = 0; i < match.moves.length; i++) {
      applyActionsUpTo(i);
      const move = moveByUci(game, match.moves[i]);
      if (!move) return null;
      game = playMove(game, move);
    }
    applyActionsUpTo(match.moves.length);
    if (match.result) game.result = match.result;
    return game;
  }

  private applyStoredDraftAction(game: NerfGame, action: StoredDraftAction) {
    if (action.a === "pick") pickDraftCard(game, action.color, action.index);
    else if (action.a === "bank") bankDraft(game, action.color);
    else activateBuff(game, action.color, action.buffIndex, action.picks);
  }

  // Moves the given color has already played (moves alternate w, b, w, …).
  private movesByColor(match: StoredMatch, color: Color): number {
    return color === "w" ? Math.ceil(match.moves.length / 2) : Math.floor(match.moves.length / 2);
  }

  // Whose turn it is. Turns always alternate w, b, w, … (no nerf skips a
  // turn), so this is pure move-count parity — no need to replay the game.
  // Keeping clock and flag checks off the replay path is what stops the
  // single-threaded Durable Object from stalling live sockets and the lobby.
  private activeColor(match: StoredMatch): Color {
    return match.moves.length % 2 === 0 ? "w" : "b";
  }

  private currentClocks(match: StoredMatch, now = Date.now()): Record<Color, number> {
    const clocks = { ...match.clocks };
    if (!match.setup.timeSec || match.result || !match.startedAt || match.runningSince === null) return clocks;
    const active = this.activeColor(match);
    let elapsed = now - match.runningSince;
    // Start-of-game grace: the first move of each side gets 10 free seconds.
    if (this.movesByColor(match, active) === 0) {
      elapsed = Math.max(0, elapsed - firstMoveGraceMs);
    }
    clocks[active] = Math.max(0, clocks[active] - elapsed);
    return clocks;
  }

  private async finishOnFlag(match: StoredMatch, now = Date.now(), schedule = true): Promise<boolean> {
    if (!match.startedAt || match.result || !match.setup.timeSec) return false;
    const clocks = this.currentClocks(match, now);
    const active = this.activeColor(match);
    if (clocks[active] > 0) return false;

    match.clocks = clocks;
    match.runningSince = null;
    match.result = {
      winner: active === "w" ? "b" : "w",
      reason: active === "w" ? "white ran out of time" : "black ran out of time",
    };
    match.completedAt = now;
    await this.endMatch(match, schedule);
    return true;
  }

  // Single exit point for a finished match: persist it to D1 (updating both
  // ratings when the game was rated), then notify players and spectators.
  private async endMatch(match: StoredMatch, schedule = true) {
    if (!match.result) return;
    if (!match.completedAt) match.completedAt = Date.now();

    let ratings: { w: RatingChange | null; b: RatingChange | null } | null = null;
    if (!match.recorded && match.startedAt) {
      match.recorded = true;
      const db = await this.db();
      if (db) {
        try {
          const recorded = await recordFinishedGame(db, {
            id: match.id,
            whiteUserId: match.users?.w?.id ?? null,
            blackUserId: match.users?.b?.id ?? null,
            whiteName: match.users?.w?.name ?? "Anonymous",
            blackName: match.users?.b?.name ?? "Anonymous",
            whiteNerfId: match.setup.whiteNerfId,
            blackNerfId: match.setup.blackNerfId,
            seed: match.setup.seed,
            timeSec: match.setup.timeSec,
            incrementSec: match.setup.incrementSec,
            moves: match.moves,
            winner: match.result.winner,
            reason: match.result.reason,
            rated: !!match.rated,
            startedAt: match.startedAt,
            completedAt: match.completedAt,
          });
          if (recorded.white || recorded.black) {
            ratings = { w: recorded.white, b: recorded.black };
          }
        } catch (err) {
          console.error("failed to record game", match.id, err);
        }
      }
    }
    await this.saveMatch(match, schedule);

    const clocks = this.currentClocks(match);
    // Draft games also close with the public draft record: each side's held
    // buffs (public all game anyway, repeated here for post-game screens).
    let draftBuffs: Record<Color, { id: string; tier: number; spent?: boolean; nullified?: boolean }[]> | null = null;
    if (match.draft) {
      try {
        const game = this.gameFromMatch(match);
        if (game?.buffs) {
          const held = (color: Color) =>
            game.buffs!.players[color].buffs.map((b) => ({
              id: b.id,
              tier: b.tier as number,
              ...(b.spent ? { spent: true } : {}),
              ...(b.nullified ? { nullified: true } : {}),
            }));
          draftBuffs = { w: held("w"), b: held("b") };
        }
      } catch {
        // The end frame must go out even if the draft replay hiccups.
      }
    }
    // Both secret rules become public at game end — players and spectators
    // all receive them with the result.
    const payload = {
      result: match.result,
      wc: Math.round(clocks.w),
      bc: Math.round(clocks.b),
      nerfs: { w: match.setup.whiteNerfId, b: match.setup.blackNerfId },
      ...(ratings ? { ratings } : {}),
      ...(draftBuffs ? { draftBuffs } : {}),
    };
    this.broadcast(match, "end", payload);
    this.sendWatchers(match, "end", payload);
  }

  private async createMatch(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    if (session.matchId) return error(ws, "already_joined", "This connection already belongs to a game.");

    const requested = (data || {}) as { timeSec?: unknown; incrementSec?: unknown; draft?: unknown; picksVisible?: unknown; invite?: unknown };
    const timeSec = Number.isInteger(requested.timeSec) ? Number(requested.timeSec) : 600;
    const incrementSec = Number.isInteger(requested.incrementSec) ? Number(requested.incrementSec) : 0;
    if (timeSec < 0 || timeSec > 7200 || incrementSec < 0 || incrementSec > 60) {
      return error(ws, "invalid_clock", "Unsupported time control.");
    }
    // Optional Draft ruleset for friend games. Draft matches are always
    // casual: `rated` is deliberately never set here, whatever the client
    // asks, so a draft game can never touch ratings.
    const draft = requested.draft === true;
    const picksVisible = draft && requested.picksVisible === true;
    // Direct challenge: reserve the black seat for the named player. Only a
    // signed-in host can address a challenge (the API notification requires
    // an account anyway).
    const invite =
      session.userId && typeof requested.invite === "string" ? requested.invite.trim().slice(0, 30) : "";

    const id = await this.newCode();
    const match: StoredMatch = {
      id,
      setup: {
        ...pickNerfIds(),
        seed: makeSeed(),
        timeSec,
        incrementSec,
      },
      tokens: { w: newToken(), b: newToken() },
      disconnectedAt: {},
      opponentGoneNotified: {},
      moves: [],
      result: null,
      clocks: { w: timeSec * 1000, b: timeSec * 1000 },
      runningSince: null,
      drawOfferBy: null,
      createdAt: Date.now(),
      startedAt: null,
      completedAt: null,
      ...(draft ? { draft: true, picksVisible, draftSeed: makeSeed(), draftActions: [] } : {}),
      ...(invite ? { invitedUsername: invite } : {}),
    };

    await this.attachSession(ws, match, "w");
    await this.saveMatch(match);
    send(ws, "created", { id, color: "w", token: match.tokens.w });
  }

  private async joinMatch(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    if (session.matchId) return error(ws, "already_joined", "This connection already belongs to a game.");

    const id = String((data as { id?: unknown } | undefined)?.id || "").trim().toUpperCase();
    const match = await this.loadMatch(id);
    // A dealt nerf draft means both seats are claimed even though the game
    // has not started, so the code is no longer joinable.
    if (!match || match.startedAt || match.nerfOptions || this.connectedSession(id, "b")) {
      return error(ws, "not_found", "That code is not accepting a player.");
    }
    // Direct challenges are reserved: only the invited account may take the
    // black seat, so a lobby stranger can never race the invitee to it.
    if (
      match.invitedUsername &&
      match.invitedUsername.toLowerCase() !== (session.username ?? "").toLowerCase()
    ) {
      return error(ws, "invite_only", "This game is reserved for the invited player.");
    }
    // The host is gone (navigated away or closed the tab): joining would
    // start a game against an empty seat. Tell the joiner plainly instead.
    if (!this.connectedSession(id, "w")) {
      return error(ws, "host_gone", "The player who created this game has left.");
    }

    await this.attachSession(ws, match, "b");
    // Draft games open with the nerf draft instead of starting outright.
    if (match.draft) return this.beginNerfDraft(match);
    match.startedAt = Date.now();
    match.runningSince = match.startedAt;
    await this.saveMatch(match);
    this.sendStart(match, "w");
    this.sendStart(match, "b");
  }

  private async reconnectMatch(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    if (session.matchId) return error(ws, "already_joined", "This connection already belongs to a game.");

    const request = (data || {}) as { id?: unknown; color?: unknown; token?: unknown };
    const id = String(request.id || "").trim().toUpperCase();
    const color = isColor(request.color) ? request.color : null;
    const token = typeof request.token === "string" ? request.token : "";
    const match = await this.loadMatch(id);
    if (!match || !color || match.tokens[color] !== token) {
      return error(ws, "reconnect_failed", "Could not resume that game.");
    }

    await this.attachSession(ws, match, color);
    await this.saveMatch(match);
    if (!match.startedAt) {
      // Mid nerf draft: resume it. The start payload restores this seat's
      // options and pick state (a seat that already picked sees the waiting
      // state again).
      if (match.nerfOptions) return this.sendStart(match, color);
      // Matchmade and rematch games begin the moment both paired players
      // arrive at the game URL; friend games wait in the lobby for a join.
      if (
        (match.rated || match.autoStart) &&
        this.connectedSession(match.id, "w") &&
        this.connectedSession(match.id, "b")
      ) {
        if (match.draft) return this.beginNerfDraft(match);
        match.startedAt = Date.now();
        match.runningSince = match.startedAt;
        await this.saveMatch(match);
        this.sendStart(match, "w");
        this.sendStart(match, "b");
        return;
      }
      return send(ws, "created", { id, color, token: match.tokens[color] });
    }
    this.sendStart(match, color);
    // A rematch was created while this seat was away (page refresh or dropped
    // socket mid-rematch): re-deliver the seat in the new game so the player
    // reclaims it instead of arriving at the rematch as a spectator. Only
    // while the rematch is still unfinished, so revisiting an old game page
    // never bounces into an already-decided one.
    if (match.rematchedTo) {
      const rematch = await this.loadMatch(match.rematchedTo);
      if (rematch && !rematch.result) {
        const newColor: Color = color === "w" ? "b" : "w";
        send(ws, "rematched", { id: rematch.id, color: newColor, token: rematch.tokens[newColor] });
      }
    }
  }

  private async playClientMove(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before sending moves.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return error(ws, "game_over", "This game is over.");
    // Draft games: no moves while the opening nerf draft is unresolved.
    if (match.draft && match.nerfOptions && !match.startedAt) {
      return error(ws, "nerf_pending", "Pick your nerf before the game starts.");
    }

    const game = this.gameFromMatch(match);
    if (!game) return error(ws, "no_game", "Join a game before sending moves.");
    if (game.board.turn !== session.color) return error(ws, "not_your_turn", "It is not your turn.");
    // Draft games: a pending buff offer blocks the seat's moves, mirroring
    // how the client blocks the board until the draft is resolved.
    if (match.draft && game.buffs?.players[session.color].offer) {
      return error(ws, "draft_pending", "Resolve your buff draft before moving.");
    }

    const request = (data || {}) as { u?: unknown; ply?: unknown };
    const uci = typeof request.u === "string" ? request.u.toLowerCase() : "";
    if (Number.isInteger(request.ply) && Number(request.ply) !== match.moves.length) {
      return error(ws, "stale_ply", "Your board is out of date.");
    }
    const move = moveByUci(game, uci);
    if (!move) return error(ws, "illegal_move", "That move is not legal in the current position.");

    const now = Date.now();
    match.clocks = this.currentClocks(match, now);
    if (match.drawOfferBy && match.drawOfferBy !== session.color) {
      const declinedBy = session.color;
      match.drawOfferBy = null;
      this.broadcast(match, "drawDeclined", { color: declinedBy });
    }
    // Moving past an opponent's takeback request declines it.
    if (match.takebackOfferBy && match.takebackOfferBy !== session.color) {
      match.takebackOfferBy = null;
      this.broadcast(match, "takebackDeclined", { color: session.color });
    }
    // Which seats already had a pending offer: playMove mutates the game, so
    // newly rolled offers are detected against this pre-move snapshot.
    const offersBefore =
      match.draft && game.buffs
        ? { w: !!game.buffs.players.w.offer, b: !!game.buffs.players.b.offer }
        : null;
    const nextGame = playMove(game, move);
    match.moves.push(uci);
    if (match.setup.timeSec) match.clocks[session.color] += match.setup.incrementSec * 1000;
    match.runningSince = nextGame.result ? null : now;
    match.result = nextGame.result;
    if (nextGame.result) match.completedAt = now;
    await this.saveMatch(match);

    const movePayload = {
      u: uci,
      ply: match.moves.length,
      wc: Math.round(match.clocks.w),
      bc: Math.round(match.clocks.b),
    };
    this.broadcast(match, "move", movePayload);
    this.sendWatchers(match, "move", movePayload);
    if (match.draft && nextGame.buffs) {
      // The shared draft cadence rolls offers for BOTH seats on the same
      // move, so each seat whose offer appeared gets its dtOffer frame now,
      // not just the mover's. dtOffer goes to the drafting seat only, plus
      // the opponent when the match was created with visible picks.
      // Spectators never see offers.
      let rolledAny = false;
      for (const color of ["w", "b"] as Color[]) {
        const rolled = nextGame.buffs.players[color].offer;
        if (!rolled || offersBefore?.[color]) continue;
        rolledAny = true;
        const offerPayload = {
          color,
          cards: rolled.cards,
          index: rolled.index,
          ...(rolled.banked ? { banked: true } : {}),
        };
        send(this.connectedSession(match.id, color), "dtOffer", offerPayload);
        if (match.picksVisible) {
          send(this.connectedSession(match.id, color === "w" ? "b" : "w"), "dtOffer", offerPayload);
        }
      }
      if (rolledAny) this.sendDraftState(match, nextGame);
    }
    if (match.result) await this.endMatch(match);
  }

  private async resignGame(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before resigning.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;

    const game = this.gameFromMatch(match);
    if (!game) return error(ws, "no_game", "Join a game before resigning.");

    match.clocks = this.currentClocks(match);
    match.runningSince = null;
    match.result = resign(game, session.color).result;
    match.completedAt = Date.now();
    await this.endMatch(match);
  }

  // ---------------- abandonment claims ----------------

  // Once the opponent has been disconnected for 30+ seconds in a started,
  // unfinished game, the remaining player may end it as a win or a draw.
  private async claimAbandonment(ws: WebSocket, draw: boolean) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before claiming.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;
    if (!match.startedAt) return error(ws, "not_started", "The game has not started yet.");

    const opponent: Color = session.color === "w" ? "b" : "w";
    const disconnectedAt = match.disconnectedAt[opponent];
    if (
      this.connectedSession(match.id, opponent) ||
      !disconnectedAt ||
      Date.now() - disconnectedAt < abandonmentClaimMs
    ) {
      return error(ws, "no_claim", "Your opponent has not been gone long enough to claim.");
    }

    match.clocks = this.currentClocks(match);
    match.runningSince = null;
    match.result = draw
      ? { winner: "draw", reason: "abandonment" }
      : { winner: session.color, reason: "abandonment" };
    match.completedAt = Date.now();
    await this.endMatch(match);
  }

  private async offerDraw(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before offering a draw.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;
    if (match.drawOfferBy === session.color) return error(ws, "draw_pending", "Your draw offer is already pending.");
    if (match.drawOfferBy && match.drawOfferBy !== session.color) return this.acceptDraw(ws);

    match.drawOfferBy = session.color;
    await this.saveMatch(match);
    this.broadcast(match, "drawOffer", { color: session.color });
  }

  private async acceptDraw(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before accepting a draw.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;
    if (!match.drawOfferBy || match.drawOfferBy === session.color) {
      return error(ws, "no_draw_offer", "There is no opponent draw offer to accept.");
    }

    match.clocks = this.currentClocks(match);
    match.runningSince = null;
    match.drawOfferBy = null;
    match.result = { winner: "draw", reason: "draw by agreement" };
    match.completedAt = Date.now();
    await this.endMatch(match);
  }

  private async declineDraw(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before declining a draw.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;
    if (!match.drawOfferBy || match.drawOfferBy === session.color) {
      return error(ws, "no_draw_offer", "There is no opponent draw offer to decline.");
    }

    match.drawOfferBy = null;
    await this.saveMatch(match);
    this.broadcast(match, "drawDeclined", { color: session.color });
  }

  // ---------------- takebacks (casual games only) ----------------

  // How many plies an accepted takeback removes: the offerer's last move,
  // plus the opponent's reply if they already answered it.
  private takebackPlies(match: StoredMatch, offerer: Color): number {
    const lastMover: Color = match.moves.length % 2 === 1 ? "w" : "b";
    return lastMover === offerer ? 1 : 2;
  }

  private async offerTakeback(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before requesting a takeback.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;
    if (match.rated) return error(ws, "takeback_rated", "Takebacks are not allowed in rated games.");
    // Draft state (rolled offers, consumed RNG, applied buffs) cannot be
    // rewound, so draft games have no takebacks.
    if (match.draft) return error(ws, "takeback_draft", "Takebacks are not available in Draft games.");
    const myMoves = session.color === "w" ? Math.ceil(match.moves.length / 2) : Math.floor(match.moves.length / 2);
    if (myMoves === 0) return error(ws, "no_moves", "You have no move to take back.");
    if (this.takebackPlies(match, session.color) > match.moves.length) {
      return error(ws, "no_moves", "You have no move to take back.");
    }
    if (match.takebackOfferBy === session.color) {
      return error(ws, "takeback_pending", "Your takeback request is already pending.");
    }
    if (match.takebackOfferBy && match.takebackOfferBy !== session.color) return this.acceptTakeback(ws);

    match.takebackOfferBy = session.color;
    await this.saveMatch(match);
    this.broadcast(match, "takebackOffer", { color: session.color });
  }

  private async acceptTakeback(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before accepting a takeback.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;
    const offerer = match.takebackOfferBy;
    if (!offerer || offerer === session.color) {
      return error(ws, "no_takeback_offer", "There is no takeback request to accept.");
    }

    const remove = this.takebackPlies(match, offerer);
    if (remove > match.moves.length) {
      match.takebackOfferBy = null;
      await this.saveMatch(match);
      return error(ws, "no_moves", "There is nothing to take back.");
    }

    const now = Date.now();
    match.clocks = this.currentClocks(match, now);
    match.moves = match.moves.slice(0, match.moves.length - remove);
    match.takebackOfferBy = null;
    match.runningSince = match.startedAt ? now : null;
    await this.saveMatch(match);

    const payload = {
      by: offerer,
      moves: match.moves,
      ply: match.moves.length,
      wc: Math.round(match.clocks.w),
      bc: Math.round(match.clocks.b),
    };
    this.broadcast(match, "takeback", payload);
    this.sendWatchers(match, "takeback", payload);
  }

  private async declineTakeback(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before declining a takeback.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;
    if (!match.takebackOfferBy || match.takebackOfferBy === session.color) {
      return error(ws, "no_takeback_offer", "There is no takeback request to decline.");
    }

    match.takebackOfferBy = null;
    await this.saveMatch(match);
    this.broadcast(match, "takebackDeclined", { color: session.color });
  }

  // ---------------- matchmaking queue ----------------

  private queueKey(pool: string): string {
    return `queue:${pool}`;
  }

  private async queueJoin(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    if (session.matchId) return error(ws, "already_joined", "This connection already belongs to a game.");
    if (!session.userId || !session.username) {
      return error(ws, "auth_required", "Sign in to play rated games.");
    }
    const req = (data as { pool?: unknown } | undefined) ?? {};
    const poolName = String(req.pool || "3+2");
    const pool = QUEUE_POOLS[poolName];
    if (!pool) return error(ws, "bad_pool", "Unknown queue pool.");
    const db = await this.db();
    if (!db) return error(ws, "server_unconfigured", "Matchmaking is unavailable right now.");

    let rating = 1500;
    let rd = 350;
    let vol = 0.06;
    let avatar: string | null = null;
    {
      // Queueing uses (and later updates) the rating bucket for this pool's
      // time control only.
      const row = await this.seatCategoryRating(
        db,
        session.userId,
        categoryForTimeControl(pool.timeSec, pool.incrementSec),
      );
      if (row) {
        rating = row.rating;
        rd = row.rd;
        vol = row.vol;
        avatar = row.avatar;
      }
    }

    const key = this.queueKey(poolName);
    let entries = (await this.ctx.storage.get<QueueEntry[]>(key)) ?? [];
    // Drop dead sockets and any previous entry by this same account.
    entries = entries.filter(
      (entry) => entry.userId !== session.userId && this.socketForAttachment(entry.attachmentId),
    );

    const opponent = entries.shift();
    if (!opponent) {
      entries.push({
        attachmentId: session.id,
        userId: session.userId,
        username: session.username,
        rating,
        rd,
        vol,
        avatar,
        at: Date.now(),
      });
      await this.ctx.storage.put(key, entries);
      return send(ws, "queued", { pool: poolName });
    }
    await this.ctx.storage.put(key, entries);

    const opponentWs = this.socketForAttachment(opponent.attachmentId)!;
    const meWhite = randomInt(2) === 0;
    const me: SeatUser = { id: session.userId, name: session.username, rating, rd, vol, avatar };
    const them: SeatUser = {
      id: opponent.userId,
      name: opponent.username,
      rating: opponent.rating,
      rd: opponent.rd,
      vol: opponent.vol,
      avatar: opponent.avatar ?? null,
    };
    const id = await this.newCode(8);
    const match: StoredMatch = {
      id,
      setup: {
        ...pickNerfIds(),
        seed: makeSeed(),
        timeSec: pool.timeSec,
        incrementSec: pool.incrementSec,
      },
      tokens: { w: newToken(), b: newToken() },
      disconnectedAt: {},
      opponentGoneNotified: {},
      moves: [],
      result: null,
      clocks: { w: pool.timeSec * 1000, b: pool.timeSec * 1000 },
      runningSince: null,
      drawOfferBy: null,
      createdAt: Date.now(),
      startedAt: null,
      completedAt: null,
      rated: true,
      autoStart: true,
      users: { w: meWhite ? me : them, b: meWhite ? them : me },
    };
    await this.saveMatch(match);

    // Both clients navigate to /game/{id} and take their seat via `reconnect`;
    // the game starts once both have arrived.
    const myColor: Color = meWhite ? "w" : "b";
    const theirColor: Color = meWhite ? "b" : "w";
    send(ws, "paired", { id, color: myColor, token: match.tokens[myColor], pool: poolName });
    send(opponentWs, "paired", { id, color: theirColor, token: match.tokens[theirColor], pool: poolName });
  }

  private async queueLeave(ws: WebSocket, notify: boolean) {
    const session = this.sessions.get(ws) ?? (ws.deserializeAttachment() as SessionAttachment | null);
    if (!session) return;
    for (const poolName of Object.keys(QUEUE_POOLS)) {
      const key = this.queueKey(poolName);
      const entries = (await this.ctx.storage.get<QueueEntry[]>(key)) ?? [];
      const next = entries.filter((entry) => entry.attachmentId !== session.id);
      if (next.length !== entries.length) await this.ctx.storage.put(key, next);
    }
    if (notify) send(ws, "queueCancelled");
  }

  // ---------------- rematch ----------------

  private async rematchRequest(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before requesting a rematch.");
    if (!match.result) return error(ws, "not_over", "The game is still in progress.");
    if (match.rematchedTo) return error(ws, "rematch_done", "A rematch has already started.");

    const opponentColor: Color = session.color === "w" ? "b" : "w";
    if (match.rematchOfferBy === session.color) return;
    if (match.rematchOfferBy !== opponentColor) {
      if (!this.connectedSession(match.id, opponentColor)) {
        return error(ws, "opponent_gone", "Your opponent has left.");
      }
      match.rematchOfferBy = session.color;
      await this.saveMatch(match, false);
      this.broadcast(match, "rematchOffer", { color: session.color });
      return;
    }

    // Both agreed: new game with colors swapped, fresh rules and seed.
    const users: StoredMatch["users"] = {};
    if (match.users?.b) users.w = { ...match.users.b };
    if (match.users?.w) users.b = { ...match.users.w };
    const db = await this.db();
    if (db) {
      for (const color of ["w", "b"] as Color[]) {
        const seat = users[color];
        if (!seat) continue;
        const row = await this.seatCategoryRating(
          db,
          seat.id,
          categoryForTimeControl(match.setup.timeSec, match.setup.incrementSec),
        );
        if (row) {
          seat.rating = row.rating;
          seat.rd = row.rd;
          seat.vol = row.vol;
          seat.avatar = row.avatar;
        }
      }
    }

    const id = await this.newCode(match.rated ? 8 : 5);
    const rematch: StoredMatch = {
      id,
      setup: {
        ...pickNerfIds(),
        seed: makeSeed(),
        timeSec: match.setup.timeSec,
        incrementSec: match.setup.incrementSec,
      },
      tokens: { w: newToken(), b: newToken() },
      disconnectedAt: {},
      opponentGoneNotified: {},
      moves: [],
      result: null,
      clocks: { w: match.setup.timeSec * 1000, b: match.setup.timeSec * 1000 },
      runningSince: null,
      drawOfferBy: null,
      createdAt: Date.now(),
      startedAt: null,
      completedAt: null,
      rated: match.rated,
      autoStart: true,
      users,
      ...(match.draft
        ? { draft: true, picksVisible: !!match.picksVisible, draftSeed: makeSeed(), draftActions: [] }
        : {}),
    };
    await this.saveMatch(rematch);
    match.rematchOfferBy = null;
    match.rematchedTo = id;
    await this.saveMatch(match, false);

    send(this.connectedSession(match.id, "w"), "rematched", { id, color: "b", token: rematch.tokens.b });
    send(this.connectedSession(match.id, "b"), "rematched", { id, color: "w", token: rematch.tokens.w });
  }

  // ---------------- chat ----------------

  // Per-socket chat throttle; in-memory only, so at worst a hibernation wake
  // resets the window.
  private lastChatAt = new Map<string, number>();

  private async chatMessage(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before chatting.");
    const raw = String((data as { text?: unknown } | undefined)?.text ?? "").trim();
    if (!raw) return;
    const now = Date.now();
    if (now - (this.lastChatAt.get(session.id) ?? 0) < 500) return;
    this.lastChatAt.set(session.id, now);

    const name = match.users?.[session.color]?.name ?? (session.color === "w" ? "White" : "Black");
    const clipped = raw.slice(0, 200);
    // Shadow-mute (Lichess-style): a chat-muted player sees their own message
    // echoed back, but it is neither stored nor shown to anyone else.
    if (session.mutedUntil && session.mutedUntil > Date.now()) {
      send(ws, "chat", { color: session.color, name, text: clipped, at: now } satisfies ChatEntry);
      return;
    }
    // Censor profanity before it is stored or relayed, and keep the original
    // in chat_flags so a moderator can review repeat offenders later.
    const matched = findProfanity(clipped);
    const text = matched.length ? censorText(clipped) : clipped;
    if (matched.length) {
      const db = await this.db();
      if (db) {
        try {
          await db
            .prepare(
              `INSERT INTO chat_flags (id, match_id, user_id, username, color, text, matched_words, created_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
            )
            .bind(crypto.randomUUID(), match.id, session.userId ?? null, name, session.color, clipped, matched.join(","), now)
            .run();
        } catch (err) {
          console.error("failed to record chat flag", match.id, err);
        }
      }
    }
    const entry: ChatEntry = { color: session.color, name, text, at: now };
    match.chat = [...(match.chat ?? []), entry].slice(-50);
    await this.saveMatch(match, false);
    this.broadcast(match, "chat", entry);
  }

  // Chat between spectators. Relayed only to sockets watching the same game,
  // so the players can't read it (no coaching from the rail).
  private async spectatorChatMessage(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    const match = session.watching ? await this.loadMatch(session.watching) : null;
    if (!match) return error(ws, "not_watching", "Watch a game before chatting.");
    const raw = String((data as { text?: unknown } | undefined)?.text ?? "").trim();
    if (!raw) return;
    const now = Date.now();
    if (now - (this.lastChatAt.get(session.id) ?? 0) < 500) return;
    this.lastChatAt.set(session.id, now);

    const name = session.username ?? "Anonymous";
    const clipped = raw.slice(0, 200);
    // Shadow-mute works here too: the muted watcher sees only their own echo.
    if (session.mutedUntil && session.mutedUntil > Date.now()) {
      send(ws, "schat", { name, text: clipped, at: now } satisfies SpectatorChatEntry);
      return;
    }
    const matched = findProfanity(clipped);
    const text = matched.length ? censorText(clipped) : clipped;
    if (matched.length) {
      const db = await this.db();
      if (db) {
        try {
          await db
            .prepare(
              `INSERT INTO chat_flags (id, match_id, user_id, username, color, text, matched_words, created_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
            )
            .bind(crypto.randomUUID(), match.id, session.userId ?? null, name, "s", clipped, matched.join(","), now)
            .run();
        } catch (err) {
          console.error("failed to record chat flag", match.id, err);
        }
      }
    }
    const entry: SpectatorChatEntry = { name, text, at: now };
    match.spectatorChat = [...(match.spectatorChat ?? []), entry].slice(-50);
    await this.saveMatch(match, false);
    this.sendWatchers(match, "schat", entry);
  }

  // ---------------- voluntary rule reveal ----------------

  // A player may show their secret rule to the table mid-game. Irreversible;
  // the opponent and all spectators learn it immediately, and reconnects
  // replay it via the start payload.
  private async revealRule(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before revealing your rule.");
    if (!match.startedAt) return error(ws, "not_started", "The game has not started yet.");
    if (match.revealed?.[session.color]) return;

    match.revealed = { ...(match.revealed ?? {}), [session.color]: true };
    await this.saveMatch(match, false);
    const nerfId = session.color === "w" ? match.setup.whiteNerfId : match.setup.blackNerfId;
    const payload = { color: session.color, nerfId };
    this.broadcast(match, "reveal", payload);
    this.sendWatchers(match, "reveal", payload);
  }

  // ---------------- draft mode (buff drafts) ----------------

  // The single place that decides what each receiver may see of the draft
  // state. Visibility rules:
  // - Held (already drafted) buffs, board effects, tempo counters, and the
  //   draft counters are public: both seats and spectators get them.
  // - A pending offer's cards are visible to the offer's own seat, plus the
  //   opposing seat when the match was created with picksVisible. Without
  //   picksVisible the opposing seat only learns that an offer is pending.
  // - Draft flags and the one-shot oppReveal snapshot are per-seat secrets;
  //   the opposing seat gets flags only under picksVisible, never the reveal.
  // - Spectators get none of the hidden data: no offers, no pending markers,
  //   no flags, no reveals, regardless of settings.
  // - The draft RNG state is never serialized for anyone: it would let a
  //   client predict every future offer.
  private draftStateFor(game: NerfGame, match: StoredMatch, seat: Color | "spectator") {
    const bs = game.buffs;
    if (!bs) return null;
    const playerState = (color: Color) => {
      const ps = bs.players[color];
      const self = seat === color;
      const open = self || (seat !== "spectator" && !!match.picksVisible);
      return {
        buffs: ps.buffs,
        draftsTaken: ps.draftsTaken,
        nextDraftAt: ps.nextDraftAt,
        offer: open ? ps.offer : null,
        ...(seat !== "spectator" && !open && ps.offer ? { offerPending: true } : {}),
        ...(open ? { flags: ps.flags } : {}),
        ...(self ? { oppReveal: ps.oppReveal ?? null } : {}),
        ...(ps.nerfRemoved ? { nerfRemoved: true } : {}),
        revived: ps.revived,
      };
    };
    return {
      cadence: bs.cadence,
      effects: bs.effects,
      extraMoves: bs.extraMoves,
      skips: bs.skips,
      ...(bs.chainKingGuard ? { chainKingGuard: bs.chainKingGuard } : {}),
      ...(bs.historyDiverged ? { historyDiverged: true } : {}),
      players: { w: playerState("w"), b: playerState("b") },
    };
  }

  private sendDraftState(match: StoredMatch, game: NerfGame) {
    for (const color of ["w", "b"] as Color[]) {
      const seatWs = this.connectedSession(match.id, color);
      if (!seatWs) continue;
      const state = this.draftStateFor(game, match, color);
      if (state) send(seatWs, "dtState", { state });
    }
  }

  // The public draft record everyone may replay: picked cards are public the
  // moment they are held, a bank only reveals that it happened, and buff
  // activations carry their targets (the effects are on the board anyway).
  // The pick's offer slot index stays private with the rest of the offer.
  private publicDraftActions(match: StoredMatch) {
    return (match.draftActions ?? []).map((action) =>
      action.a === "pick"
        ? { ply: action.ply, color: action.color, a: "pick" as const, cards: action.cards }
        : action,
    );
  }

  // Shared validation for the draft frames: a seated, live, started draft
  // match rebuilt through the engine.
  private async draftContext(
    ws: WebSocket,
  ): Promise<{ session: SessionAttachment; match: StoredMatch; game: NerfGame } | null> {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) {
      error(ws, "no_game", "Join a game before drafting.");
      return null;
    }
    if (!match.draft) {
      error(ws, "not_draft", "This game is not a Draft game.");
      return null;
    }
    if (await this.finishOnFlag(match)) return null;
    if (match.result) {
      error(ws, "game_over", "This game is over.");
      return null;
    }
    // Buff frames wait for the opening nerf draft like moves do.
    if (match.nerfOptions && !match.startedAt) {
      error(ws, "nerf_pending", "Pick your nerf before the game starts.");
      return null;
    }
    const game = this.gameFromMatch(match);
    if (!game?.buffs) {
      error(ws, "no_game", "The game has not started yet.");
      return null;
    }
    return { session, match, game };
  }

  // Persist a resolved draft action, tell everyone the public outcome, and
  // re-sync both seats' filtered state. Instant and activated buffs can end
  // the game on the spot (a removal or freeze can decide it), so the end
  // flow runs here too.
  private async settleDraftAction(
    match: StoredMatch,
    game: NerfGame,
    resolved: { color: Color; kind: "picked" | "banked"; cards?: { id: string; tier: number }[] } | null,
    used?: { color: Color; buffIndex: number; picks: BuffPick[] },
  ) {
    if (game.result && !match.result) {
      const now = Date.now();
      match.clocks = this.currentClocks(match, now);
      match.runningSince = null;
      match.result = game.result;
      match.completedAt = now;
    }
    await this.saveMatch(match);
    if (resolved) {
      this.broadcast(match, "dtResolved", resolved);
      this.sendWatchers(match, "dtResolved", resolved);
    }
    if (used) {
      this.broadcast(match, "dtUsed", used);
      this.sendWatchers(match, "dtUsed", used);
    }
    this.sendDraftState(match, game);
    if (match.result) await this.endMatch(match);
  }

  private async draftPick(ws: WebSocket, data: unknown) {
    const ctx = await this.draftContext(ws);
    if (!ctx) return;
    const { session, match, game } = ctx;
    const color = session.color!;
    const ps = game.buffs!.players[color];
    const offer = ps.offer;
    if (!offer) return error(ws, "no_offer", "You have no pending buff draft.");
    const request = (data || {}) as { index?: unknown };
    const index = Number(request.index);
    if (!Number.isInteger(index) || !offer.cards[index]) {
      return error(ws, "bad_pick", "That card is not part of your offer.");
    }
    const before = ps.buffs.length;
    pickDraftCard(game, color, index);
    // Everything acquired by this pick (take-both drafts can grab several
    // cards) becomes public the moment it is held.
    const cards = ps.buffs.slice(before).map((b) => ({ id: b.id, tier: b.tier as number }));
    match.draftActions = [
      ...(match.draftActions ?? []),
      { ply: match.moves.length, color, a: "pick", index, cards },
    ];
    await this.settleDraftAction(match, game, { color, kind: "picked", cards });
  }

  private async draftBank(ws: WebSocket) {
    const ctx = await this.draftContext(ws);
    if (!ctx) return;
    const { session, match, game } = ctx;
    const color = session.color!;
    if (!game.buffs!.players[color].offer) {
      return error(ws, "no_offer", "You have no pending buff draft.");
    }
    bankDraft(game, color);
    match.draftActions = [...(match.draftActions ?? []), { ply: match.moves.length, color, a: "bank" }];
    await this.settleDraftAction(match, game, { color, kind: "banked" });
  }

  private async draftUse(ws: WebSocket, data: unknown) {
    const ctx = await this.draftContext(ws);
    if (!ctx) return;
    const { session, match, game } = ctx;
    const color = session.color!;
    const ps = game.buffs!.players[color];
    if (ps.offer) return error(ws, "draft_pending", "Resolve your buff draft first.");
    if (game.board.turn !== color) return error(ws, "not_your_turn", "Buffs activate on your turn.");
    const request = (data || {}) as { buffIndex?: unknown; picks?: unknown };
    const buffIndex = Number(request.buffIndex);
    if (!Number.isInteger(buffIndex) || !ps.buffs[buffIndex]) {
      return error(ws, "bad_buff", "You do not hold that buff.");
    }
    const picks = this.parseBuffPicks(request.picks);
    if (!picks || !this.buffPicksComplete(game, color, buffIndex, picks)) {
      return error(ws, "bad_target", "Those targets are not valid for that buff.");
    }
    if (!activateBuff(game, color, buffIndex, picks)) {
      return error(ws, "bad_buff", "That buff cannot be used right now.");
    }
    match.draftActions = [
      ...(match.draftActions ?? []),
      { ply: match.moves.length, color, a: "use", buffIndex, picks },
    ];
    await this.settleDraftAction(match, game, null, { color, buffIndex, picks });
  }

  private async draftTarget(ws: WebSocket, data: unknown) {
    const ctx = await this.draftContext(ws);
    if (!ctx) return;
    const { session, game } = ctx;
    const color = session.color!;
    const request = (data || {}) as { buffIndex?: unknown; picks?: unknown };
    const buffIndex = Number(request.buffIndex);
    if (!Number.isInteger(buffIndex) || !game.buffs!.players[color].buffs[buffIndex]) {
      return error(ws, "bad_buff", "You do not hold that buff.");
    }
    const picks = this.parseBuffPicks(request.picks);
    const collected = picks ? this.walkBuffPicks(game, color, buffIndex, picks) : null;
    if (!collected) return error(ws, "bad_target", "Those targets are not valid for that buff.");
    send(ws, "dtTargetReq", { buffIndex, target: buffNextTarget(game, color, buffIndex, collected) });
  }

  // ---------------- draft mode (opening nerf draft) ----------------

  // Deal the opening nerf draft for a Draft match. Difficulty is matched the
  // same way pickNerfPair matches classic games: each seat's two options
  // share a tier, and the two seats' tiers sit within one of each other. All
  // four cards are distinct. The deal comes from the match seed RNG so a
  // Durable Object restart re-deals the same options (never Math.random).
  private dealNerfDraftOptions(match: StoredMatch): Record<Color, string[]> {
    const master = new RNG(match.setup.seed);
    master.fork(); // skip: white's nerf seed, already derived in startPayload
    master.fork(); // skip: black's nerf seed
    const rng = master.fork();

    const pool = PLAYABLE_NERFS.filter((nerf) => nerf.id !== "lucky");
    const ofTier = (tier: number, exclude: ReadonlySet<string>) =>
      pool.filter((nerf) => nerf.tier === tier && !exclude.has(nerf.id));
    const takeTwo = (tier: number, exclude: ReadonlySet<string>): string[] => {
      const candidates = ofTier(tier, exclude);
      const first = candidates.splice(rng.int(candidates.length), 1)[0];
      const second = candidates[rng.int(candidates.length)];
      return [first.id, second.id];
    };
    const none = new Set<string>();
    const tiers = [...new Set(pool.map((nerf) => nerf.tier))];
    // A tier can anchor the deal if it holds two cards and a tier within one
    // of it still holds two once the anchor's cards are gone.
    const anchorTiers = tiers.filter((anchor) => {
      if (ofTier(anchor, none).length < 2) return false;
      return tiers.some(
        (partner) =>
          Math.abs(partner - anchor) <= 1 &&
          ofTier(partner, none).length >= (partner === anchor ? 4 : 2),
      );
    });
    const anchorTier = anchorTiers[rng.int(anchorTiers.length)];
    const anchorCards = takeTwo(anchorTier, none);
    const taken = new Set(anchorCards);
    const partnerTiers = tiers.filter(
      (partner) => Math.abs(partner - anchorTier) <= 1 && ofTier(partner, taken).length >= 2,
    );
    const partnerCards = takeTwo(partnerTiers[rng.int(partnerTiers.length)], taken);
    // Like pickNerfPair, randomize which color holds the anchor so tier-edge
    // deals do not always land on the same side.
    return rng.int(2) === 0 ? { w: anchorCards, b: partnerCards } : { w: partnerCards, b: anchorCards };
  }

  // Both seats of a Draft match are present: deal the opening nerf draft
  // instead of starting the game. The match stays un-started (clocks off,
  // moves and buff frames rejected with nerf_pending) until both picks land.
  private async beginNerfDraft(match: StoredMatch) {
    if (!match.nerfOptions) match.nerfOptions = this.dealNerfDraftOptions(match);
    await this.saveMatch(match);
    this.sendStart(match, "w");
    this.sendStart(match, "b");
  }

  private async nerfDraftPick(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before drafting.");
    if (!match.draft) return error(ws, "not_draft", "This game is not a Draft game.");
    if (match.result) return error(ws, "game_over", "This game is over.");
    if (!match.nerfOptions || match.startedAt) {
      return error(ws, "no_nerf_draft", "There is no nerf draft to pick from.");
    }
    const color = session.color;
    if (match.nerfPicks?.[color] != null) {
      return error(ws, "already_picked", "You already picked your nerf.");
    }
    // Index-only validation: clients choose between the two server-dealt
    // options and can never smuggle in a nerf id of their own.
    const index = Number((data as { index?: unknown } | undefined)?.index);
    if (index !== 0 && index !== 1) {
      return error(ws, "bad_pick", "That card is not part of your options.");
    }

    match.nerfPicks = { ...(match.nerfPicks ?? {}), [color]: index };
    const opp: Color = color === "w" ? "b" : "w";
    const oppPick = match.nerfPicks[opp];
    if (oppPick == null) {
      await this.saveMatch(match);
      // Progress only: both seats learn that this side picked, never which
      // card. Spectators learn nothing.
      this.broadcast(match, "dtNerfPicked", { color });
      return;
    }

    // Both picks are in: lock the chosen rules and start the game proper.
    // Clocks only begin now, so neither side paid for choosing.
    match.setup.whiteNerfId = match.nerfOptions.w[match.nerfPicks.w!];
    match.setup.blackNerfId = match.nerfOptions.b[match.nerfPicks.b!];
    // Visible-picks matches: both chosen rules are open from move one,
    // through the same reveal channel voluntary reveals use.
    if (match.picksVisible) match.revealed = { w: true, b: true };
    match.startedAt = Date.now();
    match.runningSince = match.startedAt;
    await this.saveMatch(match);
    this.sendStart(match, "w");
    this.sendStart(match, "b");
  }

  private parseBuffPicks(raw: unknown): BuffPick[] | null {
    if (raw === undefined) return [];
    if (!Array.isArray(raw) || raw.length > 8) return null;
    const picks: BuffPick[] = [];
    for (const entry of raw) {
      const pick = (entry || {}) as { square?: unknown; buffIndex?: unknown };
      const next: BuffPick = {};
      if (Number.isInteger(pick.square)) next.square = Number(pick.square);
      if (Number.isInteger(pick.buffIndex)) next.buffIndex = Number(pick.buffIndex);
      if (next.square === undefined && next.buffIndex === undefined) return null;
      picks.push(next);
    }
    return picks;
  }

  // Walk the buff's own target chain: every pick must be one of the engine's
  // offered candidates. This keeps a client from smuggling arbitrary squares
  // or buff indexes into an effect.
  private walkBuffPicks(game: NerfGame, color: Color, buffIndex: number, picks: BuffPick[]): BuffPick[] | null {
    const collected: BuffPick[] = [];
    for (const pick of picks) {
      const target = buffNextTarget(game, color, buffIndex, collected);
      if (!target) return null;
      if (target.kind === "square") {
        if (pick.square === undefined || !target.squares.includes(pick.square)) return null;
        collected.push({ square: pick.square });
      } else {
        if (pick.buffIndex === undefined || !target.options.some((option) => option.index === pick.buffIndex)) {
          return null;
        }
        collected.push({ buffIndex: pick.buffIndex });
      }
    }
    return collected;
  }

  private buffPicksComplete(game: NerfGame, color: Color, buffIndex: number, picks: BuffPick[]): boolean {
    const collected = this.walkBuffPicks(game, color, buffIndex, picks);
    if (!collected) return false;
    return buffNextTarget(game, color, buffIndex, collected) === null;
  }

  // ---------------- spectating & lobby ----------------

  private async watchMatch(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    if (session.matchId) return error(ws, "already_joined", "This connection already belongs to a game.");
    const id = String((data as { id?: unknown } | undefined)?.id || "").trim().toUpperCase();
    const match = await this.loadMatch(id);
    if (!match) return error(ws, "not_found", "No live game with that id.");
    await this.finishOnFlag(match);

    const next = { ...session, watching: id };
    this.sessions.set(ws, next);
    ws.serializeAttachment(next);

    const clocks = this.currentClocks(match);
    // Spectator-safe draft payload: the public action record and a filtered
    // state carrying held buffs and board effects only, never offers.
    let draftExtras: Record<string, unknown> | null = null;
    if (match.draft) {
      const game = match.startedAt ? this.gameFromMatch(match) : null;
      draftExtras = {
        draft: true,
        dtActions: this.publicDraftActions(match),
        ...(game?.buffs ? { dtState: this.draftStateFor(game, match, "spectator") } : {}),
      };
    }
    send(ws, "wstart", {
      id,
      timeSec: match.setup.timeSec,
      incrementSec: match.setup.incrementSec,
      wc: Math.round(clocks.w),
      bc: Math.round(clocks.b),
      moves: match.moves,
      players: this.playersPayload(match),
      rated: !!match.rated,
      started: !!match.startedAt,
      result: match.result,
      watchers: this.watcherCount(id),
      watcherNames: this.watcherInfo(id).names,
      spectatorChat: match.spectatorChat ?? [],
      // Hidden rules are only revealed to spectators once the game is over.
      ...(match.result ? { nerfs: { w: match.setup.whiteNerfId, b: match.setup.blackNerfId } } : {}),
      ...(draftExtras ?? {}),
    });
    this.broadcastWatchers(id);
  }

  private watchLeave(ws: WebSocket) {
    const session = this.session(ws);
    if (!session.watching) return;
    const id = session.watching;
    const next = { ...session };
    delete next.watching;
    this.sessions.set(ws, next);
    ws.serializeAttachment(next);
    this.broadcastWatchers(id);
  }

  // One snapshot for the lobby page: who is online right now and which games
  // can be watched. Polled by the client every few seconds.
  private async lobbySnapshot(ws: WebSocket) {
    const matches = [...(await this.ctx.storage.list<StoredMatch>({ prefix: "match:" })).values()];
    const now = Date.now();

    const liveGames: Array<{
      id: string;
      players: ReturnType<GameServer["playersPayload"]>;
      rated: boolean;
      draft: boolean;
      timeSec: number;
      incrementSec: number;
      moves: number;
      watchers: number;
    }> = [];
    const playingUserIds = new Set<string>();
    // Friend games waiting for an opponent, shown in the lobby as open
    // challenges anyone can accept. Matchmade (autoStart) games waiting for
    // their paired players to arrive are not challenges.
    const challenges: Array<{
      id: string;
      host: { name: string; rating: number | null };
      draft: boolean;
      timeSec: number;
      incrementSec: number;
      createdAt: number;
    }> = [];
    for (const match of matches) {
      // A dealt nerf draft means both seats are taken: not a challenge.
      if (!match.startedAt && !match.result && !match.autoStart && !match.nerfOptions) {
        // Only list codes whose host is still connected; otherwise the code
        // is a dead end for whoever clicks it. Direct challenges are reserved
        // for their invitee and never appear as open challenges.
        if (!match.invitedUsername && this.connectedSession(match.id, "w")) {
          const host = match.users?.w;
          challenges.push({
            id: match.id,
            host: host ? { name: host.name, rating: Math.round(host.rating) } : { name: "Anonymous", rating: null },
            draft: !!match.draft,
            timeSec: match.setup.timeSec,
            incrementSec: match.setup.incrementSec,
            createdAt: match.createdAt,
          });
        }
        continue;
      }
      if (!match.startedAt || match.result) continue;
      await this.finishOnFlag(match, now, false);
      if (match.result) continue;
      for (const color of ["w", "b"] as Color[]) {
        const id = match.users?.[color]?.id;
        if (id) playingUserIds.add(id);
      }
      liveGames.push({
        id: match.id,
        players: this.playersPayload(match),
        rated: !!match.rated,
        draft: !!match.draft,
        timeSec: match.setup.timeSec,
        incrementSec: match.setup.incrementSec,
        moves: match.moves.length,
        watchers: this.watcherCount(match.id),
      });
    }
    liveGames.sort((a, b) => b.watchers - a.watchers || b.moves - a.moves);
    challenges.sort((a, b) => b.createdAt - a.createdAt);

    // Who is queued for quick pairing right now. Each connected entry is also
    // surfaced as a joinable seek, so a player browsing the lobby can see and
    // answer someone waiting in a different pool instead of both idling.
    const queuedUserIds = new Set<string>();
    const seeks: Array<{
      pool: string;
      name: string;
      rating: number | null;
      timeSec: number;
      incrementSec: number;
      at: number;
    }> = [];
    for (const [poolName, pool] of Object.entries(QUEUE_POOLS)) {
      const entries = (await this.ctx.storage.get<QueueEntry[]>(this.queueKey(poolName))) ?? [];
      for (const entry of entries) {
        if (!this.socketForAttachment(entry.attachmentId)) continue;
        queuedUserIds.add(entry.userId);
        seeks.push({
          pool: poolName,
          name: entry.username,
          rating: Math.round(entry.rating),
          timeSec: pool.timeSec,
          incrementSec: pool.incrementSec,
          at: entry.at,
        });
      }
    }
    seeks.sort((a, b) => a.at - b.at);

    // Every signed-in account with an open socket, deduped; anonymous sockets
    // are only counted.
    const seen = new Map<string, { name: string; rating: number | null; status: string; avatar: string | null }>();
    let anonymous = 0;
    for (const [socket, session] of this.sessions) {
      if (socket.readyState !== WebSocket.OPEN) continue;
      if (!session.userId || !session.username) {
        anonymous++;
        continue;
      }
      const status = playingUserIds.has(session.userId)
        ? "playing"
        : queuedUserIds.has(session.userId)
        ? "searching"
        : "online";
      const existing = seen.get(session.userId);
      // "playing" wins over "searching" wins over "online" across tabs.
      if (!existing || existing.status === "online" || (existing.status === "searching" && status === "playing")) {
        seen.set(session.userId, { name: session.username, rating: null, status, avatar: null });
      }
    }

    // Attach ratings for the online list in one query.
    const db = await this.db();
    if (db && seen.size > 0) {
      try {
        const ids = [...seen.keys()];
        const placeholders = ids.map(() => "?").join(",");
        const rows = await db
          .prepare(`SELECT id, username, rating, avatar FROM users WHERE id IN (${placeholders})`)
          .bind(...ids)
          .all<{ id: string; username: string; rating: number; avatar: string | null }>();
        for (const row of rows.results) {
          const entry = seen.get(row.id);
          if (entry) {
            entry.rating = Math.round(row.rating);
            entry.avatar = row.avatar;
          }
        }
      } catch {}
    }

    const players = [...seen.values()]
      .sort((a, b) => (b.rating ?? 0) - (a.rating ?? 0))
      .slice(0, 50);
    send(ws, "lobby", {
      players,
      anonymous,
      games: liveGames.slice(0, 25),
      challenges: challenges.slice(0, 25),
      seeks: seeks.slice(0, 25),
    });
  }

  private async sendClocks(ws: WebSocket) {
    const session = this.session(ws);
    const watchedId = session.matchId ?? session.watching;
    const match = watchedId ? await this.loadMatch(watchedId) : null;
    if (!match) return send(ws, "n");
    if (await this.finishOnFlag(match)) return;
    const clocks = this.currentClocks(match);
    send(ws, "n", { wc: Math.round(clocks.w), bc: Math.round(clocks.b) });
  }

  private candidateAlarm(match: StoredMatch, now = Date.now()): number | null {
    const candidates: number[] = [];
    if (match.setup.timeSec && match.startedAt && !match.result && match.runningSince !== null) {
      const active = this.activeColor(match);
      const grace = this.movesByColor(match, active) === 0 ? firstMoveGraceMs : 0;
      candidates.push(match.runningSince + match.clocks[active] + grace);
    }
    for (const color of ["w", "b"] as Color[]) {
      const disconnectedAt = match.disconnectedAt[color];
      if (disconnectedAt && !match.opponentGoneNotified[color]) candidates.push(disconnectedAt + disconnectGraceMs);
    }
    const expiry = match.completedAt ?? match.createdAt;
    if (match.completedAt) candidates.push(expiry + 60 * 60 * 1000);
    else if (!match.startedAt) candidates.push(expiry + 30 * 60 * 1000);
    else if (this.connectedSessions(match.id).length === 0) {
      const latestDisconnect = Math.max(match.disconnectedAt.w ?? 0, match.disconnectedAt.b ?? 0);
      if (latestDisconnect) candidates.push(latestDisconnect + 30 * 60 * 1000);
    }

    const next = Math.min(...candidates.filter((candidate) => candidate > now));
    return Number.isFinite(next) ? next : null;
  }

  private async scheduleAlarmForMatch(match: StoredMatch) {
    const next = this.candidateAlarm(match);
    if (!next) return;
    const existing = await this.ctx.storage.getAlarm();
    if (!existing || next < existing) await this.ctx.storage.setAlarm(next);
  }

  private async scheduleNextAlarm(matches: StoredMatch[]) {
    const now = Date.now();
    const next = Math.min(...matches.map((match) => this.candidateAlarm(match) ?? Number.POSITIVE_INFINITY));
    // No pending deadline means no alarm: the Durable Object goes idle until
    // the next socket/save re-arms it via scheduleAlarmForMatch.
    if (!Number.isFinite(next)) return;
    await this.ctx.storage.setAlarm(Math.max(next, now + 250));
  }

  private async cleanupExpired() {
    const matches = [...(await this.ctx.storage.list<StoredMatch>({ prefix: "match:" })).values()];
    const now = Date.now();
    for (const match of matches) {
      if (match.completedAt && now - match.completedAt > 60 * 60 * 1000) await this.deleteMatch(match);
      else if (!match.startedAt && now - match.createdAt > 30 * 60 * 1000) await this.deleteMatch(match);
    }
  }

  private async maintenanceAll() {
    const matches = [...(await this.ctx.storage.list<StoredMatch>({ prefix: "match:" })).values()];
    const now = Date.now();
    const remaining: StoredMatch[] = [];

    for (const match of matches) {
      // One bad match (corrupt record, transient storage error) must not stop
      // flag enforcement for every other live game or break the alarm chain.
      try {
        let changed = await this.finishOnFlag(match, now, false);
        for (const color of ["w", "b"] as Color[]) {
          const disconnectedAt = match.disconnectedAt[color];
          const opponent = this.connectedSession(match.id, color === "w" ? "b" : "w");
          if (disconnectedAt && opponent && !match.opponentGoneNotified[color] && now - disconnectedAt > disconnectGraceMs) {
            send(opponent, "opponentGone");
            match.opponentGoneNotified[color] = true;
            changed = true;
          }
        }

        const bothDisconnected = this.connectedSessions(match.id).length === 0;
        const latestDisconnect = Math.max(match.disconnectedAt.w ?? 0, match.disconnectedAt.b ?? 0);
        if (
          (match.completedAt && now - match.completedAt > 60 * 60 * 1000) ||
          (!match.startedAt && now - match.createdAt > 30 * 60 * 1000) ||
          (match.startedAt && bothDisconnected && latestDisconnect && now - latestDisconnect > 30 * 60 * 1000)
        ) {
          await this.deleteMatch(match);
          continue;
        }

        if (changed) await this.saveMatch(match, false);
      } catch (err) {
        console.error("maintenance failed for match", match.id, err);
      }
      remaining.push(match);
    }

    await this.scheduleNextAlarm(remaining);
  }
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (url.pathname === socketPath || url.pathname === "/healthz") {
      try {
        const id = env.GAME_SERVER.idFromName(globalServerName);
        return await env.GAME_SERVER.get(id).fetch(request);
      } catch (err) {
        // The game server threw. Without this the platform returns an opaque
        // 1101 page with no detail. Surface the actual error on /healthz so it
        // can be read from a browser (there is no other log access here), and
        // fail the socket upgrade cleanly instead of crashing the request.
        const message = err instanceof Error ? `${err.name}: ${err.message}` : String(err);
        const stack = err instanceof Error ? err.stack : undefined;
        console.error("game server fetch threw", err);
        if (url.pathname === "/healthz") {
          return Response.json({ ok: false, version: buildVersion, error: message, stack }, { status: 200 });
        }
        return new Response("game server unavailable", { status: 503 });
      }
    }
    return handler.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<Env>;

// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
