/// <reference types="@cloudflare/workers-types" />

import { DurableObject } from "cloudflare:workers";
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import { default as handler } from "./.open-next/worker.js";
import { moveToUCI } from "./src/engine/board";
import { PLAYABLE_NERFS } from "./src/engine/nerfs/library";
import { NerfGame, legalMoves, newGame, playMove, resign } from "./src/engine/game";
import { RNG } from "./src/engine/rng";
import { Color } from "./src/engine/types";

type Result = NerfGame["result"];
type Setup = {
  whiteNerfId: string;
  blackNerfId: string;
  seed: number;
  timeSec: number;
  incrementSec: number;
};
type StoredMatch = {
  id: string;
  setup: Setup;
  tokens: Record<Color, string>;
  disconnectedAt: Partial<Record<Color, number>>;
  opponentGoneNotified: Partial<Record<Color, boolean>>;
  moves: string[];
  result: Result;
  clocks: Record<Color, number>;
  runningSince: number | null;
  drawOfferBy: Color | null;
  rematchOfferBy?: Color | null;
  createdAt: number;
  startedAt: number | null;
  completedAt: number | null;
};
type SessionAttachment = {
  id: string;
  matchId?: string;
  color?: Color;
  token?: string;
};
type ClientFrame =
  | { t: "create"; d?: { timeSec?: unknown; incrementSec?: unknown } }
  | { t: "join"; d?: { id?: unknown } }
  | { t: "reconnect"; d?: { id?: unknown; color?: unknown; token?: unknown } }
  | { t: "move"; d?: { u?: unknown; ply?: unknown } }
  | { t: "resign" }
  | { t: "drawOffer" }
  | { t: "drawAccept" }
  | { t: "drawDecline" }
  | { t: "rematch" }
  | { t: "rematchDecline" }
  | { t: "p" };

export interface Env {
  GAME_SERVER: DurableObjectNamespace<GameServer>;
  GAME_SERVER_ORIGINS?: string;
}

const socketPath = "/socket/v1";
const globalServerName = "nerfchess-global";
const disconnectGraceMs = 15 * 1000;

function randomInt(max: number): number {
  const values = new Uint32Array(1);
  crypto.getRandomValues(values);
  return values[0] % max;
}

function randomCode(): string {
  const chars = "BCDFGHJKMNPQRSTVWXYZ23456789";
  let code = "";
  for (let i = 0; i < 5; i++) code += chars[randomInt(chars.length)];
  return code;
}

function newToken(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

function makeSeed(): number {
  return randomInt(2 ** 31);
}

function pickNerfId(): string {
  const pool = PLAYABLE_NERFS.filter((nerf) => nerf.id !== "lucky");
  return pool[randomInt(pool.length)].id;
}

function isColor(value: unknown): value is Color {
  return value === "w" || value === "b";
}

function matchKey(id: string): string {
  return `match:${id}`;
}

function send(ws: WebSocket | undefined, t: string, d?: unknown) {
  if (!ws || ws.readyState !== WebSocket.OPEN) return;
  ws.send(JSON.stringify(d === undefined ? { t } : { t, d }));
}

function error(ws: WebSocket, code: string, message: string) {
  send(ws, "error", { code, message });
}

function moveByUci(game: NerfGame, uci: string) {
  return legalMoves(game).find((candidate) => moveToUCI(candidate) === uci);
}

export class GameServer extends DurableObject<Env> {
  private sessions = new Map<WebSocket, SessionAttachment>();

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    for (const ws of this.ctx.getWebSockets()) {
      const attachment = ws.deserializeAttachment() as SessionAttachment | null;
      if (attachment) this.sessions.set(ws, attachment);
    }
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/healthz") {
      await this.cleanupExpired();
      const matches = await this.ctx.storage.list<StoredMatch>({ prefix: "match:" });
      return Response.json({ ok: true, games: matches.size, sockets: this.sessions.size });
    }

    if (url.pathname !== socketPath) return new Response("Not found", { status: 404 });
    if (request.headers.get("Upgrade") !== "websocket") {
      return new Response("Expected WebSocket", { status: 426 });
    }
    if (!this.originAllowed(request)) {
      return new Response("Forbidden", { status: 403 });
    }

    const pair = new WebSocketPair();
    const [client, server] = Object.values(pair);
    const attachment = { id: crypto.randomUUID() };
    server.serializeAttachment(attachment);
    this.sessions.set(server, attachment);
    this.ctx.acceptWebSocket(server);

    return new Response(null, { status: 101, webSocket: client });
  }

  async webSocketMessage(ws: WebSocket, message: ArrayBuffer | string) {
    let frame: ClientFrame;
    try {
      frame = JSON.parse(typeof message === "string" ? message : new TextDecoder().decode(message)) as ClientFrame;
    } catch {
      return error(ws, "bad_json", "Messages must be JSON objects.");
    }

    switch (frame.t) {
      case "create":
        return this.createMatch(ws, frame.d);
      case "join":
        return this.joinMatch(ws, frame.d);
      case "reconnect":
        return this.reconnectMatch(ws, frame.d);
      case "move":
        return this.playClientMove(ws, frame.d);
      case "resign":
        return this.resignGame(ws);
      case "drawOffer":
        return this.offerDraw(ws);
      case "drawAccept":
        return this.acceptDraw(ws);
      case "drawDecline":
        return this.declineDraw(ws);
      case "rematch":
        return this.offerRematch(ws);
      case "rematchDecline":
        return this.declineRematch(ws);
      case "p":
        return this.sendClocks(ws);
      default:
        return error(ws, "unknown_message", "Unknown message type.");
    }
  }

  async webSocketClose(ws: WebSocket) {
    await this.detachSession(ws);
  }

  async webSocketError(ws: WebSocket) {
    await this.detachSession(ws);
  }

  async alarm() {
    await this.maintenanceAll();
  }

  private originAllowed(request: Request): boolean {
    const origin = request.headers.get("Origin");
    const configured = (this.env.GAME_SERVER_ORIGINS || "")
      .split(",")
      .map((allowed) => allowed.trim())
      .filter(Boolean);

    // Explicit allowlist: only the configured origins may connect.
    if (configured.length > 0) {
      return !!origin && configured.includes(origin);
    }

    // No allowlist configured: fail closed to same-origin only. Requests
    // without an Origin header (non-browser clients, which cannot be targets
    // of browser CSRF) are still permitted; cross-origin browser requests are
    // rejected instead of being allowed unconditionally.
    if (!origin) return true;
    try {
      return new URL(origin).host === new URL(request.url).host;
    } catch {
      return false;
    }
  }

  private async loadMatch(id: string): Promise<StoredMatch | null> {
    return (await this.ctx.storage.get<StoredMatch>(matchKey(id))) ?? null;
  }

  private async saveMatch(match: StoredMatch, schedule = true) {
    await this.ctx.storage.put(matchKey(match.id), match);
    if (schedule) await this.scheduleAlarmForMatch(match);
  }

  private async deleteMatch(match: StoredMatch) {
    for (const [ws, session] of this.sessions) {
      if (session.matchId === match.id) {
        this.sessions.delete(ws);
        ws.close(1000, "Game expired");
      }
    }
    await this.ctx.storage.delete(matchKey(match.id));
  }

  private connectedSession(matchId: string, color: Color): WebSocket | undefined {
    for (const [ws, session] of this.sessions) {
      if (session.matchId === matchId && session.color === color && ws.readyState === WebSocket.OPEN) return ws;
    }
    return undefined;
  }

  private connectedSessions(matchId: string): WebSocket[] {
    return [...this.sessions]
      .filter(([ws, session]) => session.matchId === matchId && ws.readyState === WebSocket.OPEN)
      .map(([ws]) => ws);
  }

  private session(ws: WebSocket): SessionAttachment {
    const restored = ws.deserializeAttachment() as SessionAttachment | null;
    const session = this.sessions.get(ws) ?? restored;
    if (!session) {
      const next = { id: crypto.randomUUID() };
      this.sessions.set(ws, next);
      ws.serializeAttachment(next);
      return next;
    }
    this.sessions.set(ws, session);
    return session;
  }

  private async attachSession(ws: WebSocket, match: StoredMatch, color: Color) {
    const existing = this.connectedSession(match.id, color);
    if (existing && existing !== ws) existing.close(1000, "Reconnected from another tab");

    const session = { ...this.session(ws), matchId: match.id, color, token: match.tokens[color] };
    this.sessions.set(ws, session);
    ws.serializeAttachment(session);
    delete match.disconnectedAt[color];
    delete match.opponentGoneNotified[color];
  }

  private async detachSession(ws: WebSocket) {
    const session = this.sessions.get(ws) ?? (ws.deserializeAttachment() as SessionAttachment | null);
    this.sessions.delete(ws);
    if (!session?.matchId || !session.color) return;
    if (this.connectedSession(session.matchId, session.color)) return;

    const match = await this.loadMatch(session.matchId);
    if (!match) return;
    match.disconnectedAt[session.color] = Date.now();
    match.opponentGoneNotified[session.color] = false;
    await this.saveMatch(match);
  }

  private async newCode(): Promise<string> {
    let code = randomCode();
    while (await this.loadMatch(code)) code = randomCode();
    return code;
  }

  private startPayload(match: StoredMatch, color: Color) {
    const clocks = this.currentClocks(match);
    const myNerfId = color === "w" ? match.setup.whiteNerfId : match.setup.blackNerfId;
    const masterRng = new RNG(match.setup.seed);
    const wSeed = masterRng.fork().getState();
    const bSeed = masterRng.fork().getState();
    const nerfSeed = color === "w" ? wSeed : bSeed;
    return {
      id: match.id,
      color,
      token: match.tokens[color],
      nerfId: myNerfId,
      nerfSeed,
      timeSec: match.setup.timeSec,
      incrementSec: match.setup.incrementSec,
      wc: Math.round(clocks.w),
      bc: Math.round(clocks.b),
      moves: match.moves,
    };
  }

  // Once a game is over both secret rules are public: every "end" frame
  // carries the nerf ids so each client can reveal the opponent's rule.
  private endPayload(match: StoredMatch) {
    const clocks = this.currentClocks(match);
    return {
      result: match.result,
      wc: Math.round(clocks.w),
      bc: Math.round(clocks.b),
      nerfs: { w: match.setup.whiteNerfId, b: match.setup.blackNerfId },
    };
  }

  private sendStart(match: StoredMatch, color: Color) {
    const ws = this.connectedSession(match.id, color);
    send(ws, "start", this.startPayload(match, color));
    if (match.result) {
      send(ws, "end", this.endPayload(match));
    }
  }

  private broadcast(match: StoredMatch, t: string, d?: unknown) {
    send(this.connectedSession(match.id, "w"), t, d);
    send(this.connectedSession(match.id, "b"), t, d);
  }

  private gameFromMatch(match: StoredMatch): NerfGame | null {
    if (!match.startedAt) return null;
    const white = PLAYABLE_NERFS.find((nerf) => nerf.id === match.setup.whiteNerfId);
    const black = PLAYABLE_NERFS.find((nerf) => nerf.id === match.setup.blackNerfId);
    if (!white || !black) return null;

    let game = newGame(white, black, match.setup.seed);
    for (const uci of match.moves) {
      const move = moveByUci(game, uci);
      if (!move) return null;
      game = playMove(game, move);
    }
    if (match.result) game.result = match.result;
    return game;
  }

  private currentClocks(match: StoredMatch, now = Date.now()): Record<Color, number> {
    const clocks = { ...match.clocks };
    const game = this.gameFromMatch(match);
    if (!match.setup.timeSec || !game || game.result || match.runningSince === null) return clocks;
    const active = game.board.turn;
    clocks[active] = Math.max(0, clocks[active] - (now - match.runningSince));
    return clocks;
  }

  private async finishOnFlag(match: StoredMatch, now = Date.now(), schedule = true): Promise<boolean> {
    const game = this.gameFromMatch(match);
    if (!game || game.result || !match.setup.timeSec) return false;
    const clocks = this.currentClocks(match, now);
    const active = game.board.turn;
    if (clocks[active] > 0) return false;

    match.clocks = clocks;
    match.runningSince = null;
    match.result = {
      winner: active === "w" ? "b" : "w",
      reason: active === "w" ? "white ran out of time" : "black ran out of time",
    };
    match.completedAt = now;
    await this.saveMatch(match, schedule);
    this.broadcast(match, "end", this.endPayload(match));
    return true;
  }

  private async createMatch(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    if (session.matchId) return error(ws, "already_joined", "This connection already belongs to a game.");

    const requested = (data || {}) as { timeSec?: unknown; incrementSec?: unknown };
    const timeSec = Number.isInteger(requested.timeSec) ? Number(requested.timeSec) : 600;
    const incrementSec = Number.isInteger(requested.incrementSec) ? Number(requested.incrementSec) : 0;
    if (timeSec < 0 || timeSec > 7200 || incrementSec < 0 || incrementSec > 60) {
      return error(ws, "invalid_clock", "Unsupported time control.");
    }

    const id = await this.newCode();
    const match: StoredMatch = {
      id,
      setup: {
        whiteNerfId: pickNerfId(),
        blackNerfId: pickNerfId(),
        seed: makeSeed(),
        timeSec,
        incrementSec,
      },
      tokens: { w: newToken(), b: newToken() },
      disconnectedAt: {},
      opponentGoneNotified: {},
      moves: [],
      result: null,
      clocks: { w: timeSec * 1000, b: timeSec * 1000 },
      runningSince: null,
      drawOfferBy: null,
      rematchOfferBy: null,
      createdAt: Date.now(),
      startedAt: null,
      completedAt: null,
    };

    await this.attachSession(ws, match, "w");
    await this.saveMatch(match);
    send(ws, "created", { id, color: "w", token: match.tokens.w });
  }

  private async joinMatch(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    if (session.matchId) return error(ws, "already_joined", "This connection already belongs to a game.");

    const id = String((data as { id?: unknown } | undefined)?.id || "").trim().toUpperCase();
    const match = await this.loadMatch(id);
    if (!match || match.startedAt || this.connectedSession(id, "b")) {
      return error(ws, "not_found", "That code is not accepting a player.");
    }

    await this.attachSession(ws, match, "b");
    match.startedAt = Date.now();
    match.runningSince = match.startedAt;
    await this.saveMatch(match);
    this.sendStart(match, "w");
    this.sendStart(match, "b");
  }

  private async reconnectMatch(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    if (session.matchId) return error(ws, "already_joined", "This connection already belongs to a game.");

    const request = (data || {}) as { id?: unknown; color?: unknown; token?: unknown };
    const id = String(request.id || "").trim().toUpperCase();
    const color = isColor(request.color) ? request.color : null;
    const token = typeof request.token === "string" ? request.token : "";
    const match = await this.loadMatch(id);
    if (!match || !color || match.tokens[color] !== token) {
      return error(ws, "reconnect_failed", "Could not resume that game.");
    }

    await this.attachSession(ws, match, color);
    await this.saveMatch(match);
    if (!match.startedAt) return send(ws, "created", { id, color, token: match.tokens[color] });
    this.sendStart(match, color);
  }

  private async playClientMove(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before sending moves.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return error(ws, "game_over", "This game is over.");

    const game = this.gameFromMatch(match);
    if (!game) return error(ws, "no_game", "Join a game before sending moves.");
    if (game.board.turn !== session.color) return error(ws, "not_your_turn", "It is not your turn.");

    const request = (data || {}) as { u?: unknown; ply?: unknown };
    const uci = typeof request.u === "string" ? request.u.toLowerCase() : "";
    if (Number.isInteger(request.ply) && Number(request.ply) !== match.moves.length) {
      return error(ws, "stale_ply", "Your board is out of date.");
    }
    const move = moveByUci(game, uci);
    if (!move) return error(ws, "illegal_move", "That move is not legal in the current position.");

    const now = Date.now();
    match.clocks = this.currentClocks(match, now);
    if (match.drawOfferBy && match.drawOfferBy !== session.color) {
      const declinedBy = session.color;
      match.drawOfferBy = null;
      this.broadcast(match, "drawDeclined", { color: declinedBy });
    }
    const nextGame = playMove(game, move);
    match.moves.push(uci);
    if (match.setup.timeSec) match.clocks[session.color] += match.setup.incrementSec * 1000;
    match.runningSince = nextGame.result ? null : now;
    match.result = nextGame.result;
    if (nextGame.result) match.completedAt = now;
    await this.saveMatch(match);

    this.broadcast(match, "move", {
      u: uci,
      ply: match.moves.length,
      wc: Math.round(match.clocks.w),
      bc: Math.round(match.clocks.b),
    });
    if (match.result) {
      this.broadcast(match, "end", this.endPayload(match));
    }
  }

  private async resignGame(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before resigning.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;

    const game = this.gameFromMatch(match);
    if (!game) return error(ws, "no_game", "Join a game before resigning.");

    match.clocks = this.currentClocks(match);
    match.runningSince = null;
    match.result = resign(game, session.color).result;
    match.completedAt = Date.now();
    await this.saveMatch(match);

    this.broadcast(match, "end", this.endPayload(match));
  }

  private async offerDraw(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before offering a draw.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;
    if (match.drawOfferBy === session.color) return error(ws, "draw_pending", "Your draw offer is already pending.");
    if (match.drawOfferBy && match.drawOfferBy !== session.color) return this.acceptDraw(ws);

    match.drawOfferBy = session.color;
    await this.saveMatch(match);
    this.broadcast(match, "drawOffer", { color: session.color });
  }

  private async acceptDraw(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before accepting a draw.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;
    if (!match.drawOfferBy || match.drawOfferBy === session.color) {
      return error(ws, "no_draw_offer", "There is no opponent draw offer to accept.");
    }

    match.clocks = this.currentClocks(match);
    match.runningSince = null;
    match.drawOfferBy = null;
    match.result = { winner: "draw", reason: "draw by agreement" };
    match.completedAt = Date.now();
    await this.saveMatch(match);

    this.broadcast(match, "end", this.endPayload(match));
  }

  // A rematch offer once the game is over. A second offer from the other
  // player counts as acceptance and starts the new game immediately.
  private async offerRematch(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before offering a rematch.");
    if (!match.result) return error(ws, "game_live", "The game is still in progress.");
    if (match.rematchOfferBy === session.color) {
      return error(ws, "rematch_pending", "Your rematch offer is already pending.");
    }
    if (match.rematchOfferBy && match.rematchOfferBy !== session.color) return this.startRematch(match);
    match.rematchOfferBy = session.color;
    await this.saveMatch(match);
    this.broadcast(match, "rematchOffer", { color: session.color });
  }

  private async declineRematch(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before declining a rematch.");
    if (!match.rematchOfferBy || match.rematchOfferBy === session.color) {
      return error(ws, "no_rematch_offer", "There is no opponent rematch offer to decline.");
    }
    match.rematchOfferBy = null;
    await this.saveMatch(match);
    this.broadcast(match, "rematchDeclined", { color: session.color });
  }

  // Reset the match in place: fresh nerfs and seed, colors swapped for
  // fairness, clocks back to the original time control. Each player keeps
  // their token; the fresh "start" frame hands them their new color.
  private async startRematch(match: StoredMatch) {
    match.tokens = { w: match.tokens.b, b: match.tokens.w };
    for (const [sock, sess] of this.sessions) {
      if (sess.matchId !== match.id || !sess.color) continue;
      const color: Color = sess.color === "w" ? "b" : "w";
      const next = { ...sess, color, token: match.tokens[color] };
      this.sessions.set(sock, next);
      sock.serializeAttachment(next);
    }

    match.setup = {
      ...match.setup,
      whiteNerfId: pickNerfId(),
      blackNerfId: pickNerfId(),
      seed: makeSeed(),
    };
    match.moves = [];
    match.result = null;
    match.clocks = { w: match.setup.timeSec * 1000, b: match.setup.timeSec * 1000 };
    match.startedAt = Date.now();
    match.runningSince = match.startedAt;
    match.drawOfferBy = null;
    match.rematchOfferBy = null;
    match.completedAt = null;
    await this.saveMatch(match);
    this.sendStart(match, "w");
    this.sendStart(match, "b");
  }

  private async declineDraw(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before declining a draw.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;
    if (!match.drawOfferBy || match.drawOfferBy === session.color) {
      return error(ws, "no_draw_offer", "There is no opponent draw offer to decline.");
    }

    match.drawOfferBy = null;
    await this.saveMatch(match);
    this.broadcast(match, "drawDeclined", { color: session.color });
  }

  private async sendClocks(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match) return send(ws, "n");
    if (await this.finishOnFlag(match)) return;
    const clocks = this.currentClocks(match);
    send(ws, "n", { wc: Math.round(clocks.w), bc: Math.round(clocks.b) });
  }

  private candidateAlarm(match: StoredMatch, now = Date.now()): number | null {
    const candidates: number[] = [];
    const game = this.gameFromMatch(match);
    if (match.setup.timeSec && game && !game.result && match.runningSince !== null) {
      candidates.push(match.runningSince + match.clocks[game.board.turn]);
    }
    for (const color of ["w", "b"] as Color[]) {
      const disconnectedAt = match.disconnectedAt[color];
      if (disconnectedAt && !match.opponentGoneNotified[color]) candidates.push(disconnectedAt + disconnectGraceMs);
    }

    const expiry = match.completedAt ?? match.createdAt;
    if (match.completedAt) candidates.push(expiry + 60 * 60 * 1000);
    else if (!match.startedAt) candidates.push(expiry + 30 * 60 * 1000);
    else if (this.connectedSessions(match.id).length === 0) {
      const latestDisconnect = Math.max(match.disconnectedAt.w ?? 0, match.disconnectedAt.b ?? 0);
      if (latestDisconnect) candidates.push(latestDisconnect + 30 * 60 * 1000);
    }

    const next = Math.min(...candidates.filter((candidate) => candidate > now));
    return Number.isFinite(next) ? next : null;
  }

  private async scheduleAlarmForMatch(match: StoredMatch) {
    const next = this.candidateAlarm(match);
    if (!next) return;
    const existing = await this.ctx.storage.getAlarm();
    if (!existing || next < existing) await this.ctx.storage.setAlarm(next);
  }

  private async scheduleNextAlarm(matches: StoredMatch[]) {
    const next = Math.min(...matches.map((match) => this.candidateAlarm(match) ?? Number.POSITIVE_INFINITY));
    if (Number.isFinite(next)) await this.ctx.storage.setAlarm(next);
    else await this.ctx.storage.deleteAlarm();
  }

  private async cleanupExpired() {
    const matches = [...(await this.ctx.storage.list<StoredMatch>({ prefix: "match:" })).values()];
    const now = Date.now();
    for (const match of matches) {
      if (match.completedAt && now - match.completedAt > 60 * 60 * 1000) await this.deleteMatch(match);
      else if (!match.startedAt && now - match.createdAt > 30 * 60 * 1000) await this.deleteMatch(match);
    }
  }

  private async maintenanceAll() {
    const matches = [...(await this.ctx.storage.list<StoredMatch>({ prefix: "match:" })).values()];
    const now = Date.now();
    const remaining: StoredMatch[] = [];

    for (const match of matches) {
      let changed = await this.finishOnFlag(match, now, false);
      for (const color of ["w", "b"] as Color[]) {
        const disconnectedAt = match.disconnectedAt[color];
        const opponent = this.connectedSession(match.id, color === "w" ? "b" : "w");
        if (disconnectedAt && opponent && !match.opponentGoneNotified[color] && now - disconnectedAt > disconnectGraceMs) {
          send(opponent, "opponentGone");
          match.opponentGoneNotified[color] = true;
          changed = true;
        }
      }

      const bothDisconnected = this.connectedSessions(match.id).length === 0;
      const latestDisconnect = Math.max(match.disconnectedAt.w ?? 0, match.disconnectedAt.b ?? 0);
      if (
        (match.completedAt && now - match.completedAt > 60 * 60 * 1000) ||
        (!match.startedAt && now - match.createdAt > 30 * 60 * 1000) ||
        (match.startedAt && bothDisconnected && latestDisconnect && now - latestDisconnect > 30 * 60 * 1000)
      ) {
        await this.deleteMatch(match);
        continue;
      }

      if (changed) await this.saveMatch(match, false);
      remaining.push(match);
    }

    await this.scheduleNextAlarm(remaining);
  }
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (url.pathname === socketPath || url.pathname === "/healthz") {
      const id = env.GAME_SERVER.idFromName(globalServerName);
      return env.GAME_SERVER.get(id).fetch(request);
    }
    return handler.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<Env>;

// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
