/// <reference types="@cloudflare/workers-types" />

import { DurableObject } from "cloudflare:workers";
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import { default as handler } from "./.open-next/worker.js";
import { moveToUCI } from "./src/engine/board";
import { PLAYABLE_NERFS } from "./src/engine/nerfs/library";
import { NerfGame, legalMoves, newGame, playMove, resign } from "./src/engine/game";
import { RNG } from "./src/engine/rng";
import { Color } from "./src/engine/types";
import { sessionTokenFromCookieHeader, userForSession } from "./src/lib/server/auth";
import { ensureSchema } from "./src/lib/server/schema";
import { recordFinishedGame, RatingChange } from "./src/lib/server/games";

type Result = NerfGame["result"];
type Setup = {
  whiteNerfId: string;
  blackNerfId: string;
  seed: number;
  timeSec: number;
  incrementSec: number;
};
type SeatUser = { id: string; name: string; rating: number };
type StoredMatch = {
  id: string;
  setup: Setup;
  tokens: Record<Color, string>;
  disconnectedAt: Partial<Record<Color, number>>;
  opponentGoneNotified: Partial<Record<Color, boolean>>;
  moves: string[];
  result: Result;
  clocks: Record<Color, number>;
  runningSince: number | null;
  drawOfferBy: Color | null;
  createdAt: number;
  startedAt: number | null;
  completedAt: number | null;
  // Rated matchmade games carry the two accounts; friend games may carry them
  // too (for history) but stay casual.
  rated?: boolean;
  users?: Partial<Record<Color, SeatUser>>;
  recorded?: boolean;
};
type SessionAttachment = {
  id: string;
  matchId?: string;
  color?: Color;
  token?: string;
  // Account attached at websocket upgrade from the session cookie.
  userId?: string;
  username?: string;
  // Match id this socket spectates (mutually exclusive with a seat).
  watching?: string;
};
type QueueEntry = {
  attachmentId: string;
  userId: string;
  username: string;
  rating: number;
  at: number;
};
type ClientFrame =
  | { t: "create"; d?: { timeSec?: unknown; incrementSec?: unknown } }
  | { t: "join"; d?: { id?: unknown } }
  | { t: "reconnect"; d?: { id?: unknown; color?: unknown; token?: unknown } }
  | { t: "move"; d?: { u?: unknown; ply?: unknown } }
  | { t: "resign" }
  | { t: "drawOffer" }
  | { t: "drawAccept" }
  | { t: "drawDecline" }
  | { t: "queue"; d?: { pool?: unknown } }
  | { t: "queueCancel" }
  | { t: "watch"; d?: { id?: unknown } }
  | { t: "p" };

export interface Env {
  GAME_SERVER: DurableObjectNamespace<GameServer>;
  GAME_SERVER_ORIGINS?: string;
  DB: D1Database;
}

// Quick-pairing pools for rated matchmaking.
const QUEUE_POOLS: Record<string, { timeSec: number; incrementSec: number }> = {
  "3+2": { timeSec: 180, incrementSec: 2 },
};

const socketPath = "/socket/v1";
const globalServerName = "nerfchess-global";
const disconnectGraceMs = 15 * 1000;

function randomInt(max: number): number {
  const values = new Uint32Array(1);
  crypto.getRandomValues(values);
  return values[0] % max;
}

function randomCode(length = 5): string {
  const chars = "BCDFGHJKMNPQRSTVWXYZ23456789";
  let code = "";
  for (let i = 0; i < length; i++) code += chars[randomInt(chars.length)];
  return code;
}

function newToken(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

function makeSeed(): number {
  return randomInt(2 ** 31);
}

function pickNerfId(): string {
  const pool = PLAYABLE_NERFS.filter((nerf) => nerf.id !== "lucky");
  return pool[randomInt(pool.length)].id;
}

function isColor(value: unknown): value is Color {
  return value === "w" || value === "b";
}

function matchKey(id: string): string {
  return `match:${id}`;
}

function send(ws: WebSocket | undefined, t: string, d?: unknown) {
  if (!ws || ws.readyState !== WebSocket.OPEN) return;
  ws.send(JSON.stringify(d === undefined ? { t } : { t, d }));
}

function error(ws: WebSocket, code: string, message: string) {
  send(ws, "error", { code, message });
}

function moveByUci(game: NerfGame, uci: string) {
  return legalMoves(game).find((candidate) => moveToUCI(candidate) === uci);
}

export class GameServer extends DurableObject<Env> {
  private sessions = new Map<WebSocket, SessionAttachment>();
  private dbReady: Promise<boolean> | null = null;

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    for (const ws of this.ctx.getWebSockets()) {
      const attachment = ws.deserializeAttachment() as SessionAttachment | null;
      if (attachment) this.sessions.set(ws, attachment);
    }
  }

  // Resolves to true when D1 is configured and its schema is in place.
  // Account features degrade to anonymous play when it isn't.
  private async db(): Promise<D1Database | null> {
    if (!this.env.DB) return null;
    if (!this.dbReady) {
      this.dbReady = ensureSchema(this.env.DB).then(
        () => true,
        () => false,
      );
    }
    return (await this.dbReady) ? this.env.DB : null;
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/healthz") {
      await this.cleanupExpired();
      const matches = await this.ctx.storage.list<StoredMatch>({ prefix: "match:" });
      return Response.json({ ok: true, games: matches.size, sockets: this.sessions.size });
    }

    if (url.pathname !== socketPath) return new Response("Not found", { status: 404 });
    if (request.headers.get("Upgrade") !== "websocket") {
      return new Response("Expected WebSocket", { status: 426 });
    }
    if (!this.originAllowed(request)) {
      return new Response("Forbidden", { status: 403 });
    }

    // Same-origin websocket upgrades carry the session cookie; attach the
    // account (if any) so queueing and rated games know who this socket is.
    const attachment: SessionAttachment = { id: crypto.randomUUID() };
    const db = await this.db();
    if (db) {
      try {
        const token = sessionTokenFromCookieHeader(request.headers.get("Cookie"));
        const user = await userForSession(db, token);
        if (user) {
          attachment.userId = user.id;
          attachment.username = user.username;
        }
      } catch {
        // Anonymous on any auth failure.
      }
    }

    const pair = new WebSocketPair();
    const [client, server] = Object.values(pair);
    server.serializeAttachment(attachment);
    this.sessions.set(server, attachment);
    this.ctx.acceptWebSocket(server);

    return new Response(null, { status: 101, webSocket: client });
  }

  async webSocketMessage(ws: WebSocket, message: ArrayBuffer | string) {
    let frame: ClientFrame;
    try {
      frame = JSON.parse(typeof message === "string" ? message : new TextDecoder().decode(message)) as ClientFrame;
    } catch {
      return error(ws, "bad_json", "Messages must be JSON objects.");
    }

    switch (frame.t) {
      case "create":
        return this.createMatch(ws, frame.d);
      case "join":
        return this.joinMatch(ws, frame.d);
      case "reconnect":
        return this.reconnectMatch(ws, frame.d);
      case "move":
        return this.playClientMove(ws, frame.d);
      case "resign":
        return this.resignGame(ws);
      case "drawOffer":
        return this.offerDraw(ws);
      case "drawAccept":
        return this.acceptDraw(ws);
      case "drawDecline":
        return this.declineDraw(ws);
      case "queue":
        return this.queueJoin(ws, frame.d);
      case "queueCancel":
        return this.queueLeave(ws, true);
      case "watch":
        return this.watchMatch(ws, frame.d);
      case "p":
        return this.sendClocks(ws);
      default:
        return error(ws, "unknown_message", "Unknown message type.");
    }
  }

  async webSocketClose(ws: WebSocket) {
    await this.queueLeave(ws, false);
    await this.detachSession(ws);
  }

  async webSocketError(ws: WebSocket) {
    await this.queueLeave(ws, false);
    await this.detachSession(ws);
  }

  async alarm() {
    await this.maintenanceAll();
  }

  private originAllowed(request: Request): boolean {
    const origin = request.headers.get("Origin");
    const configured = (this.env.GAME_SERVER_ORIGINS || "")
      .split(",")
      .map((allowed) => allowed.trim())
      .filter(Boolean);

    // Explicit allowlist: only the configured origins may connect.
    if (configured.length > 0) {
      return !!origin && configured.includes(origin);
    }

    // No allowlist configured: fail closed to same-origin only. Requests
    // without an Origin header (non-browser clients, which cannot be targets
    // of browser CSRF) are still permitted; cross-origin browser requests are
    // rejected instead of being allowed unconditionally.
    if (!origin) return true;
    try {
      return new URL(origin).host === new URL(request.url).host;
    } catch {
      return false;
    }
  }

  private async loadMatch(id: string): Promise<StoredMatch | null> {
    return (await this.ctx.storage.get<StoredMatch>(matchKey(id))) ?? null;
  }

  private async saveMatch(match: StoredMatch, schedule = true) {
    await this.ctx.storage.put(matchKey(match.id), match);
    if (schedule) await this.scheduleAlarmForMatch(match);
  }

  private async deleteMatch(match: StoredMatch) {
    for (const [ws, session] of this.sessions) {
      if (session.matchId === match.id) {
        this.sessions.delete(ws);
        ws.close(1000, "Game expired");
      }
    }
    await this.ctx.storage.delete(matchKey(match.id));
  }

  private connectedSession(matchId: string, color: Color): WebSocket | undefined {
    for (const [ws, session] of this.sessions) {
      if (session.matchId === matchId && session.color === color && ws.readyState === WebSocket.OPEN) return ws;
    }
    return undefined;
  }

  private connectedSessions(matchId: string): WebSocket[] {
    return [...this.sessions]
      .filter(([ws, session]) => session.matchId === matchId && ws.readyState === WebSocket.OPEN)
      .map(([ws]) => ws);
  }

  private session(ws: WebSocket): SessionAttachment {
    const restored = ws.deserializeAttachment() as SessionAttachment | null;
    const session = this.sessions.get(ws) ?? restored;
    if (!session) {
      const next = { id: crypto.randomUUID() };
      this.sessions.set(ws, next);
      ws.serializeAttachment(next);
      return next;
    }
    this.sessions.set(ws, session);
    return session;
  }

  private async attachSession(ws: WebSocket, match: StoredMatch, color: Color) {
    const existing = this.connectedSession(match.id, color);
    if (existing && existing !== ws) existing.close(1000, "Reconnected from another tab");

    const session = { ...this.session(ws), matchId: match.id, color, token: match.tokens[color] };
    delete session.watching;
    this.sessions.set(ws, session);
    ws.serializeAttachment(session);
    delete match.disconnectedAt[color];
    delete match.opponentGoneNotified[color];

    // Remember which account holds this seat (used for names in the UI and
    // for game history). Matchmade seats are assigned at pairing and are
    // never overwritten here.
    if (session.userId && session.username && !match.users?.[color]) {
      let rating = 1500;
      const db = await this.db();
      if (db) {
        try {
          const row = await db
            .prepare("SELECT rating FROM users WHERE id = ?")
            .bind(session.userId)
            .first<{ rating: number }>();
          if (row) rating = row.rating;
        } catch {}
      }
      match.users = { ...(match.users ?? {}), [color]: { id: session.userId, name: session.username, rating } };
    }
  }

  private async detachSession(ws: WebSocket) {
    const session = this.sessions.get(ws) ?? (ws.deserializeAttachment() as SessionAttachment | null);
    this.sessions.delete(ws);
    if (!session?.matchId || !session.color) return;
    if (this.connectedSession(session.matchId, session.color)) return;

    const match = await this.loadMatch(session.matchId);
    if (!match) return;
    match.disconnectedAt[session.color] = Date.now();
    match.opponentGoneNotified[session.color] = false;
    await this.saveMatch(match);
  }

  private async newCode(length = 5): Promise<string> {
    let code = randomCode(length);
    while (await this.loadMatch(code)) code = randomCode(length);
    return code;
  }

  private socketForAttachment(id: string): WebSocket | undefined {
    for (const [ws, session] of this.sessions) {
      if (session.id === id && ws.readyState === WebSocket.OPEN) return ws;
    }
    return undefined;
  }

  private playersPayload(match: StoredMatch) {
    const seat = (color: Color) => {
      const user = match.users?.[color];
      return user
        ? { name: user.name, rating: Math.round(user.rating) }
        : { name: "Anonymous", rating: null };
    };
    return { w: seat("w"), b: seat("b") };
  }

  private sendWatchers(match: StoredMatch, t: string, d?: unknown) {
    for (const [ws, session] of this.sessions) {
      if (session.watching === match.id && ws.readyState === WebSocket.OPEN) send(ws, t, d);
    }
  }

  private startPayload(match: StoredMatch, color: Color) {
    const clocks = this.currentClocks(match);
    const myNerfId = color === "w" ? match.setup.whiteNerfId : match.setup.blackNerfId;
    const masterRng = new RNG(match.setup.seed);
    const wSeed = masterRng.fork().getState();
    const bSeed = masterRng.fork().getState();
    const nerfSeed = color === "w" ? wSeed : bSeed;
    return {
      id: match.id,
      color,
      token: match.tokens[color],
      nerfId: myNerfId,
      nerfSeed,
      timeSec: match.setup.timeSec,
      incrementSec: match.setup.incrementSec,
      wc: Math.round(clocks.w),
      bc: Math.round(clocks.b),
      moves: match.moves,
      players: this.playersPayload(match),
      rated: !!match.rated,
    };
  }

  private sendStart(match: StoredMatch, color: Color) {
    const ws = this.connectedSession(match.id, color);
    send(ws, "start", this.startPayload(match, color));
    if (match.result) {
      const clocks = this.currentClocks(match);
      send(ws, "end", { result: match.result, wc: Math.round(clocks.w), bc: Math.round(clocks.b) });
    }
  }

  private broadcast(match: StoredMatch, t: string, d?: unknown) {
    send(this.connectedSession(match.id, "w"), t, d);
    send(this.connectedSession(match.id, "b"), t, d);
  }

  private gameFromMatch(match: StoredMatch): NerfGame | null {
    if (!match.startedAt) return null;
    const white = PLAYABLE_NERFS.find((nerf) => nerf.id === match.setup.whiteNerfId);
    const black = PLAYABLE_NERFS.find((nerf) => nerf.id === match.setup.blackNerfId);
    if (!white || !black) return null;

    let game = newGame(white, black, match.setup.seed);
    for (const uci of match.moves) {
      const move = moveByUci(game, uci);
      if (!move) return null;
      game = playMove(game, move);
    }
    if (match.result) game.result = match.result;
    return game;
  }

  private currentClocks(match: StoredMatch, now = Date.now()): Record<Color, number> {
    const clocks = { ...match.clocks };
    const game = this.gameFromMatch(match);
    if (!match.setup.timeSec || !game || game.result || match.runningSince === null) return clocks;
    const active = game.board.turn;
    clocks[active] = Math.max(0, clocks[active] - (now - match.runningSince));
    return clocks;
  }

  private async finishOnFlag(match: StoredMatch, now = Date.now(), schedule = true): Promise<boolean> {
    const game = this.gameFromMatch(match);
    if (!game || game.result || !match.setup.timeSec) return false;
    const clocks = this.currentClocks(match, now);
    const active = game.board.turn;
    if (clocks[active] > 0) return false;

    match.clocks = clocks;
    match.runningSince = null;
    match.result = {
      winner: active === "w" ? "b" : "w",
      reason: active === "w" ? "white ran out of time" : "black ran out of time",
    };
    match.completedAt = now;
    await this.endMatch(match, schedule);
    return true;
  }

  // Single exit point for a finished match: persist it to D1 (updating both
  // ratings when the game was rated), then notify players and spectators.
  private async endMatch(match: StoredMatch, schedule = true) {
    if (!match.result) return;
    if (!match.completedAt) match.completedAt = Date.now();

    let ratings: { w: RatingChange | null; b: RatingChange | null } | null = null;
    if (!match.recorded && match.startedAt) {
      match.recorded = true;
      const db = await this.db();
      if (db) {
        try {
          const recorded = await recordFinishedGame(db, {
            id: match.id,
            whiteUserId: match.users?.w?.id ?? null,
            blackUserId: match.users?.b?.id ?? null,
            whiteName: match.users?.w?.name ?? "Anonymous",
            blackName: match.users?.b?.name ?? "Anonymous",
            whiteNerfId: match.setup.whiteNerfId,
            blackNerfId: match.setup.blackNerfId,
            seed: match.setup.seed,
            timeSec: match.setup.timeSec,
            incrementSec: match.setup.incrementSec,
            moves: match.moves,
            winner: match.result.winner,
            reason: match.result.reason,
            rated: !!match.rated,
            startedAt: match.startedAt,
            completedAt: match.completedAt,
          });
          if (recorded.white || recorded.black) {
            ratings = { w: recorded.white, b: recorded.black };
          }
        } catch (err) {
          console.error("failed to record game", match.id, err);
        }
      }
    }
    await this.saveMatch(match, schedule);

    const clocks = this.currentClocks(match);
    const payload = {
      result: match.result,
      wc: Math.round(clocks.w),
      bc: Math.round(clocks.b),
      ...(ratings ? { ratings } : {}),
    };
    this.broadcast(match, "end", payload);
    this.sendWatchers(match, "end", {
      ...payload,
      nerfs: { w: match.setup.whiteNerfId, b: match.setup.blackNerfId },
    });
  }

  private async createMatch(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    if (session.matchId) return error(ws, "already_joined", "This connection already belongs to a game.");

    const requested = (data || {}) as { timeSec?: unknown; incrementSec?: unknown };
    const timeSec = Number.isInteger(requested.timeSec) ? Number(requested.timeSec) : 600;
    const incrementSec = Number.isInteger(requested.incrementSec) ? Number(requested.incrementSec) : 0;
    if (timeSec < 0 || timeSec > 7200 || incrementSec < 0 || incrementSec > 60) {
      return error(ws, "invalid_clock", "Unsupported time control.");
    }

    const id = await this.newCode();
    const match: StoredMatch = {
      id,
      setup: {
        whiteNerfId: pickNerfId(),
        blackNerfId: pickNerfId(),
        seed: makeSeed(),
        timeSec,
        incrementSec,
      },
      tokens: { w: newToken(), b: newToken() },
      disconnectedAt: {},
      opponentGoneNotified: {},
      moves: [],
      result: null,
      clocks: { w: timeSec * 1000, b: timeSec * 1000 },
      runningSince: null,
      drawOfferBy: null,
      createdAt: Date.now(),
      startedAt: null,
      completedAt: null,
    };

    await this.attachSession(ws, match, "w");
    await this.saveMatch(match);
    send(ws, "created", { id, color: "w", token: match.tokens.w });
  }

  private async joinMatch(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    if (session.matchId) return error(ws, "already_joined", "This connection already belongs to a game.");

    const id = String((data as { id?: unknown } | undefined)?.id || "").trim().toUpperCase();
    const match = await this.loadMatch(id);
    if (!match || match.startedAt || this.connectedSession(id, "b")) {
      return error(ws, "not_found", "That code is not accepting a player.");
    }

    await this.attachSession(ws, match, "b");
    match.startedAt = Date.now();
    match.runningSince = match.startedAt;
    await this.saveMatch(match);
    this.sendStart(match, "w");
    this.sendStart(match, "b");
  }

  private async reconnectMatch(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    if (session.matchId) return error(ws, "already_joined", "This connection already belongs to a game.");

    const request = (data || {}) as { id?: unknown; color?: unknown; token?: unknown };
    const id = String(request.id || "").trim().toUpperCase();
    const color = isColor(request.color) ? request.color : null;
    const token = typeof request.token === "string" ? request.token : "";
    const match = await this.loadMatch(id);
    if (!match || !color || match.tokens[color] !== token) {
      return error(ws, "reconnect_failed", "Could not resume that game.");
    }

    await this.attachSession(ws, match, color);
    await this.saveMatch(match);
    if (!match.startedAt) {
      // Matchmade games begin the moment both paired players arrive at the
      // game URL; friend games wait in the lobby until someone joins by code.
      if (match.rated && this.connectedSession(match.id, "w") && this.connectedSession(match.id, "b")) {
        match.startedAt = Date.now();
        match.runningSince = match.startedAt;
        await this.saveMatch(match);
        this.sendStart(match, "w");
        this.sendStart(match, "b");
        return;
      }
      return send(ws, "created", { id, color, token: match.tokens[color] });
    }
    this.sendStart(match, color);
  }

  private async playClientMove(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before sending moves.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return error(ws, "game_over", "This game is over.");

    const game = this.gameFromMatch(match);
    if (!game) return error(ws, "no_game", "Join a game before sending moves.");
    if (game.board.turn !== session.color) return error(ws, "not_your_turn", "It is not your turn.");

    const request = (data || {}) as { u?: unknown; ply?: unknown };
    const uci = typeof request.u === "string" ? request.u.toLowerCase() : "";
    if (Number.isInteger(request.ply) && Number(request.ply) !== match.moves.length) {
      return error(ws, "stale_ply", "Your board is out of date.");
    }
    const move = moveByUci(game, uci);
    if (!move) return error(ws, "illegal_move", "That move is not legal in the current position.");

    const now = Date.now();
    match.clocks = this.currentClocks(match, now);
    if (match.drawOfferBy && match.drawOfferBy !== session.color) {
      const declinedBy = session.color;
      match.drawOfferBy = null;
      this.broadcast(match, "drawDeclined", { color: declinedBy });
    }
    const nextGame = playMove(game, move);
    match.moves.push(uci);
    if (match.setup.timeSec) match.clocks[session.color] += match.setup.incrementSec * 1000;
    match.runningSince = nextGame.result ? null : now;
    match.result = nextGame.result;
    if (nextGame.result) match.completedAt = now;
    await this.saveMatch(match);

    const movePayload = {
      u: uci,
      ply: match.moves.length,
      wc: Math.round(match.clocks.w),
      bc: Math.round(match.clocks.b),
    };
    this.broadcast(match, "move", movePayload);
    this.sendWatchers(match, "move", movePayload);
    if (match.result) await this.endMatch(match);
  }

  private async resignGame(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before resigning.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;

    const game = this.gameFromMatch(match);
    if (!game) return error(ws, "no_game", "Join a game before resigning.");

    match.clocks = this.currentClocks(match);
    match.runningSince = null;
    match.result = resign(game, session.color).result;
    match.completedAt = Date.now();
    await this.endMatch(match);
  }

  private async offerDraw(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before offering a draw.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;
    if (match.drawOfferBy === session.color) return error(ws, "draw_pending", "Your draw offer is already pending.");
    if (match.drawOfferBy && match.drawOfferBy !== session.color) return this.acceptDraw(ws);

    match.drawOfferBy = session.color;
    await this.saveMatch(match);
    this.broadcast(match, "drawOffer", { color: session.color });
  }

  private async acceptDraw(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before accepting a draw.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;
    if (!match.drawOfferBy || match.drawOfferBy === session.color) {
      return error(ws, "no_draw_offer", "There is no opponent draw offer to accept.");
    }

    match.clocks = this.currentClocks(match);
    match.runningSince = null;
    match.drawOfferBy = null;
    match.result = { winner: "draw", reason: "draw by agreement" };
    match.completedAt = Date.now();
    await this.endMatch(match);
  }

  private async declineDraw(ws: WebSocket) {
    const session = this.session(ws);
    const match = session.matchId ? await this.loadMatch(session.matchId) : null;
    if (!match || !session.color) return error(ws, "no_game", "Join a game before declining a draw.");
    if (await this.finishOnFlag(match)) return;
    if (match.result) return;
    if (!match.drawOfferBy || match.drawOfferBy === session.color) {
      return error(ws, "no_draw_offer", "There is no opponent draw offer to decline.");
    }

    match.drawOfferBy = null;
    await this.saveMatch(match);
    this.broadcast(match, "drawDeclined", { color: session.color });
  }

  // ---------------- matchmaking queue ----------------

  private queueKey(pool: string): string {
    return `queue:${pool}`;
  }

  private async queueJoin(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    if (session.matchId) return error(ws, "already_joined", "This connection already belongs to a game.");
    if (!session.userId || !session.username) {
      return error(ws, "auth_required", "Sign in to play rated games.");
    }
    const poolName = String((data as { pool?: unknown } | undefined)?.pool || "3+2");
    const pool = QUEUE_POOLS[poolName];
    if (!pool) return error(ws, "bad_pool", "Unknown queue pool.");
    const db = await this.db();
    if (!db) return error(ws, "server_unconfigured", "Matchmaking is unavailable right now.");

    let rating = 1500;
    try {
      const row = await db
        .prepare("SELECT rating FROM users WHERE id = ?")
        .bind(session.userId)
        .first<{ rating: number }>();
      if (row) rating = row.rating;
    } catch {}

    const key = this.queueKey(poolName);
    let entries = (await this.ctx.storage.get<QueueEntry[]>(key)) ?? [];
    // Drop dead sockets and any previous entry by this same account.
    entries = entries.filter(
      (entry) => entry.userId !== session.userId && this.socketForAttachment(entry.attachmentId),
    );

    const opponent = entries.shift();
    if (!opponent) {
      entries.push({
        attachmentId: session.id,
        userId: session.userId,
        username: session.username,
        rating,
        at: Date.now(),
      });
      await this.ctx.storage.put(key, entries);
      return send(ws, "queued", { pool: poolName });
    }
    await this.ctx.storage.put(key, entries);

    const opponentWs = this.socketForAttachment(opponent.attachmentId)!;
    const meWhite = randomInt(2) === 0;
    const me: SeatUser = { id: session.userId, name: session.username, rating };
    const them: SeatUser = { id: opponent.userId, name: opponent.username, rating: opponent.rating };
    const id = await this.newCode(8);
    const match: StoredMatch = {
      id,
      setup: {
        whiteNerfId: pickNerfId(),
        blackNerfId: pickNerfId(),
        seed: makeSeed(),
        timeSec: pool.timeSec,
        incrementSec: pool.incrementSec,
      },
      tokens: { w: newToken(), b: newToken() },
      disconnectedAt: {},
      opponentGoneNotified: {},
      moves: [],
      result: null,
      clocks: { w: pool.timeSec * 1000, b: pool.timeSec * 1000 },
      runningSince: null,
      drawOfferBy: null,
      createdAt: Date.now(),
      startedAt: null,
      completedAt: null,
      rated: true,
      users: { w: meWhite ? me : them, b: meWhite ? them : me },
    };
    await this.saveMatch(match);

    // Both clients navigate to /game/{id} and take their seat via `reconnect`;
    // the game starts once both have arrived.
    const myColor: Color = meWhite ? "w" : "b";
    const theirColor: Color = meWhite ? "b" : "w";
    send(ws, "paired", { id, color: myColor, token: match.tokens[myColor], pool: poolName });
    send(opponentWs, "paired", { id, color: theirColor, token: match.tokens[theirColor], pool: poolName });
  }

  private async queueLeave(ws: WebSocket, notify: boolean) {
    const session = this.sessions.get(ws) ?? (ws.deserializeAttachment() as SessionAttachment | null);
    if (!session) return;
    for (const poolName of Object.keys(QUEUE_POOLS)) {
      const key = this.queueKey(poolName);
      const entries = (await this.ctx.storage.get<QueueEntry[]>(key)) ?? [];
      const next = entries.filter((entry) => entry.attachmentId !== session.id);
      if (next.length !== entries.length) await this.ctx.storage.put(key, next);
    }
    if (notify) send(ws, "queueCancelled");
  }

  // ---------------- spectating ----------------

  private async watchMatch(ws: WebSocket, data: unknown) {
    const session = this.session(ws);
    if (session.matchId) return error(ws, "already_joined", "This connection already belongs to a game.");
    const id = String((data as { id?: unknown } | undefined)?.id || "").trim().toUpperCase();
    const match = await this.loadMatch(id);
    if (!match) return error(ws, "not_found", "No live game with that id.");
    await this.finishOnFlag(match);

    const next = { ...session, watching: id };
    this.sessions.set(ws, next);
    ws.serializeAttachment(next);

    const clocks = this.currentClocks(match);
    send(ws, "wstart", {
      id,
      timeSec: match.setup.timeSec,
      incrementSec: match.setup.incrementSec,
      wc: Math.round(clocks.w),
      bc: Math.round(clocks.b),
      moves: match.moves,
      players: this.playersPayload(match),
      rated: !!match.rated,
      started: !!match.startedAt,
      result: match.result,
      // Hidden rules are only revealed to spectators once the game is over.
      ...(match.result ? { nerfs: { w: match.setup.whiteNerfId, b: match.setup.blackNerfId } } : {}),
    });
  }

  private async sendClocks(ws: WebSocket) {
    const session = this.session(ws);
    const watchedId = session.matchId ?? session.watching;
    const match = watchedId ? await this.loadMatch(watchedId) : null;
    if (!match) return send(ws, "n");
    if (await this.finishOnFlag(match)) return;
    const clocks = this.currentClocks(match);
    send(ws, "n", { wc: Math.round(clocks.w), bc: Math.round(clocks.b) });
  }

  private candidateAlarm(match: StoredMatch, now = Date.now()): number | null {
    const candidates: number[] = [];
    const game = this.gameFromMatch(match);
    if (match.setup.timeSec && game && !game.result && match.runningSince !== null) {
      candidates.push(match.runningSince + match.clocks[game.board.turn]);
    }
    for (const color of ["w", "b"] as Color[]) {
      const disconnectedAt = match.disconnectedAt[color];
      if (disconnectedAt && !match.opponentGoneNotified[color]) candidates.push(disconnectedAt + disconnectGraceMs);
    }

    const expiry = match.completedAt ?? match.createdAt;
    if (match.completedAt) candidates.push(expiry + 60 * 60 * 1000);
    else if (!match.startedAt) candidates.push(expiry + 30 * 60 * 1000);
    else if (this.connectedSessions(match.id).length === 0) {
      const latestDisconnect = Math.max(match.disconnectedAt.w ?? 0, match.disconnectedAt.b ?? 0);
      if (latestDisconnect) candidates.push(latestDisconnect + 30 * 60 * 1000);
    }

    const next = Math.min(...candidates.filter((candidate) => candidate > now));
    return Number.isFinite(next) ? next : null;
  }

  private async scheduleAlarmForMatch(match: StoredMatch) {
    const next = this.candidateAlarm(match);
    if (!next) return;
    const existing = await this.ctx.storage.getAlarm();
    if (!existing || next < existing) await this.ctx.storage.setAlarm(next);
  }

  private async scheduleNextAlarm(matches: StoredMatch[]) {
    const next = Math.min(...matches.map((match) => this.candidateAlarm(match) ?? Number.POSITIVE_INFINITY));
    if (Number.isFinite(next)) await this.ctx.storage.setAlarm(next);
    else await this.ctx.storage.deleteAlarm();
  }

  private async cleanupExpired() {
    const matches = [...(await this.ctx.storage.list<StoredMatch>({ prefix: "match:" })).values()];
    const now = Date.now();
    for (const match of matches) {
      if (match.completedAt && now - match.completedAt > 60 * 60 * 1000) await this.deleteMatch(match);
      else if (!match.startedAt && now - match.createdAt > 30 * 60 * 1000) await this.deleteMatch(match);
    }
  }

  private async maintenanceAll() {
    const matches = [...(await this.ctx.storage.list<StoredMatch>({ prefix: "match:" })).values()];
    const now = Date.now();
    const remaining: StoredMatch[] = [];

    for (const match of matches) {
      let changed = await this.finishOnFlag(match, now, false);
      for (const color of ["w", "b"] as Color[]) {
        const disconnectedAt = match.disconnectedAt[color];
        const opponent = this.connectedSession(match.id, color === "w" ? "b" : "w");
        if (disconnectedAt && opponent && !match.opponentGoneNotified[color] && now - disconnectedAt > disconnectGraceMs) {
          send(opponent, "opponentGone");
          match.opponentGoneNotified[color] = true;
          changed = true;
        }
      }

      const bothDisconnected = this.connectedSessions(match.id).length === 0;
      const latestDisconnect = Math.max(match.disconnectedAt.w ?? 0, match.disconnectedAt.b ?? 0);
      if (
        (match.completedAt && now - match.completedAt > 60 * 60 * 1000) ||
        (!match.startedAt && now - match.createdAt > 30 * 60 * 1000) ||
        (match.startedAt && bothDisconnected && latestDisconnect && now - latestDisconnect > 30 * 60 * 1000)
      ) {
        await this.deleteMatch(match);
        continue;
      }

      if (changed) await this.saveMatch(match, false);
      remaining.push(match);
    }

    await this.scheduleNextAlarm(remaining);
  }
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (url.pathname === socketPath || url.pathname === "/healthz") {
      const id = env.GAME_SERVER.idFromName(globalServerName);
      return env.GAME_SERVER.get(id).fetch(request);
    }
    return handler.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<Env>;

// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
