import { attackedBy, cloneBoard, countRepetitions, findKing, generateMoves, initialBoard, isInCheck, kingCaptured, makeMove } from "./board";
import {
  ActiveEffect,
  aiCanUse,
  Buff,
  BuffApi,
  BuffInstance,
  BuffMatchState,
  BuffPick,
  BuffTarget,
  DraftMode,
  effectTickColor,
  newBuffMatchState,
} from "./buff";
import { grantGuaranteedTier9, pawnRankOk } from "./buffs/helpers";
import { BUFF_BY_ID } from "./buffs/library";
import { PLAYABLE_NERFS } from "./nerfs/library";
import { DEFAULT_CADENCE, NERF_MODE_CADENCE, bankOffer, rerollOffer, rollOffer, rollOpenerOffers, rollSharedTiers } from "./draft";
import { Nerf, NerfState, GameContext, Tier } from "./nerf";
import { RNG } from "./rng";
import { BoardState, Color, FILE, Move, PieceType, RANK, SQ, Square, squareName } from "./types";

export interface PlayerSlot {
  nerf: Nerf;
  state: NerfState;
  color: Color;
  rng: RNG;
}

export interface GameResult {
  winner: Color | "draw" | null;
  reason: string;
}

export interface NerfGame {
  board: BoardState;
  white: PlayerSlot;
  black: PlayerSlot;
  result: GameResult | null;
  startedAt: number;
  // running counters per color
  captured: Record<Color, { p: number; n: number; b: number; r: number; q: number; k: number }>;
  /** Present only in draft-mode games: buffs, drafts, and board effects. */
  buffs?: BuffMatchState;
}

function emptyCounts() {
  return { p: 0, n: 0, b: 0, r: 0, q: 0, k: 0 };
}

export function newGame(whiteNerf: Nerf, blackNerf: Nerf, seed: number): NerfGame {
  const rng = new RNG(seed);
  const wRng = rng.fork();
  const bRng = rng.fork();
  const board = initialBoard();
  const white: PlayerSlot = {
    nerf: whiteNerf,
    state: whiteNerf.init ? whiteNerf.init(wRng, "w") : {},
    color: "w",
    rng: wRng,
  };
  const black: PlayerSlot = {
    nerf: blackNerf,
    state: blackNerf.init ? blackNerf.init(bRng, "b") : {},
    color: "b",
    rng: bRng,
  };
  const game: NerfGame = {
    board,
    white,
    black,
    result: null,
    startedAt: Date.now(),
    captured: { w: emptyCounts(), b: emptyCounts() },
  };
  // Run onTurnStart for the first player
  applyTurnStart(game);
  return game;
}

const NOOP_NERF: Nerf = {
  id: "noop",
  name: "Unknown",
  description: "",
  tier: 1,
  implemented: true,
};

// What a player's nerf becomes when a Nerf Breaker style buff removes it.
const FREED_NERF: Nerf = {
  id: "nerf_removed",
  name: "Unshackled",
  description: "This nerf was removed by a buff. No handicap remains.",
  tier: 1,
  implemented: true,
};

// Buff mode games have no handicaps at all: both players run this nerf.
export const UNRESTRICTED_NERF: Nerf = {
  id: "none",
  name: "No nerf",
  description: "Buff mode: no handicap. Win with the buffs you draft.",
  tier: 1,
  implemented: true,
};

// ---------------------------------------------------------------------------
// Game state snapshots (checkpointing).
//
// A NerfGame is plain JSON data except for two things per player slot: the Nerf
// def (carries functions — keyed by id and rehydrated from the registry) and
// the RNG (Mulberry32, whose entire state is one number via getState/fromState).
// The buff/draft state already stores its RNG as a plain `rngState` number, so
// it serializes as-is once the purely transient bookkeeping (regenerated by the
// next apply cycle, never persisted) is dropped.
//
// A snapshot lets a caller resume a game from a mid-game ply instead of
// replaying every move from the start. The version stamp lets a reader reject a
// stale snapshot (e.g. after an engine change) and fall back to a full replay,
// so a snapshot can only ever be a speedup — never a correctness risk.
export const GAME_SNAPSHOT_VERSION = 1;

type SlotSnapshot = { nerfId: string; state: NerfState; rngState: number };

export interface GameSnapshot {
  v: number;
  board: BoardState;
  captured: NerfGame["captured"];
  result: GameResult | null;
  startedAt: number;
  slots: { w: SlotSnapshot; b: SlotSnapshot };
  buffs?: BuffMatchState;
}

// Lazily built (avoids any import-order surprise with the nerf library) map from
// nerf id to its def. Covers the playable pool, buff mode's UNRESTRICTED_NERF,
// and the two internal specials a slot can hold mid-game: NOOP_NERF
// (single-color games) and FREED_NERF (a Nerf Breaker removed the handicap).
let SNAPSHOT_NERF_BY_ID: Map<string, Nerf> | null = null;
function snapshotNerfById(id: string): Nerf {
  if (!SNAPSHOT_NERF_BY_ID) {
    SNAPSHOT_NERF_BY_ID = new Map();
    for (const n of [...PLAYABLE_NERFS, UNRESTRICTED_NERF, FREED_NERF, NOOP_NERF]) {
      SNAPSHOT_NERF_BY_ID.set(n.id, n);
    }
  }
  // An unknown id degrades to NOOP (no handicap) rather than throwing, matching
  // how a missing setup nerf id already behaves on a normal rebuild.
  return SNAPSHOT_NERF_BY_ID.get(id) ?? NOOP_NERF;
}

/** Freeze a live game into a plain, JSON-safe snapshot. Shares no references
 * with `game` (the caller may keep mutating it). */
export function serializeGame(game: NerfGame): GameSnapshot {
  const slot = (s: PlayerSlot): SlotSnapshot => ({
    nerfId: s.nerf.id,
    state: s.state,
    rngState: s.rng.getState(),
  });
  let buffs: BuffMatchState | undefined;
  if (game.buffs) {
    // mutations / lastHookMutations / clockFx are transient-only: never
    // persisted, regenerated by the next apply cycle. Dropping them keeps the
    // snapshot equal to what a fresh replay of the same record produces.
    const { mutations, lastHookMutations, clockFx, ...persistent } = game.buffs;
    void mutations;
    void lastHookMutations;
    void clockFx;
    buffs = persistent;
  }
  const snap: GameSnapshot = {
    v: GAME_SNAPSHOT_VERSION,
    board: game.board,
    captured: game.captured,
    result: game.result,
    startedAt: game.startedAt,
    slots: { w: slot(game.white), b: slot(game.black) },
    ...(buffs ? { buffs } : {}),
  };
  // Deep-clone through JSON so the snapshot shares no structure with the live
  // game and to assert the state really is plain data (a stray function would
  // be dropped here and surface immediately in the round-trip test).
  return JSON.parse(JSON.stringify(snap)) as GameSnapshot;
}

/** Rebuild a live game from a snapshot. The result is fully detached from
 * `snap`, so the caller can mutate it (play moves) without corrupting a stored
 * checkpoint. Returns null if the snapshot is from an older schema. */
export function deserializeGame(snap: GameSnapshot): NerfGame | null {
  if (!snap || snap.v !== GAME_SNAPSHOT_VERSION) return null;
  const copy = JSON.parse(JSON.stringify(snap)) as GameSnapshot;
  const mkSlot = (color: Color, s: SlotSnapshot): PlayerSlot => ({
    nerf: snapshotNerfById(s.nerfId),
    state: s.state,
    color,
    rng: RNG.fromState(s.rngState),
  });
  return {
    board: copy.board,
    white: mkSlot("w", copy.slots.w),
    black: mkSlot("b", copy.slots.b),
    result: copy.result,
    startedAt: copy.startedAt,
    captured: copy.captured,
    ...(copy.buffs ? { buffs: copy.buffs } : {}),
  };
}

// ---------------------------------------------------------------------------
// Public spectator snapshot.
//
// A PublicSpectatorSnapshot is a read-only PROJECTION of the authoritative game
// (server: gameFromMatch; a player's own game.ts) into exactly the state a
// spectator, the TV, or a profile preview is allowed to see. It is deliberately
// SEPARATE from the secret GameSnapshot (which carries slot RNG state, the
// nerf identities, and every hidden field): this snapshot never contains a
// secret nerf id, a draft seed, an rng state, an unrevealed card, a private
// offer, or any future delayed-event target identity. What a viewer cannot
// legitimately know is simply not projected, so the snapshot and its hash can
// be shipped to anyone.
//
// PUBLIC_SNAPSHOT_VERSION is independent of GAME_SNAPSHOT_VERSION and of the
// worker's REPLAY_VERSION. A client that sees an unrecognized schemaVersion
// rejects the frame (a later stage) rather than rendering a wrong board.
export const PUBLIC_SNAPSHOT_VERSION = 1;

export type SpectatorPhase = "active" | "draftPaused" | "chessDiff" | "over";

export type PublicTimerState = "running-w" | "running-b" | "paused" | "flagged";

export interface PublicPiece {
  /** Stable-per-snapshot id: the piece's square name (a1..h8). The engine has
   * no persistent piece identity, so the square is the only public, stable key
   * for a point-in-time projection; it is deterministic and leaks nothing. */
  id: string;
  color: Color;
  type: PieceType;
  /** 0..63, file = square % 8, rank = square >> 3. */
  square: number;
  /** Piece is frozen / walnut-locked in place by a public board effect. */
  frozen?: boolean;
  /** Piece stands on a shielded square. */
  shielded?: boolean;
}

export interface PublicSquareEffect {
  kind: ActiveEffect["kind"];
  /** Squares the effect covers, sorted ascending. A side-wide effect (king
   * safety, a movement lock) covers no specific squares and lists none. */
  squares: number[];
  owner?: Color;
  against?: Color;
  /** Remaining public turns; null = untimed. Never a hidden target identity. */
  turns: number | null;
}

export interface PublicWall {
  axis: "file" | "rank";
  /** 0..7 index of the barred file/rank. */
  line: number;
  against: Color;
}

export interface PublicHeldBuff {
  buffId: string;
  category: string;
  tier: number;
  kind: "passive" | "instant" | "activated";
  spent?: boolean;
  nullified?: boolean;
  /** Always true: only publicly-revealed cards are ever projected here. */
  revealed: true;
}

export interface PublicPlayerInfo {
  name: string;
  rating: number | null;
  ratingCategory?: string | null;
  title?: string | null;
  provisional?: boolean;
}

export interface PublicCaptureCounts {
  p: number;
  n: number;
  b: number;
  r: number;
  q: number;
  k: number;
}

/**
 * The match-level PUBLIC bits the projector needs but that live on the match
 * record, not on the engine game (ids, ratings, clocks, revealed rules, the
 * server's monotonic revision). Every field here is already public: the caller
 * (worker.ts publicSnapshot) is responsible for passing only revealed nerf ids
 * and masked card history, never raw slot state.
 */
export interface PublicSnapshotBits {
  gameId: string;
  replayVersion: number;
  /** Monotonic per-game revision, ++ on every committed event. */
  stateRevision: number;
  /** Seq of the last applied event at capture (== stateRevision). */
  lastSeq: number;
  /** draftActions index folded into the projected game. */
  cursor: number;
  capturedAtMs: number;
  mode: DraftMode | null;
  rated: boolean;
  players: { w: PublicPlayerInfo; b: PublicPlayerInfo };
  /** Public clock values, ms remaining. Excluded from the parity hash. */
  clocks: { w: number; b: number };
  timeSec: number;
  incrementSec: number;
  timerState: PublicTimerState;
  /** Revealed nerf ids only (match result set, or slot revealed); else null. */
  revealedNerfs: { w: string | null; b: string | null };
  /** Masked draft-action record (rerolls/hidden grants already dropped). */
  publicCardHistory?: unknown[];
  /** Public offer seats (a seat currently holding an unresolved offer). */
  offerSeats?: { w: boolean; b: boolean };
  nextDraftAtPly?: number | null;
  spectatorDelaySec?: number;
  /** Advisory flourish hint (last card play id). Never gates state. */
  lastCardPlayId?: string | null;
}

export interface PublicSpectatorSnapshot {
  gameId: string;
  schemaVersion: number;
  replayVersion: number;
  stateRevision: number;
  lastSeq: number;
  capturedAtPly: number;
  capturedAtCursor: number;
  capturedAtMs: number;

  mode: DraftMode | null;
  rated: boolean;
  players: { w: PublicPlayerInfo; b: PublicPlayerInfo };

  board: {
    dims: { files: number; ranks: number };
    sideToMove: Color;
    moveNumber: number;
    fullmove: number;
    halfmoveClock: number;
    castling: { wK: boolean; wQ: boolean; bK: boolean; bQ: boolean };
    enPassant: number | null;
    pieces: PublicPiece[];
  };

  clocks: {
    w: number;
    b: number;
    incrementSec: number;
    timeSec: number;
    timerState: PublicTimerState;
  };

  status: {
    phase: SpectatorPhase;
    result: GameResult | null;
    reason: string | null;
  };

  /** Cumulative PUBLIC piece counters. Captured is authoritative from the
   * engine; the spawned/removed/transformed/duplicated lists are reserved for
   * the event-log stage and start empty (never fabricated). */
  pieceEvents: {
    captured: { w: PublicCaptureCounts; b: PublicCaptureCounts };
    spawned: unknown[];
    removed: unknown[];
    transformed: unknown[];
    duplicated: unknown[];
  };

  terrain: {
    blockedSquares: number[];
    portals: number[];
    walls: PublicWall[];
    squareEffects: PublicSquareEffect[];
  };

  activeBuffs: { w: PublicHeldBuff[]; b: PublicHeldBuff[] };
  revealedNerfs: { w: string | null; b: string | null };
  publicCardHistory: unknown[];

  draftTiming: {
    nextDraftAtPly: number | null;
    cadence: number | null;
    offerSeats: { w: boolean; b: boolean };
    diffActive: boolean;
  };

  publicRuleModifiers: {
    activeNerfIds: string[];
    extraMoves: { w: number; b: number };
    skips: { w: number; b: number };
    ruleIds: string[];
  };

  customVictory: {
    timedLoss: { owner: Color; square: number; turns: number }[];
    shortLeash: { owner: Color; turns: number }[];
  };

  animationState: { lastCardPlayId: string | null };

  spectatorDelaySec: number;

  /** The public-state parity hash (see desync.ts publicStateHash). Computed by
   * the caller after projection and assigned here; the projector leaves it "". */
  publicHash: string;
}

/** The squares an effect visibly covers, for the public projection. A side or
 * army wide effect (king safety, a movement lock, a whole-army shield) covers
 * no single square list: it lists the owner's current piece squares for a
 * whole-army shield (all public) and nothing for the purely side-scoped kinds. */
function effectPublicSquares(e: ActiveEffect, board: BoardState): number[] {
  switch (e.kind) {
    case "freeze":
    case "walnut":
    case "timed_loss":
    case "cosmetic":
      return [e.sq];
    case "barred":
    case "strike":
    case "bonk":
      return [...e.squares].sort((a, b) => a - b);
    case "shield": {
      if (e.squares) return [...e.squares].sort((a, b) => a - b);
      // Whole-army shield: project the owner's current piece squares (public).
      const sqs: number[] = [];
      for (let sq = 0; sq < 64; sq++) {
        const p = board.pieces[sq];
        if (p && p.color === e.owner) sqs.push(sq);
      }
      return sqs;
    }
    default:
      return [];
  }
}

/** Owner/against attribution for the public effect projection. */
function effectPublicSides(e: ActiveEffect): { owner?: Color; against?: Color } {
  switch (e.kind) {
    case "freeze":
    case "walnut":
    case "timed_loss":
    case "shield":
    case "king_safe":
    case "nerf_suspended":
    case "strike":
    case "bonk":
    case "short_leash":
    case "cosmetic":
      return { owner: e.owner };
    case "barred":
    case "no_pawn_advance":
    case "king_only":
      return { against: e.against };
  }
}

/**
 * Project the authoritative game plus its public match bits into a
 * PublicSpectatorSnapshot. PURE and read-only: it never mutates the game and
 * never re-implements card logic; it only reads already-resolved state. All
 * hidden info (secret nerf ids, slot rng, unrevealed cards, private offers,
 * delayed-event target identities) is left out by construction. The caller
 * fills `publicHash` via publicStateHash(snap).
 */
export function toPublicSnapshot(game: NerfGame, bits: PublicSnapshotBits): PublicSpectatorSnapshot {
  const board = game.board;
  const bs = game.buffs;

  // Board effects that pin a piece in place (freeze/walnut) or shield it.
  const frozen = new Set<number>();
  const shielded = new Set<number>();
  const squareEffects: PublicSquareEffect[] = [];
  const blockedSquares = new Set<number>();
  const walls: PublicWall[] = [];
  const timedLoss: { owner: Color; square: number; turns: number }[] = [];
  const shortLeash: { owner: Color; turns: number }[] = [];

  if (bs) {
    for (const e of bs.effects) {
      const squares = effectPublicSquares(e, board);
      const sides = effectPublicSides(e);
      squareEffects.push({
        kind: e.kind,
        squares,
        ...(sides.owner ? { owner: sides.owner } : {}),
        ...(sides.against ? { against: sides.against } : {}),
        turns: e.turns == null ? null : e.turns,
      });
      if (e.kind === "freeze" || e.kind === "walnut") frozen.add(e.sq);
      if (e.kind === "shield") for (const sq of squares) shielded.add(sq);
      if (e.kind === "barred") {
        for (const sq of e.squares) blockedSquares.add(sq);
        const wall = wallLine(e.squares);
        if (wall) walls.push({ axis: wall.axis, line: wall.line, against: e.against });
      }
      // Public marker for a trade-off timer: owner + square + remaining turns.
      // The delayed OUTCOME (remove vs demote-into) is a hidden future event and
      // is deliberately not projected.
      if (e.kind === "timed_loss") timedLoss.push({ owner: e.owner, square: e.sq, turns: e.turns });
      if (e.kind === "short_leash") shortLeash.push({ owner: e.owner, turns: e.turns });
    }
  }

  const pieces: PublicPiece[] = [];
  for (let sq = 0; sq < 64; sq++) {
    const p = board.pieces[sq];
    if (!p) continue;
    pieces.push({
      id: squareName(sq),
      color: p.color,
      type: p.type,
      square: sq,
      ...(frozen.has(sq) ? { frozen: true } : {}),
      ...(shielded.has(sq) ? { shielded: true } : {}),
    });
  }

  const heldOf = (color: Color): PublicHeldBuff[] => {
    if (!bs) return [];
    const out: PublicHeldBuff[] = [];
    for (const inst of bs.players[color].buffs) {
      const def = BUFF_BY_ID[inst.id];
      if (!def) continue;
      out.push({
        buffId: inst.id,
        category: String(def.category),
        tier: inst.tier as number,
        kind: def.kind,
        ...(inst.spent ? { spent: true } : {}),
        ...(inst.nullified ? { nullified: true } : {}),
        revealed: true,
      });
    }
    return out;
  };

  // Public rule ids: revealed nerf ids only (never a secret nerf) plus each
  // active board effect kind. Distinct from desync.activeRuleIds, which folds
  // in the raw nerf identities and so cannot be shown to a spectator.
  const ruleIds: string[] = [];
  if (bits.revealedNerfs.w) ruleIds.push(`w:${bits.revealedNerfs.w}`);
  if (bits.revealedNerfs.b) ruleIds.push(`b:${bits.revealedNerfs.b}`);
  if (bs) for (const e of bs.effects) ruleIds.push(`fx:${e.kind}`);
  ruleIds.sort();

  const activeNerfIds: string[] = [];
  if (bits.revealedNerfs.w) activeNerfIds.push(bits.revealedNerfs.w);
  if (bits.revealedNerfs.b) activeNerfIds.push(bits.revealedNerfs.b);

  const offerSeats = bits.offerSeats ?? { w: false, b: false };
  const phase: SpectatorPhase = game.result
    ? "over"
    : bs?.diff
      ? "chessDiff"
      : offerSeats.w || offerSeats.b
        ? "draftPaused"
        : "active";

  return {
    gameId: bits.gameId,
    schemaVersion: PUBLIC_SNAPSHOT_VERSION,
    replayVersion: bits.replayVersion,
    stateRevision: bits.stateRevision,
    lastSeq: bits.lastSeq,
    capturedAtPly: board.history.length,
    capturedAtCursor: bits.cursor,
    capturedAtMs: bits.capturedAtMs,

    mode: bits.mode,
    rated: bits.rated,
    players: bits.players,

    board: {
      dims: { files: 8, ranks: 8 },
      sideToMove: board.turn,
      moveNumber: board.history.length,
      fullmove: board.fullmove,
      halfmoveClock: board.halfmove,
      castling: {
        wK: board.castling.wk,
        wQ: board.castling.wq,
        bK: board.castling.bk,
        bQ: board.castling.bq,
      },
      enPassant: board.epTarget,
      pieces,
    },

    clocks: {
      w: bits.clocks.w,
      b: bits.clocks.b,
      incrementSec: bits.incrementSec,
      timeSec: bits.timeSec,
      timerState: bits.timerState,
    },

    status: {
      phase,
      result: game.result,
      reason: game.result?.reason ?? null,
    },

    pieceEvents: {
      captured: { w: { ...game.captured.w }, b: { ...game.captured.b } },
      spawned: [],
      removed: [],
      transformed: [],
      duplicated: [],
    },

    terrain: {
      blockedSquares: [...blockedSquares].sort((a, b) => a - b),
      portals: [],
      walls,
      squareEffects,
    },

    activeBuffs: { w: heldOf("w"), b: heldOf("b") },
    revealedNerfs: bits.revealedNerfs,
    publicCardHistory: bits.publicCardHistory ?? [],

    draftTiming: {
      nextDraftAtPly: bits.nextDraftAtPly ?? bs?.nextDraftAtPly ?? null,
      cadence: bs?.cadence ?? null,
      offerSeats,
      diffActive: !!bs?.diff,
    },

    publicRuleModifiers: {
      activeNerfIds,
      extraMoves: bs ? { ...bs.extraMoves } : { w: 0, b: 0 },
      skips: bs ? { ...bs.skips } : { w: 0, b: 0 },
      ruleIds,
    },

    customVictory: { timedLoss, shortLeash },

    animationState: { lastCardPlayId: bits.lastCardPlayId ?? null },

    spectatorDelaySec: bits.spectatorDelaySec ?? 0,

    publicHash: "",
  };
}

/** Turn an ordinary game into a draft-mode game. The mode picks the section
 * ruleset: "nerf" (opening nerf pick, nerf-modifier buffs on a slow cadence),
 * "buff" (no nerfs, nerf-modifier buffs excluded), or absent for the legacy
 * merged rules so saved games keep replaying unchanged. */
export function enableDraftMode(
  game: NerfGame,
  seed: number,
  opts?: { mode?: DraftMode; cadence?: number; stackFor?: Color; stackBoost?: number },
) {
  const cadence = opts?.cadence ?? (opts?.mode === "nerf" ? NERF_MODE_CADENCE : DEFAULT_CADENCE);
  game.buffs = newBuffMatchState(seed, cadence, opts?.mode);
  // "Stacked draft" preset: give one seat a persistent tier lift on every
  // offer. Seeded here (not per-offer) so the boost is part of the match's
  // deterministic setup and replays identically. Must be re-applied on every
  // rebuild that recreates game.buffs, exactly like cadence/mode.
  if (opts?.stackFor && opts.stackBoost && opts.stackBoost > 0) {
    game.buffs.players[opts.stackFor].flags.stackBoost = opts.stackBoost;
  }
  // Buff mode's OPENING pick (owner feature): both players are dealt a pair
  // of tiny opener cards before the first move, mirroring the opening nerf
  // pair. Deterministic from the seed above, so every replica and every
  // rebuild deals the identical pairs (replay-safe by construction).
  rollOpenerOffers(game.buffs);
}

export function newGameAsColor(myNerf: Nerf, myColor: Color, mySeed: number): NerfGame {
  const myRng = RNG.fromState(mySeed);
  const opponentRng = new RNG(0);
  const whiteNerf = myColor === "w" ? myNerf : NOOP_NERF;
  const blackNerf = myColor === "b" ? myNerf : NOOP_NERF;
  const whiteRng = myColor === "w" ? myRng : opponentRng;
  const blackRng = myColor === "b" ? myRng : opponentRng;
  const board = initialBoard();
  const white: PlayerSlot = {
    nerf: whiteNerf,
    state: whiteNerf.init ? whiteNerf.init(whiteRng, "w") : {},
    color: "w",
    rng: whiteRng,
  };
  const black: PlayerSlot = {
    nerf: blackNerf,
    state: blackNerf.init ? blackNerf.init(blackRng, "b") : {},
    color: "b",
    rng: blackRng,
  };
  const game: NerfGame = {
    board,
    white,
    black,
    result: null,
    startedAt: Date.now(),
    captured: { w: emptyCounts(), b: emptyCounts() },
  };
  applyTurnStart(game);
  return game;
}

export function makeContext(game: NerfGame, color: Color): GameContext {
  const me = color === "w" ? game.white : game.black;
  const opp = color === "w" ? game.black : game.white;
  // count moves I've made
  const moveNumber = game.board.history.filter((m) => m.color === color).length;
  const myLast = [...game.board.history].reverse().find((m) => m.color === color) ?? null;
  const oppLast = [...game.board.history].reverse().find((m) => m.color !== color) ?? null;
  return {
    board: game.board,
    me: color,
    opponentLastMove: oppLast,
    myLastMove: myLast,
    moveNumber,
    capturedByMe: game.captured[color],
    capturedFromMe: game.captured[color === "w" ? "b" : "w"],
  };
}

export function applyTurnStart(game: NerfGame) {
  // Chess Diff sub-game: nerfs are fully suspended — plain chess only.
  if (game.buffs?.diff) return;
  const slot = game.board.turn === "w" ? game.white : game.black;
  if (slot.nerf.onTurnStart) {
    const ctx = makeContext(game, slot.color);
    slot.state = slot.nerf.onTurnStart(slot.state, ctx, slot.rng);
  }
}

// ---------------------------------------------------------------------------
// Buff system (draft mode)
// ---------------------------------------------------------------------------

function effectActive(e: ActiveEffect): boolean {
  return e.turns == null || e.turns > 0;
}

/** Freeze and walnut bind to the piece standing on their square. Once that
 * piece is gone (captured, or removed/relocated by another buff) the effect
 * must go with it: a walnut or freeze marker can never linger on an empty
 * square or transfer onto a capturing enemy piece. Called after every move and
 * after every buff-driven board mutation. */
function pruneOrphanedSquareEffects(game: NerfGame) {
  const bs = game.buffs;
  if (!bs) return;
  bs.effects = bs.effects.filter((e) => {
    if (e.kind === "freeze" || e.kind === "walnut" || e.kind === "timed_loss" || e.kind === "cosmetic") {
      // A trade-off timer whose piece was captured (or otherwise vanished)
      // before it expired has nothing left to reclaim: drop it like a freeze.
      const p = game.board.pieces[e.sq];
      return !!p && p.color === e.owner;
    }
    // A square-list shield only protects pieces standing on its squares. When
    // a shielded piece moves away (without the shield-follow keeping up, e.g.
    // a buff relocated or removed it) or is captured, its square must drop
    // from the list, or the shield would later protect whatever owner piece
    // next steps onto that square. A whole-army shield (squares null) is
    // unbounded and never pruned; a shield whose list empties is gone.
    if (e.kind === "shield" && e.squares) {
      e.squares = e.squares.filter((sq) => {
        const p = game.board.pieces[sq];
        return !!p && p.color === e.owner;
      });
      return e.squares.length > 0;
    }
    return true;
  });
}

/** Fire trade-off timers (timed_loss) that have counted down to zero: the owner
 * pays the delayed price on their tracked piece before the expired effect is
 * filtered out. The piece is either removed or reverted to another type (a
 * temporary grant taken back). Never touches a king, and the loss is uncounted:
 * the piece is reclaimed by its own owner's bargain, not captured by the
 * opponent, so revive pools and material counters stay truthful. */
function fireExpiredTradeOffs(game: NerfGame) {
  const bs = game.buffs;
  if (!bs) return;
  for (const e of bs.effects) {
    if (e.kind !== "timed_loss" || e.turns == null || e.turns > 0) continue;
    const p = game.board.pieces[e.sq];
    if (!p || p.color !== e.owner || p.type === "k") continue;
    bs.historyDiverged = true;
    bs.mutations = (bs.mutations ?? 0) + 1;
    if (e.then === "demote" && e.into && e.into !== "k") {
      game.board.pieces[e.sq] = { ...p, type: e.into };
    } else {
      game.board.pieces[e.sq] = null;
    }
  }
}

/** True while a nerf is suspended (Grace Period) or removed (Nerf Breaker). */
export function nerfDisabled(game: NerfGame, color: Color): boolean {
  const bs = game.buffs;
  if (!bs) return false;
  if (bs.players[color].nerfRemoved) return true;
  return bs.effects.some(
    (e) => e.kind === "nerf_suspended" && e.owner === color && effectActive(e),
  );
}

/**
 * The RNG behind api.rng: buff-effect randomness (The Culling's victims, chaos
 * scatters, the Jackpot / apex grants...). Seeded STATELESSLY from public,
 * byte-identically-synced state — the ply count, the 64-square board signature,
 * and the acting color — never from any per-client secret.
 *
 * Why not slot.rng (the per-player nerf RNG, used here historically): that
 * stream only exists on the server. A client replica builds the OPPONENT's slot
 * as RNG(0) (their nerf seed is hidden) and a spectator replica seeds both
 * slots with a dummy, so any card effect that rolled on slot.rng removed
 * DIFFERENT pieces on every replica — the root cause of the "crazy powerup
 * desyncs the game" reports. Every replica does share the board and the move /
 * public-action record, so a seed derived purely from those replays the same
 * draws everywhere: server, both clients, spectators, arena replays, snapshot
 * restores.
 *
 * Stateless-per-event is deliberate (no persistent fx stream in
 * BuffMatchState): a hidden card whose hook draws but does nothing observable
 * never shifts anyone else's future draws, so replicas can never drift apart —
 * each event reseeds from state they all agree on. Within one event (one
 * makeBuffApi lifetime) successive draws walk one Mulberry32 stream, so
 * multi-draw effects stay properly varied. The board signature is taken at api
 * creation, which every apply path does per event (activation, hook loop,
 * instant pick), so two same-ply events by the same color are still separated
 * by the board change the first one made.
 */
function fxRng(game: NerfGame, me: Color): RNG {
  let seed = boardSignature(game.board);
  seed = Math.imul(seed ^ (game.board.history.length + 1), 0x9e3779b1);
  seed = Math.imul(seed ^ (me === "w" ? 0x517cc1b7 : 0x27220a95), 0x85ebca6b);
  // Also mix a digest of the public card state. Board+ply alone repeated
  // seeds byte-for-byte when two casts landed at the same position with no
  // board change between them — e.g. two Wheel of Fortune instants picked
  // back-to-back whose first wedge only touched the clock rolled the SAME
  // wedge every time ("I got +55 seconds five spins in a row"). Held-card
  // counts, spent/used flags, effect count, rerolls, and the mutation
  // counter all advance between such casts, are part of the byte-identical
  // synced state on every replica, and never leak a hidden card (counts
  // only, no identities).
  const bs = game.buffs;
  if (bs) {
    let d = (bs.mutations ?? 0) ^ ((bs.effects.length + 1) << 8);
    for (const c of ["w", "b"] as Color[]) {
      const ps = bs.players[c];
      let spent = 0;
      let used = 0;
      for (const b of ps.buffs) {
        if (b.spent) spent++;
        if (b.usedActivation) used++;
      }
      d = Math.imul(d ^ (ps.buffs.length + 1), 0x9e3779b1);
      d = Math.imul(d ^ (spent * 31 + used * 131 + ps.rerollsLeft * 7 + 1), 0x85ebca6b);
    }
    seed = Math.imul(seed ^ d, 0xc2b2ae35);
  }
  return new RNG(seed >>> 0);
}

export function makeBuffApi(game: NerfGame, me: Color): BuffApi {
  const bs = game.buffs!;
  const opp: Color = me === "w" ? "b" : "w";
  const slot = me === "w" ? game.white : game.black;
  // Every direct board mutation bumps the transient counter so apply paths
  // (playMove's hook loop, the game server's pick handling) can tell whether
  // a hook or init observably changed the board. Only counted when the board
  // actually changes, so a refused relocation or a no-op removal never
  // reveals a card that did nothing visible.
  const mutated = () => {
    bs.mutations = (bs.mutations ?? 0) + 1;
  };
  return {
    board: game.board,
    me,
    opp,
    bs,
    mine: bs.players[me],
    theirs: bs.players[opp],
    rng: fxRng(game, me),
    capturedFromMe: game.captured[opp],
    capturedByMe: game.captured[me],
    place: (sq, type, color) => {
      bs.historyDiverged = true;
      mutated();
      game.board.pieces[sq] = { type, color };
    },
    removePiece: (sq, opts) => {
      const p = game.board.pieces[sq];
      if (!p) return;
      bs.historyDiverged = true;
      mutated();
      game.board.pieces[sq] = null;
      // A piece destroyed by a buff is a real loss: count it as captured by
      // the other side so material counters and the owner's revivable pool
      // (Resurrect and friends) stay truthful. Kings are never removed by
      // buffs; the guard is a backstop. Whole-board rewrites (Perfect
      // Rewind, Genesis) and effect-expiry removals of summoned pieces pass
      // `uncounted` instead: those pieces were never lost to the opponent,
      // so counting them would corrupt the revive pools and any
      // capturedFromMe-based nerf conditions.
      if (p && p.type !== "k" && !opts?.uncounted) {
        game.captured[p.color === "w" ? "b" : "w"][p.type] += 1;
      }
    },
    relocate: (from, to) => {
      const p = game.board.pieces[from];
      // Nothing to relocate: bail before the write below could null out a
      // piece already standing on `to`.
      if (!p) return;
      // Anchor: an enemy piece bound by its owner's Anchor buff cannot be
      // pushed or swapped by my buffs (its own moves are unaffected).
      if (
        p &&
        p.color !== me &&
        bs.players[p.color].buffs.some(
          (b) => b.id === "anchor" && !b.spent && !b.nullified && b.state.sq === from,
        )
      ) {
        return;
      }
      // Pawns can never stand on rank 1 or rank 8: refuse the relocation
      // outright, whatever card asked for it (cards filter their destination
      // zones too; this is the backstop).
      if (p?.type === "p" && !pawnRankOk(to)) {
        return;
      }
      bs.historyDiverged = true;
      mutated();
      game.board.pieces[from] = null;
      game.board.pieces[to] = p;
    },
    setPieceType: (sq, type) => {
      bs.historyDiverged = true;
      const p = game.board.pieces[sq];
      if (p) {
        mutated();
        game.board.pieces[sq] = { ...p, type };
      }
    },
    setPieceColor: (sq, color) => {
      bs.historyDiverged = true;
      const p = game.board.pieces[sq];
      if (p) {
        mutated();
        game.board.pieces[sq] = { ...p, color };
      }
    },
    restoreCastling: () => {
      const homeR = me === "w" ? 0 : 7;
      const king = game.board.pieces[SQ(4, homeR)];
      if (!king || king.type !== "k" || king.color !== me) return;
      const kingside = game.board.pieces[SQ(7, homeR)];
      const queenside = game.board.pieces[SQ(0, homeR)];
      if (kingside?.type === "r" && kingside.color === me) {
        if (me === "w") game.board.castling.wk = true;
        else game.board.castling.bk = true;
      }
      if (queenside?.type === "r" && queenside.color === me) {
        if (me === "w") game.board.castling.wq = true;
        else game.board.castling.bq = true;
      }
    },
    removeMyNerf: () => {
      slot.nerf = FREED_NERF;
      slot.state = {};
      bs.players[me].nerfRemoved = true;
    },
    adjustClock: (req) => {
      (bs.clockFx ??= []).push({ caster: me, ...req });
    },
  };
}

/**
 * Squares `color` can strike through BUFF-granted augmented moves (a rook that
 * also steps diagonally, a camel knight, an amazon, the king's extended reach,
 * ...). Runs exactly the augmentMoves hooks legalMoves uses, but on a read-only
 * clone of the board with `color` to move, then returns only the target squares
 * of the moves those hooks ADDED beyond standard movement. Pure: it clones the
 * board and never mutates the live board, effects, or the draft RNG (augment
 * generators only read the board), so it is safe to call from anywhere and can
 * never desync. Feeds board.ts's attack test so a king attacked solely by an
 * augmented enemy piece is still detected (see gameInCheck / isInCheck).
 */
export function buffAugmentedAttacks(game: NerfGame, color: Color): Square[] {
  const bs = game.buffs;
  if (!bs || bs.diff) return [];
  const held = heldBuffs(game, color);
  if (held.length === 0) return [];
  const board = cloneBoard(game.board);
  board.turn = color;
  const view: NerfGame = { ...game, board };
  const api = makeBuffApi(view, color);
  const base = generateMoves(board);
  const augmented = base.slice();
  for (const { inst, def } of held) def.augmentMoves?.(augmented, inst, api);
  const squares: Square[] = [];
  for (let i = base.length; i < augmented.length; i++) squares.push(augmented[i].to);
  return squares;
}

/** Check detection that also honors buff-granted augmented moves: a king
 * attacked only via an augmented enemy piece is flagged in check, which plain
 * board.ts isInCheck (standard movement only) misses. Use this wherever game
 * (buff) context is available. */
export function gameInCheck(game: NerfGame, color: Color): boolean {
  const opp: Color = color === "w" ? "b" : "w";
  return isInCheck(game.board, color, buffAugmentedAttacks(game, opp));
}

function heldBuffs(game: NerfGame, color: Color): { inst: BuffInstance; def: Buff }[] {
  const bs = game.buffs;
  if (!bs) return [];
  return bs.players[color].buffs
    .filter((b) => !b.spent && !b.nullified)
    .map((inst) => ({ inst, def: BUFF_BY_ID[inst.id] }))
    .filter((x): x is { inst: BuffInstance; def: Buff } => !!x.def);
}

/** A barred effect whose squares form exactly one complete file or rank is a
 * board-splitting WALL, not just a no-landing zone (Fault Line, Great Wall,
 * Great Divide, Sundering, and the whole-file / whole-rank hexes all build one
 * such line per pick). Blocking only the landing square lets a piece jump the
 * wall: a knight leaps clean over the barred squares, and a slider glides
 * through the empty ones. Detecting this shape lets legalMoves also reject any
 * move that CROSSES the line. Returns the wall's axis and line index, or null
 * for partial barred zones (Bunker, the Kraken 3x3 seal, a multi-rank scorched
 * band) which only block landing. A thick band (two or more adjacent ranks or
 * files) needs no crossing rule: a knight cannot leap a two-wide barrier, so
 * its landing square always falls inside the band and the landing filter alone
 * stops it. */
function wallLine(squares: Square[]): { axis: "file" | "rank"; line: number } | null {
  if (squares.length !== 8) return null;
  const f0 = FILE(squares[0]);
  if (squares.every((s) => FILE(s) === f0) && new Set(squares.map((s) => RANK(s))).size === 8) {
    return { axis: "file", line: f0 };
  }
  const r0 = RANK(squares[0]);
  if (squares.every((s) => RANK(s) === r0) && new Set(squares.map((s) => FILE(s))).size === 8) {
    return { axis: "rank", line: r0 };
  }
  return null;
}

export function legalMoves(game: NerfGame): Move[] {
  if (game.result) return [];
  let all = generateMoves(game.board);
  // Chess Diff sub-game: a plain game of chess under STANDARD rules. No nerf
  // filters, no buff augments, no zone effects (stashed empty anyway), and no
  // pocket drops - but, unlike the rest of the site (decided by king capture),
  // you may not leave your own king in check. Filter the pseudo-legal moves
  // down to the ones that keep the mover's king safe, so the diff is won by
  // checkmate and drawn by stalemate (see resolveNoMoves), never by a king
  // walking into capture.
  if (game.buffs?.diff) {
    const mover = game.board.turn;
    const opp: Color = mover === "w" ? "b" : "w";
    // Opponent's attack map on the pre-move board, reused for the castling test.
    const attacked = attackedBy(game.board, opp);
    return all.filter((m) => {
      if (m.castle) {
        // Standard castling: the king may not castle out of, through, or into
        // check, so all three king-path squares (from, transit, destination)
        // must be unattacked. generateMoves deliberately allows nerf-chess
        // castling through check, so the diff has to re-impose the real rule.
        const transit = m.castle === "k" ? SQ(5, RANK(m.from)) : SQ(3, RANK(m.from));
        return !attacked.has(m.from) && !attacked.has(transit) && !attacked.has(m.to);
      }
      // Any other move is legal iff it does not leave the mover's king in check.
      return !isInCheck(makeMove(game.board, m), mover);
    });
  }
  const me = game.board.turn;
  const opp: Color = me === "w" ? "b" : "w";
  const slot = me === "w" ? game.white : game.black;
  const bs = game.buffs;
  let frozenOwnCount = 0;

  if (bs) {
    // Frozen pieces cannot move at all. Walnuts are a lighter, distinct
    // lockdown: a heavy nut can still shuffle ONE square (a king-step), so it
    // plays differently from a freeze instead of being a reskin of it.
    const frozen = new Set(
      bs.effects
        .filter((e) => e.kind === "freeze" && e.owner === me && effectActive(e))
        .map((e) => (e.kind === "freeze" ? e.sq : -1)),
    );
    const walnut = new Set(
      bs.effects
        .filter((e) => e.kind === "walnut" && e.owner === me && effectActive(e))
        .map((e) => (e.kind === "walnut" ? e.sq : -1)),
    );
    frozenOwnCount = frozen.size + walnut.size;
    if (frozen.size) all = all.filter((m) => !frozen.has(m.from));
    if (walnut.size)
      all = all.filter(
        (m) =>
          !walnut.has(m.from) ||
          (Math.abs(FILE(m.to) - FILE(m.from)) <= 1 && Math.abs(RANK(m.to) - RANK(m.from)) <= 1),
      );

    // My buffs may add moves. Nerf constraints are applied afterwards, so a
    // handicap still governs buff-granted movement.
    const api = makeBuffApi(game, me);
    for (const { inst, def } of heldBuffs(game, me)) {
      def.augmentMoves?.(all, inst, api);
    }
  }

  if (slot.nerf.filterMoves && !nerfDisabled(game, me)) {
    const ctx = makeContext(game, slot.color);
    const beforeNerf = all;
    const filtered = slot.nerf.filterMoves(all, slot.state, ctx);
    // Safety net: a move-restriction nerf must never zero out the mover's
    // options. That is a self-stalemate / soft-lock, not an intended loss
    // (loss conditions run separately via checkLoss). The rule harness only
    // probes each nerf from the opening, so nerfs that empty the list in a
    // mid or endgame position (statue_king, no_mans_land, scorched_earth,
    // the no-backward family, etc.) slipped through. If a nerf empties the
    // list while legal moves existed, relax it for this one turn. Every such
    // nerf still shapes play on every turn where at least one legal move
    // survives its filter, which is nearly all of them.
    all = filtered.length > 0 ? filtered : beforeNerf;
  }

  if (bs) {
    // Opponent protections and zone effects restrict my options.
    for (const e of bs.effects) {
      if (!effectActive(e)) continue;
      switch (e.kind) {
        case "shield":
          if (e.owner === opp) {
            all = all.filter((m) => {
              const cap = m.capturedSquare ?? (m.captured ? m.to : null);
              if (cap == null) return true;
              // A shield never protects the king itself. King invulnerability
              // is exclusively king_safe / Immortal King (documented, and it
              // carries a drawback). Without this, a permanent square shield
              // parked on the king (Sanctuary) or a whole-army shield would
              // make the king uncapturable forever and the game unwinnable.
              if (game.board.pieces[cap]?.type === "k") return true;
              return e.squares ? !e.squares.includes(cap) : false;
            });
          }
          break;
        case "barred": {
          // A wall never seals the king away from capture. Winning is king
          // capture (there is no checkmate), so a permanent barred file or rank
          // sitting over the enemy king would otherwise soft-lock the game as
          // unwinnable (the Sundering / Great Divide / Fissure trap). A move
          // that captures the king ignores the wall; every other move into a
          // barred square is still blocked.
          if (e.against === me) {
            all = all.filter((m) => m.captured === "k" || !e.squares.includes(m.to));
            // Board-split walls (a full barred file or rank) must also block any
            // move that CROSSES the line, not merely one that lands on it: a
            // knight leaps over the barred squares and a slider glides through
            // the empty ones, so the landing filter above lets both jump the
            // wall. Reject moves whose from/to sit on opposite sides of the
            // line. King captures stay exempt (same unwinnability guard as
            // above). Non-soft-lock: never strand the mover. If blocking
            // crossings would empty the list (every remaining piece is across
            // the wall from where it must go), relax this wall for the turn so
            // the mover keeps its moves on its own side.
            const wall = wallLine(e.squares);
            if (wall) {
              const side = (sq: Square) =>
                (wall.axis === "file" ? FILE(sq) : RANK(sq)) - wall.line;
              const kept = all.filter(
                (m) => m.captured === "k" || side(m.from) * side(m.to) >= 0,
              );
              if (kept.length > 0) all = kept;
            }
          }
          break;
        }
        case "king_safe":
          if (e.owner === opp) all = all.filter((m) => m.captured !== "k");
          break;
        case "no_pawn_advance":
          if (e.against === me) {
            all = all.filter((m) => !(m.piece === "p" && FILE(m.from) === FILE(m.to)));
          }
          break;
        case "king_only":
          if (e.against === me) all = all.filter((m) => m.piece === "k");
          break;
        case "short_leash":
          // Berserker's hangover: the owner may only step one square (king
          // distance) with any piece. King captures stay exempt so the game
          // is always winnable, and if the leash would strand the mover with
          // no move it is relaxed for the turn rather than soft-locking.
          if (e.owner === me) {
            const kept = all.filter(
              (m) =>
                m.captured === "k" ||
                Math.max(Math.abs(FILE(m.to) - FILE(m.from)), Math.abs(RANK(m.to) - RANK(m.from))) <= 1,
            );
            if (kept.length > 0) all = kept;
          }
          break;
      }
    }
    const oppApi = makeBuffApi(game, opp);
    for (const { inst, def } of heldBuffs(game, opp)) {
      if (def.filterOpponentMoves) all = def.filterOpponentMoves(all, inst, oppApi);
    }
    // Chained-move king guard: while a player is bursting through extra
    // moves or opponent skips, capturing the king is off the table until the
    // opponent has played one reply move. The final chained move may still
    // give check or create threats; it just cannot end the game on the spot.
    if (bs.chainKingGuard === me || bs.extraMoves[me] > 0 || bs.skips[opp] > 0) {
      all = all.filter((m) => m.captured !== "k");
    }
    // Invulnerability must not also deliver the win. A piece that cannot be
    // captured this turn (shielded by my own shield, or my king under a
    // king_safe ward) may not be the one to capture the enemy king: an
    // untouchable attacker would be a riskless, uncounterable finish, which is
    // exactly the "too strong" case. You have to expose a piece to end the
    // game. Any capturable piece may still take the king, so the position is
    // never made unwinnable; the guard below relaxes if it would empty the list.
    {
      const myShieldZones = bs.effects
        .filter((e) => e.kind === "shield" && e.owner === me && effectActive(e))
        .map((e) => (e.kind === "shield" ? e.squares : null));
      const myKingSafe = bs.effects.some(
        (e) => e.kind === "king_safe" && e.owner === me && effectActive(e),
      );
      if (myShieldZones.length > 0 || myKingSafe) {
        const untouchable = (sq: Square) =>
          myShieldZones.some((squares) => (squares ? squares.includes(sq) : true)) ||
          (myKingSafe && game.board.pieces[sq]?.type === "k");
        const guarded = all.filter((m) => m.captured !== "k" || !untouchable(m.from));
        if (guarded.length > 0) all = guarded;
      }
    }
    // Panic step: while mass freeze (3 or more of my pieces frozen) is
    // active, my king keeps its plain one-square quiet steps regardless of
    // zone effects, so a freeze plus extra-move stack can never leave a side
    // with no meaningful reply.
    if (frozenOwnCount >= 3) {
      for (const m of generateMoves(game.board)) {
        if (m.piece !== "k" || m.captured) continue;
        if (Math.abs(FILE(m.to) - FILE(m.from)) > 1 || Math.abs(RANK(m.to) - RANK(m.from)) > 1) {
          continue;
        }
        if (!all.some((x) => x.from === m.from && x.to === m.to)) all.push(m);
      }
    }

    // Crazyhouse-style inventory drops. Purely ADDITIVE and appended last, after
    // every nerf/effect filter and relax rule, so a drop never displaces a piece
    // move nor gets swept up by the "relax when the list would empty" guards: a
    // player who can only drop is still not stalemated (drops count as legal
    // moves in resolveNoMoves). A drop lands on an EMPTY square only, so it can
    // never capture anything (the enemy king included), which is exactly why the
    // chainKingGuard / shield king-capture guards above leave drops untouched.
    // Pawns may never be dropped onto rank 1 or 8, and a king is never in a
    // pocket.
    const inv = bs.players[me].inventory;
    if (inv) {
      for (const key of Object.keys(inv) as PieceType[]) {
        const count = inv[key] ?? 0;
        if (count <= 0 || key === "k") continue;
        for (let sq = 0; sq < 64; sq++) {
          if (game.board.pieces[sq]) continue;
          if (key === "p" && !pawnRankOk(sq)) continue;
          all.push({ from: sq, to: sq, piece: key, color: me, drop: key });
        }
      }
    }
  }
  return all;
}

// ---------------------------------------------------------------------------
// Chess Diff sub-game (see ChessDiffState in buff.ts and the card in
// buffs/library.ts). While bs.diff is set the game is a plain 1+0 game of
// chess: no drafts roll, no nerfs filter, no buffs augment or activate, and
// board effects are stashed away. The functions below decide the diff and
// resume the paused game.
// ---------------------------------------------------------------------------

/** Decide the running Chess Diff: restore the paused game's board (keeping
 * the full, continuous move history so ply counters never drift), effects and
 * tempo counters, and hand ONLY the diff's winner a guaranteed apex (tier 9)
 * (tier 10) card. A drawn diff grants nobody anything. Deterministic: every
 * replica reaches this through the same move/action record. */
function endChessDiff(game: NerfGame, winner: Color | "draw") {
  const bs = game.buffs;
  const diff = bs?.diff;
  if (!bs || !diff) return;
  // The move record keeps counting through the diff, so the restored board
  // carries the live (pre-diff + diff) history, not the stale stashed one.
  const fullHistory = game.board.history;
  // How many plies the sub-game added: the live history minus the pre-diff
  // snapshot stashed on the saved board. Read before the saved board is
  // re-adopted below (after which savedBoard.history IS fullHistory).
  const diffPlies = fullHistory.length - diff.savedBoard.history.length;
  game.board = diff.savedBoard;
  game.board.history = fullHistory;
  bs.effects = diff.savedEffects;
  bs.extraMoves = diff.savedExtraMoves;
  bs.skips = diff.savedSkips;
  bs.chainKingGuard = diff.savedChainKingGuard;
  bs.diff = undefined;
  // The buff-draft cadence is frozen for the whole diff (no drafts run during
  // it), but the diff's own plies still inflate the shared history. Shift the
  // draft threshold forward by exactly those plies so the resumed game keeps
  // its pre-diff distance to the next draft, instead of firing a backlog of
  // offers, one per move, until the frozen counter catches up to the now
  // longer history.
  if (bs.nextDraftAtPly != null && diffPlies > 0) {
    bs.nextDraftAtPly += diffPlies;
  }
  // The board was rewritten twice (into and out of the diff): history can no
  // longer reproduce it, so replay-based checks stay off.
  bs.historyDiverged = true;
  if (winner !== "draw") {
    // Balance pass: the diff's prize is a guaranteed APEX (tier 9) card, one
    // band below the mythic it used to pay out.
    grantGuaranteedTier9(makeBuffApi(game, winner));
  }
  // Resume the paused game exactly like a turn handover: the restored mover's
  // nerf turn-start runs, and a lockdown that was pending when the game
  // paused still force-passes rather than soft-locking.
  applyTurnStart(game);
  resolveNoMoves(game);
}

/** A player flagged (ran out of the diff's 1+0 clock) during a Chess Diff:
 * the other side wins the diff and the paused game resumes. Recorded by the
 * game server as a draft action so every replica replays the same outcome. */
export function resolveDiffFlag(game: NerfGame, flagged: Color) {
  if (!game.buffs?.diff || game.result) return;
  endChessDiff(game, flagged === "w" ? "b" : "w");
}

export function checkLossConditions(game: NerfGame): GameResult | null {
  // King capture check first. The FIRST king captured ends the game on the
  // spot: the capturer wins, full stop, even if their own king was hanging
  // (owner rule: "when you capture the king it's game, no more other stuff").
  // The former mutual-capture draw was removed under REPLAY_VERSION 9. The
  // both-kings-gone edge (a board wipe that somehow cleared both) stays a
  // draw as the only sane reading of an empty throne room.
  const captured = kingCaptured(game.board);
  if (captured) {
    const winner: Color = captured === "w" ? "b" : "w";
    if (findKing(game.board, winner) == null) {
      return { winner: "draw", reason: "both kings gone" };
    }
    return { winner, reason: "king captured" };
  }
  // Chess Diff sub-game: nerf loss conditions are suspended with the nerfs
  // themselves — only king capture decides the diff.
  if (game.buffs?.diff) return null;
  for (const color of ["w", "b"] as Color[]) {
    const slot = color === "w" ? game.white : game.black;
    if (!slot.nerf.checkLoss || nerfDisabled(game, color)) continue;
    const ctx = makeContext(game, color);
    const res = slot.nerf.checkLoss(slot.state, ctx);
    if (res) {
      return { winner: color === "w" ? "b" : "w", reason: `${slot.nerf.name}: ${res.reason}` };
    }
  }
  return null;
}

/** Apply a crazyhouse-style inventory drop onto a fresh board copy: place the
 * dropped piece on the (empty) target square, clear any stale en passant, hand
 * the turn to the opponent, and record the move in history so the ply count and
 * the move stream stay in lockstep with normal moves. The board is mutated
 * outside makeMove (a drop's origin square is empty, so a history replay through
 * makeMove could not reproduce it), so playMove sets bs.historyDiverged. */
function applyDrop(board: BoardState, move: Move): BoardState {
  const nb = cloneBoard(board);
  nb.pieces[move.to] = { type: move.drop!, color: move.color };
  nb.epTarget = null;
  nb.turn = move.color === "w" ? "b" : "w";
  if (move.color === "b") nb.fullmove++;
  // A drop is neither a pawn push nor a capture; it counts toward the fifty-move
  // clock like any other quiet move.
  nb.halfmove = nb.halfmove + 1;
  nb.history.push(move);
  return nb;
}

/** A cheap fingerprint of the 64 board squares (piece type + color per square,
 * position implicit in the loop order). The onMovePlayed reveal-detection uses
 * it to notice ANY board change a hook makes, including a direct `pieces[]`
 * write that never went through the BuffApi (only the BuffApi bumps
 * bs.mutations). A hook that removes, summons, or moves a piece MUST be revealed
 * to replicas, or they cannot replay the mutation and the boards desync
 * permanently (dtState never carries the board). Keying the detection on this
 * signature instead of trusting every hook to route through the api closes that
 * gap systemically, so no removal (or any board mutation) inside a hook can be
 * skipped by the reveal. */
function boardSignature(board: BoardState): number {
  let h = 2166136261;
  for (let sq = 0; sq < 64; sq++) {
    const p = board.pieces[sq];
    const code = p ? (p.color === "w" ? 1 : 7) + "pnbrqk".indexOf(p.type) : 0;
    h = Math.imul(h ^ code, 16777619);
  }
  return h >>> 0;
}

export function playMove(game: NerfGame, move: Move): NerfGame {
  if (game.result) return game;
  let nextBoard: BoardState;
  if (move.drop) {
    nextBoard = applyDrop(game.board, move);
  } else {
    nextBoard = makeMove(game.board, move);
    // makeMove refused the move (empty origin square or the self-capture
    // backstop): treat the whole ply as a no-op. Counting the capture or
    // ticking effect timers against a board that did not change would desync
    // the capture pools (revives) and effect clocks from the board itself.
    if (nextBoard === game.board) return game;
  }
  if (move.captured) {
    game.captured[move.color][move.captured] += 1;
  }
  game.board = nextBoard;
  const bs = game.buffs;
  if (move.drop && bs) {
    // The board changed outside history-replayable makeMove: suspend the
    // replay-based repetition check and spend one piece from the pocket. Bump
    // mutations so apply paths see the direct board change, exactly like the
    // BuffApi's place()/removePiece() do. Both clients replay the same drop
    // move from the shared move stream, so the pocket stays in lockstep; the
    // synced inventory (draftStateFor / mergeDraftState) is the safety net.
    bs.historyDiverged = true;
    bs.mutations = (bs.mutations ?? 0) + 1;
    const pocket = bs.players[move.color].inventory;
    if (pocket && (pocket[move.drop] ?? 0) > 0) {
      pocket[move.drop] = (pocket[move.drop] ?? 0) - 1;
      if ((pocket[move.drop] ?? 0) <= 0) delete pocket[move.drop];
    }
  }
  if (bs) {
    // A reply move from the other side lifts the chained-move king guard.
    if (bs.chainKingGuard && bs.chainKingGuard !== move.color) bs.chainKingGuard = undefined;
    // Buff bookkeeping: piece tracking, charge consumption, timed passives.
    // Record which hooks observably fired (a board mutation or a new board
    // effect): the game server reveals those cards to the table, because a
    // replica that does not know a card's identity cannot replay its hook,
    // and a skipped board mutation is a permanent desync. State-only changes
    // (charge counters) stay private; dtState frames resync those.
    const fired: { color: Color; index: number }[] = [];
    // Chess Diff sub-game: held buffs are dormant — their hooks reference the
    // paused board and must not fire on diff moves.
    for (const color of bs.diff ? [] : (["w", "b"] as Color[])) {
      const api = makeBuffApi(game, color);
      for (const { inst, def } of heldBuffs(game, color)) {
        if (!def.onMovePlayed) continue;
        const effectsBefore = bs.effects.length;
        const mutationsBefore = bs.mutations ?? 0;
        const clockFxBefore = bs.clockFx?.length ?? 0;
        const sigBefore = boardSignature(game.board);
        def.onMovePlayed(inst, move, api);
        // Reveal the card to replicas when its hook did anything observable: a
        // new/removed board effect, a BuffApi mutation-counter bump, a raw
        // board change the signature catches (a direct pieces[] write that never
        // touched the counter), OR a clock adjustment. The signature is the
        // systemic backstop that guarantees no removal (or any board mutation)
        // inside a hook can be skipped by the reveal, which would desync the
        // replica's board. Clock requests are already visible on the clock UI
        // the moment the server applies them, so revealing the card that made
        // one leaks nothing new — and it is what lets the client fire the
        // card's play art on every tick (a virus drain that changed the clock
        // but showed nothing on the board used to play no animation at all).
        if (
          bs.effects.length !== effectsBefore ||
          (bs.mutations ?? 0) !== mutationsBefore ||
          (bs.clockFx?.length ?? 0) !== clockFxBefore ||
          boardSignature(game.board) !== sigBefore
        ) {
          fired.push({ color, index: bs.players[color].buffs.indexOf(inst) });
        }
      }
    }
    bs.lastHookMutations = fired.length > 0 ? fired : undefined;
    // Shielded squares follow the shielded piece when its owner moves it.
    for (const e of bs.effects) {
      if (e.kind === "shield" && e.squares && move.color === e.owner) {
        const idx = e.squares.indexOf(move.from);
        if (idx >= 0) e.squares[idx] = move.to;
      }
      // A trade-off timer tracks its piece the same way, so the delayed loss
      // still lands on the right square after the piece moves.
      if (e.kind === "timed_loss" && e.owner === move.color && e.sq === move.from) {
        e.sq = move.to;
      }
      // A cosmetic dressing rides its piece (a giant pawn stays giant when it
      // advances). Pure visual: nothing else in the pipeline reads it.
      if (e.kind === "cosmetic" && e.owner === move.color && e.sq === move.from) {
        e.sq = move.to;
      }
    }
    // Tick down effects whose timer runs on the mover's turns.
    for (const e of bs.effects) {
      if (e.turns != null && effectTickColor(e) === move.color) e.turns -= 1;
    }
    // Pay any trade-off timer that just reached zero before it is filtered out.
    fireExpiredTradeOffs(game);
    bs.effects = bs.effects.filter((e) => e.turns == null || e.turns > 0);
    // A captured or buff-removed piece leaves its freeze/walnut behind; drop
    // those orphaned markers so they never haunt an empty or enemy-held square.
    pruneOrphanedSquareEffects(game);
  }
  // Check loss conditions
  const result = checkLossConditions(game);
  if (result) {
    // Chess Diff sub-game: a decided diff ends the DIFF, never the match. The
    // winner takes the apex prize (a mutual king capture is a drawn diff: nobody
    // does), the paused game resumes, and play continues.
    if (bs?.diff) {
      endChessDiff(game, result.winner === "draw" || result.winner == null ? "draw" : result.winner);
      return game;
    }
    game.result = result;
    return game;
  }
  // Standard draw rules: fifty moves without a capture or pawn move, and
  // threefold repetition of the same position with the same side to move.
  // These run inside playMove so every consumer (AI games, the multiplayer
  // worker, and client-side replays of server move lists) agrees on when a
  // game is drawn.
  if (game.board.halfmove >= 100) {
    // Fifty quiet moves inside a Chess Diff draw the DIFF (its halfmove clock
    // started at zero), not the match.
    if (bs?.diff) {
      endChessDiff(game, "draw");
      return game;
    }
    game.result = { winner: "draw", reason: "draw by the fifty-move rule" };
    return game;
  }
  // A repetition needs at least 8 reversible plies, so skip the history
  // replay until then. Once a buff has mutated the board directly the replay
  // no longer reproduces the position (it would crash on moves whose pieces
  // were summoned or removed outside history), so repetition detection is
  // suspended for the rest of the game.
  if (game.board.halfmove >= 8 && !bs?.historyDiverged && countRepetitions(game.board) >= 3) {
    game.result = { winner: "draw", reason: "draw by threefold repetition" };
    return game;
  }
  if (bs) {
    // Turn manipulation: extra moves keep the turn with the mover; skips hand
    // it straight back. En passant is cleared on any irregular turn flow.
    if (bs.extraMoves[move.color] > 0) {
      bs.extraMoves[move.color] -= 1;
      game.board.turn = move.color;
      game.board.epTarget = null;
      bs.chainKingGuard = move.color;
    } else if (bs.skips[game.board.turn] > 0) {
      bs.skips[game.board.turn] -= 1;
      game.board.turn = move.color;
      game.board.epTarget = null;
      bs.chainKingGuard = move.color;
    }
    // Buff draft cadence: both players draft at the same time. The shared
    // trigger runs on total plies (a full round is two plies), so neither
    // side ever runs a draft ahead of the other. White rolls first for a
    // stable RNG stream; draft-block effects eat offers individually.
    // Suspended entirely while a Chess Diff runs: no drafts during the diff.
    // The trigger stays put while it runs; endChessDiff shifts it past the
    // diff's plies on resume so the longer restored history does not fire a
    // backlog of offers.
    if (bs.diff) {
      applyTurnStart(game);
      resolveNoMoves(game);
      return game;
    }
    if (bs.nextDraftAtPly == null) {
      // Saved games from the per-player cadence era resume on the earlier
      // of the two old thresholds.
      bs.nextDraftAtPly = Math.min(bs.players.w.nextDraftAt, bs.players.b.nextDraftAt) * 2;
    }
    if (game.board.history.length >= bs.nextDraftAtPly) {
      bs.nextDraftAtPly += bs.cadence * 2;
      // One shared tier roll per round: both offers use the same pair.
      const tiers = rollSharedTiers(bs);
      for (const color of ["w", "b"] as Color[]) {
        const ps = bs.players[color];
        ps.nextDraftAt += bs.cadence;
        if (ps.offer) continue;
        if ((ps.flags.blockedDrafts ?? 0) > 0) {
          ps.flags.blockedDrafts = (ps.flags.blockedDrafts ?? 0) - 1;
          // Tell the victim explicitly (synced): their draft did not silently
          // vanish, an opponent card blocked it this round.
          ps.lastSkip = { atPly: game.board.history.length, reason: "blocked" };
        } else if (!rollOffer(bs, color, tiers, game.board)) {
          // Pool ran completely dry for this mode/tier: also announced.
          ps.lastSkip = { atPly: game.board.history.length, reason: "dry" };
        }
      }
    }
  }
  // Apply onTurnStart for the new mover BEFORE legal-move evaluation
  applyTurnStart(game);
  resolveNoMoves(game);
  return game;
}

/** The no-move rule, run whenever the side to move may have changed or lost
 * options: no moves available = loss for the side to move (their king will be
 * captured). In draft mode a player can be locked down purely by buff effects
 * (Mass Freeze, World End...). That is a forced pass, not a loss: their
 * effect timers tick as if they had moved and the turn goes back. If the
 * opponent is locked down too, the game is a draw. */
function resolveNoMoves(game: NerfGame) {
  if (game.result) return;
  if (legalMoves(game).length > 0) return;
  const bs = game.buffs;
  // Chess Diff sub-game: STANDARD chess endings, never the match. With no legal
  // move the mover is either checkmated (in check: the opponent wins the diff
  // and its apex prize) or stalemated (not in check: the diff is a draw and nobody
  // is rewarded). Legal moves are check-filtered (see legalMoves), so "no moves"
  // here is a true mate or stalemate, not a king simply left hanging.
  if (bs?.diff) {
    const mover = game.board.turn;
    const winner: Color = mover === "w" ? "b" : "w";
    endChessDiff(game, isInCheck(game.board, mover) ? winner : "draw");
    return;
  }
  if (bs && generateMoves(game.board).length > 0) {
    const stuck = game.board.turn;
    for (const e of bs.effects) {
      if (e.turns != null && effectTickColor(e) === stuck) e.turns -= 1;
    }
    fireExpiredTradeOffs(game);
    bs.effects = bs.effects.filter((e) => e.turns == null || e.turns > 0);
    pruneOrphanedSquareEffects(game);
    game.board.turn = stuck === "w" ? "b" : "w";
    game.board.epTarget = null;
    applyTurnStart(game);
    if (legalMoves(game).length === 0) {
      game.result = { winner: "draw", reason: "mutual paralysis" };
    }
    return;
  }
  game.result = {
    winner: game.board.turn === "w" ? "b" : "w",
    reason: "no legal moves",
  };
}

export function currentHint(game: NerfGame, color: Color) {
  // Nerfs are suspended during a Chess Diff, so their hints are too.
  if (game.buffs?.diff) return null;
  const slot = color === "w" ? game.white : game.black;
  if (!slot.nerf.hint || nerfDisabled(game, color)) return null;
  if (game.result || game.board.turn !== color) return null;
  const ctx = makeContext(game, color);
  return slot.nerf.hint(slot.state, ctx, legalMoves(game));
}

// ---------------------------------------------------------------------------
// Draft resolution and buff activation (draft mode only)
// ---------------------------------------------------------------------------

/** Add a buff to a player (drafted, stolen at creation, or debug-granted). */
export function acquireBuff(game: NerfGame, color: Color, id: string, tier: Tier) {
  const bs = game.buffs;
  const def = BUFF_BY_ID[id];
  if (!bs || !def?.implemented) return;
  const ps = bs.players[color];
  const inst: BuffInstance = { id, tier, state: {} };
  if ((ps.flags.nullifyIncoming ?? 0) > 0) {
    ps.flags.nullifyIncoming = (ps.flags.nullifyIncoming ?? 0) - 1;
    inst.nullified = true;
    ps.buffs.push(inst);
    return;
  }
  const api = makeBuffApi(game, color);
  def.init?.(inst, api);
  ps.buffs.push(inst);
  if (def.kind === "instant") {
    def.effect?.(inst, api, []);
    inst.spent = true;
    settleAfterBuff(game);
  }
}

/** Resolve the pending offer by taking the card at `cardIndex`. */
export function pickDraftCard(game: NerfGame, color: Color, cardIndex: number) {
  const bs = game.buffs;
  // No drafting during a Chess Diff (offers were cancelled when it started).
  if (!bs || bs.diff) return;
  const ps = bs.players[color];
  const offer = ps.offer;
  if (!offer || !offer.cards[cardIndex]) return;
  const takeAll = (ps.flags.takeBoth ?? 0) > 0;
  if (takeAll) ps.flags.takeBoth = (ps.flags.takeBoth ?? 0) - 1;
  ps.offer = null;
  const indexes = takeAll ? offer.cards.map((_, i) => i) : [cardIndex];
  for (const i of indexes) {
    acquireBuff(game, color, offer.cards[i].id, offer.cards[i].tier);
  }
}

/** Skip the pending offer and bank +1 tier for the next draft. */
export function bankDraft(game: NerfGame, color: Color) {
  const bs = game.buffs;
  if (!bs || bs.diff) return;
  bankOffer(bs.players[color]);
}

/** Reroll the pending offer (spending one reroll): fresh cards at the same
 * tiers off the deterministic RNG. Returns whether a reroll happened. */
export function rerollDraft(game: NerfGame, color: Color): boolean {
  const bs = game.buffs;
  if (!bs || bs.diff) return false;
  return rerollOffer(bs, color, game.board);
}

/** Next target request for an activated buff, or null when picks are complete. */
export function buffNextTarget(
  game: NerfGame,
  color: Color,
  buffIndex: number,
  picks: BuffPick[],
): BuffTarget | null {
  const bs = game.buffs;
  // Buffs cannot be aimed or used while a Chess Diff runs (plain chess only).
  if (!bs || bs.diff) return null;
  const inst = bs.players[color].buffs[buffIndex];
  const def = inst && BUFF_BY_ID[inst.id];
  if (!inst || !def?.targets || inst.spent || inst.nullified || inst.usedActivation) return null;
  const target = def.targets(inst, makeBuffApi(game, color), picks);
  // Graceful termination for count-based cards ("teleport N", "N pieces become
  // amazons", "remove N enemy pawns"...). Once at least one target is picked, a
  // step that offers no remaining candidates means the board has fewer eligible
  // targets than the card's nominal count. Rather than stranding the player on a
  // step they can neither satisfy nor skip, end collection here so the effect
  // resolves with the picks gathered so far (every such effect iterates over its
  // picks, so it simply applies to as many as were available). Steps already
  // marked finishable, and the very first step (picks.length === 0, a genuinely
  // unusable card), keep their existing behavior.
  if (target && picks.length > 0) {
    if (target.kind === "square" && target.squares.length === 0 && !target.finishable) return null;
    if (target.kind === "enemy-buff" && target.options.length === 0) return null;
  }
  // Early finish everywhere (owner request): once at least ONE target is
  // picked, every further square step is finishable — the player may press
  // Done and fire the card with the targets chosen so far, forfeiting the
  // rest ("teleport 3" can teleport 1). Effects already iterate their picks,
  // so a shorter list simply applies to fewer targets; the server's dtUse
  // validation accepts any stop on a finishable step, so both surfaces and
  // the server agree. The FIRST pick is never skippable: a card with zero
  // picks is a cancel, not a cast.
  if (target && target.kind === "square" && picks.length > 0 && !target.finishable) {
    return { ...target, finishable: true };
  }
  return target;
}

/** Use an activated buff with the collected picks. Returns success. */
export function activateBuff(
  game: NerfGame,
  color: Color,
  buffIndex: number,
  picks: BuffPick[],
): boolean {
  const bs = game.buffs;
  // No buff activations during a Chess Diff: the sub-game is plain chess.
  if (!bs || game.result || bs.diff) return false;
  const inst = bs.players[color].buffs[buffIndex];
  const def = inst && BUFF_BY_ID[inst.id];
  if (
    !inst ||
    !def ||
    def.kind !== "activated" ||
    inst.spent ||
    inst.nullified ||
    inst.usedActivation
  ) {
    return false;
  }
  const effectsBefore = bs.effects.length;
  def.effect?.(inst, makeBuffApi(game, color), picks);
  // A turn-consuming activation costs the activator this turn, so protective
  // timers it just created must not also burn a tick on the opponent's
  // immediate reply: "for N turns" means N turns AFTER the activation turn.
  // Only self-protection effects (shield / king-safe) suffer this overlap;
  // effects constraining the opponent (freeze, barred...) already deliver
  // their full N turns starting from the reply.
  if (!def.freeAction) {
    for (const e of bs.effects.slice(effectsBefore)) {
      if ((e.kind === "shield" || e.kind === "king_safe") && e.turns != null) e.turns += 1;
    }
  }
  if (def.spendOnUse !== false) inst.spent = true;
  // Consume the ACTIVATION for every activated card once its effect has fully
  // resolved (picks are complete before we reach here). This is the systemic
  // one-use guard: it blocks re-activation (targets() reports done, the dock
  // shows Used) WITHOUT setting `spent`, so a spendOnUse:false card is not
  // pruned and its lingering rider (onMovePlayed despawn timer, landed-on
  // trigger, per-turn effect) keeps running. Replaces the per-card ad-hoc
  // re-activation guards (which may stay as harmless belt-and-suspenders).
  // Set inside activateBuff so replicas replaying the "use" action reach the
  // same used state, keeping both clients in sync.
  inst.usedActivation = true;
  // Any activated use can reshape the board, so the activator cannot capture
  // the king until the opponent has replied (same guard as chained moves).
  bs.chainKingGuard = color;
  settleAfterBuff(game);
  // Using a buff consumes the turn unless the card is a free action (the
  // extra-move family, which already acts within the activator's turn).
  if (!game.result && !def.freeAction && game.board.turn === color) {
    passTurnAfterBuff(game, color);
  }
  return true;
}

/** A buff use that costs the turn runs the same handover bookkeeping
 * playMove does after a regular move: tick the activator's effect timers,
 * hand the move over (extra moves and pending skips still absorb it), start
 * the new mover's turn, and apply the forced-pass / no-move rules. */
function passTurnAfterBuff(game: NerfGame, color: Color) {
  const bs = game.buffs!;
  for (const e of bs.effects) {
    if (e.turns != null && effectTickColor(e) === color) e.turns -= 1;
  }
  fireExpiredTradeOffs(game);
  bs.effects = bs.effects.filter((e) => e.turns == null || e.turns > 0);
  pruneOrphanedSquareEffects(game);
  const opp: Color = color === "w" ? "b" : "w";
  if (bs.extraMoves[color] > 0) {
    bs.extraMoves[color] -= 1;
  } else if (bs.skips[opp] > 0) {
    bs.skips[opp] -= 1;
  } else {
    game.board.turn = opp;
  }
  game.board.epTarget = null;
  applyTurnStart(game);
  resolveNoMoves(game);
}

/** After a buff mutates the board, re-run loss checks (a removal or freeze can
 * decide the game on the spot). */
function settleAfterBuff(game: NerfGame) {
  if (game.result) return;
  // A buff that removed or relocated a walnutted/frozen piece must drop its
  // now-orphaned marker before anything else reads the effect list.
  pruneOrphanedSquareEffects(game);
  const result = checkLossConditions(game);
  if (result) {
    game.result = result;
    return;
  }
  // An instant buff resolved from a draft pick (Mass Freeze, World End...)
  // can lock the current mover down outside any move handover. Run the same
  // no-move rule as playMove so the game force-passes or ends instead of
  // soft-locking with a stuck player.
  resolveNoMoves(game);
}

/** Auto-resolve a pending offer for a bot: prefer the highest-tier card it can
 * actually use, otherwise just take the higher tier. Passives and instants
 * resolve themselves; activated cards score slightly lower because the bot's
 * auto-targeting is cruder than a human's. Reveal cards score zero because
 * the bot cannot act on the information, and when every option is unusable
 * or purely informational the bot banks the draft instead. */
export function aiResolveDraft(game: NerfGame, color: Color) {
  const choice = aiDraftChoice(game, color);
  if (!choice) return;
  if (choice.action === "bank") bankDraft(game, color);
  else pickDraftCard(game, color, choice.index);
}

/** The decision behind aiResolveDraft, without applying it: which card to
 * pick, or bank. Lets the game server resolve a house player's offer through
 * its own recorded-action flow (resolveDraftPick / resolveDraftBank) so the
 * match record stays identical to a human game's. */
export function aiDraftChoice(
  game: NerfGame,
  color: Color,
): { action: "pick"; index: number } | { action: "bank" } | null {
  const bs = game.buffs;
  if (!bs) return null;
  const offer = bs.players[color].offer;
  if (!offer) return null;
  let best = 0;
  let bestScore = -1;
  offer.cards.forEach((card, i) => {
    const def = BUFF_BY_ID[card.id];
    const usable =
      !def || !def.implemented || def.category === "info"
        ? 0
        : aiCanUse(def)
          ? 100
          : def.kind === "activated"
            ? 80
            : 0;
    const score = usable + card.tier;
    if (score > bestScore) {
      bestScore = score;
      best = i;
    }
  });
  // Nothing here the bot can profit from: bank for a higher tier next time,
  // unless this offer already came from a banked skip.
  if (bestScore < 50 && !offer.banked) return { action: "bank" };
  return { action: "pick", index: best };
}

// ---------------------------------------------------------------------------
// AI buff activation
// ---------------------------------------------------------------------------

const AI_PIECE_VALUE: Record<PieceType, number> = { p: 1, n: 3, b: 3, r: 5, q: 9, k: 100 };

/** Score a candidate square for auto-targeting: enemy pieces dominate (by
 * value), then own pieces, then empty squares by centrality. */
function aiSquareScore(game: NerfGame, me: Color, sq: Square): number {
  const p = game.board.pieces[sq];
  const centrality = 7 - Math.max(Math.abs(FILE(sq) - 3.5), Math.abs(RANK(sq) - 3.5)) * 2;
  if (!p) return centrality;
  const base = AI_PIECE_VALUE[p.type] * 20;
  return p.color === me ? 100 + base + centrality : 1000 + base + centrality;
}

/** Collect a full pick sequence for an activated buff without a UI. Returns
 * null when the buff currently has no valid use, plus a rough value of the
 * best target so the caller can decide whether firing now is worth it. */
function aiCollectPicks(
  game: NerfGame,
  color: Color,
  buffIndex: number,
): { picks: BuffPick[]; value: number } | null {
  const opp: Color = color === "w" ? "b" : "w";
  const picks: BuffPick[] = [];
  let value = 0;
  for (let step = 0; step < 16; step++) {
    const target = buffNextTarget(game, color, buffIndex, picks);
    if (!target) return { picks, value };
    if (target.kind === "square") {
      if (!target.squares.length) return null;
      let best = target.squares[0];
      let bestScore = -1;
      for (const sq of target.squares) {
        const score = aiSquareScore(game, color, sq);
        if (score > bestScore) {
          bestScore = score;
          best = sq;
        }
      }
      const piece = game.board.pieces[best];
      if (piece && piece.color === opp) value = Math.max(value, AI_PIECE_VALUE[piece.type]);
      picks.push({ square: best });
    } else {
      if (!target.options.length) return null;
      const best = target.options.reduce((a, b) => (b.tier > a.tier ? b : a));
      value = Math.max(value, best.tier);
      picks.push({ buffIndex: best.index });
    }
  }
  return { picks, value };
}

/** Fire at most one of the bot's activated buffs, auto-picking targets.
 * Offensive cards wait for a target worth at least a minor piece so a
 * one-shot isn't wasted on a pawn; defensive/placement cards (no enemy piece
 * among the candidates) fire as soon as they are usable. Returns the used
 * card when a buff was activated (the board and effects may have changed),
 * so callers can tell the player what just hit the board. */
export function aiActivateBuffs(
  game: NerfGame,
  color: Color,
): { id: string; tier: Tier } | null {
  const choice = aiChooseBuffActivation(game, color);
  if (!choice) return null;
  const inst = game.buffs!.players[color].buffs[choice.buffIndex];
  if (activateBuff(game, color, choice.buffIndex, choice.picks)) {
    return { id: inst.id, tier: inst.tier };
  }
  return null;
}

/** The decision behind aiActivateBuffs, without applying it: the first held
 * buff worth firing right now plus its auto-picked targets, or null. Lets the
 * game server activate a house player's buff through its own recorded-action
 * flow so the match record stays identical to a human game's. */
export function aiChooseBuffActivation(
  game: NerfGame,
  color: Color,
): { buffIndex: number; picks: BuffPick[] } | null {
  const bs = game.buffs;
  if (!bs || bs.diff || game.result || game.board.turn !== color) return null;
  const ps = bs.players[color];
  const inDanger = gameInCheck(game, color);
  // Computed lazily: most calls never reach the protection branch.
  let oppAttacks: Set<Square> | null = null;
  for (let i = 0; i < ps.buffs.length; i++) {
    const inst = ps.buffs[i];
    const def = BUFF_BY_ID[inst.id];
    if (
      !def?.implemented ||
      def.kind !== "activated" ||
      inst.spent ||
      inst.nullified ||
      inst.usedActivation
    ) {
      continue;
    }
    // Belt-and-suspenders: usedActivation above already retires a fired card,
    // but the older state-based online check stays for clarity. Reusable cards
    // (spendOnUse: false) stay activatable until fired; once one is online
    // (bound to a piece or zone, or running) the bot must not burn its turns
    // re-activating it.
    if (
      def.spendOnUse === false &&
      (inst.state.sq != null ||
        inst.state.sqs != null ||
        inst.state.squares != null ||
        inst.state.active === true)
    ) {
      continue;
    }
    const collected = aiCollectPicks(game, color, i);
    if (!collected) continue;
    const hitsEnemy = collected.picks.some((p) => {
      if (p.buffIndex !== undefined) return true;
      const piece = p.square !== undefined ? game.board.pieces[p.square] : null;
      return !!piece && piece.color !== color;
    });
    // Offensive one-shots hold out for a knight's worth of value.
    if (hitsEnemy && collected.value < 3) continue;
    // In check, the turn is not spare. A turn-consuming activation costs this
    // move (see activateBuff), and nothing here makes the check go away, so
    // firing one leaves the king still attacked with the escape move already
    // spent. That was near-fatal every time, and the rule below made it the
    // COMMON case: protective cards only fire when in danger, and "in danger"
    // is exactly being in check, so this bot reliably answered a check by
    // raising a shield that does not even cover the king.
    //
    // Free actions are exempt because they cost no turn, so the escape is
    // still available afterwards.
    if (inDanger && !def.freeAction) continue;
    // Protective cards wait for actual danger instead of firing blind -- but
    // "danger" is a piece of theirs actually under attack, NOT being in check.
    // Keying it to check was what forced the bad trade above: the only moment
    // a shield was allowed to fire was the one moment its turn could not be
    // spared. A threatened piece is the real cue, and it leaves the escape
    // move free.
    if (!hitsEnemy && def.category === "protection") {
      if (!oppAttacks) oppAttacks = attackedBy(game.board, color === "w" ? "b" : "w");
      const threatened = collected.picks.some(
        (p) => p.square !== undefined && oppAttacks!.has(p.square),
      );
      if (!threatened) continue;
    }
    return { buffIndex: i, picks: collected.picks };
  }
  return null;
}

export function resign(game: NerfGame, color: Color): NerfGame {
  if (game.result) return game;
  game.result = { winner: color === "w" ? "b" : "w", reason: "resignation" };
  return game;
}
