// Plug-in signatures: extra card play-animations registered OUTSIDE
// BoardEffects.tsx, so several workstreams can add spectacle art in their own
// modules without touching the (very large) core file. Board resolves a card's
// signature as SIGNATURES[id] ?? PLUGIN_SIGNATURES[id] ?? generated, and
// SignatureOverlay's default case routes any `x:<key>` visual back to the
// merged registry (sigPluginsMerged.tsx).
//
// Contract for a plugin module (see godPlays.tsx / funnyPlays.tsx):
//   export const PLAYS: Record<string, SigPlugin> = {
//     card_id: {
//       config: { ordering, staggerMs, victims, hasLead, sound, source? },
//       Render: ({ lead, delayMs }) => <YourBurst .../>,
//     },
//   };
// Rules:
//   - Key by CARD id. A key already present in SIGNATURES is ignored (the
//     bespoke core entry wins) — do not shadow core entries; edit them there.
//   - `sound` must be an EXISTING SigSoundKey (Board's playSignature switch);
//     pick the closest voice, no new sound plumbing from plugins.
//   - Render must be fully self-contained (own SVG + its own CSS file):
//     transform/opacity animations only, reduced-motion gated by the caller's
//     layer, no imports from BoardEffects.tsx (cycle hazard).
//
// CODE SPLIT: this module is the EAGER facade only — it must stay tiny and
// must NOT import the plugin modules (their ~9k lines of render art ride in
// the lazy signature-visuals chunk; see sigPluginsMerged.tsx / sigVisuals.tsx
// and the prefetchSignatureVisuals note in BoardEffects.tsx). Plugin modules
// import only the SigPlugin TYPE from here, which is erased at compile time.

import type { ComponentType } from "react";
import type { SignatureConfig } from "./BoardEffects";

/**
 * Which beat of a card's life this render is playing.
 *
 *   "lead"     the play's board-scale flourish, on the cast square
 *   "target"   the per-victim hit, on each affected square
 *   "entrance" the card ARRIVING in a hand (draft pick, steal, grant), before
 *              it is ever played. Reduced scale, no board takeover: it should
 *              read as the same card as the play without pretending to BE the
 *              play. A scene that does not handle it falls back to its target
 *              cut, which is correct but generic; every new scene should give
 *              the entrance its own beat.
 */
export type SigRole = "lead" | "target" | "entrance";

export interface SigPlugin {
  config: Omit<SignatureConfig, "visual">;
  /** `lead` is kept as a derived alias of `role === "lead"` so the modules
   *  written before entrances existed keep working unchanged. */
  Render: ComponentType<{ lead: boolean; role: SigRole; delayMs: number }>;
}

/** Full SignatureConfig per plugin card id, visual keyed back to the merged
 * registry (`x:<card_id>`). Starts EMPTY and is populated (in place) the
 * moment sigPluginsMerged.tsx evaluates inside the lazy signature-visuals
 * chunk — Board prefetches that chunk on mount, so the registry is complete
 * long before a card can be played. Until then Board's resolveSignature
 * simply finds no bespoke entry and falls back to the deterministic generated
 * signature, which needs no chunk at all. Reads happen at card-fire time
 * (never cached across the fill), so late population is always picked up. */
export const PLUGIN_SIGNATURES: Record<string, SignatureConfig> = {};

/**
 * Every card id covered by a plugin module, known EAGERLY (the modules
 * themselves ride in the lazy signature-visuals chunk). Before that chunk
 * evaluates, PLUGIN_SIGNATURES is still empty; without this list the resolver
 * would fall back to the GENERATED signature for a plugin-covered card and
 * play the wrong art ("default effects blocking the customized ones").
 * Board treats these ids as "pending bespoke" pre-load: no art rather than
 * wrong art. Static on purpose so it costs zero bytes of render code (the
 * modules ride the lazy chunk).
 *
 * SINGLE SOURCE OF TRUTH: this array is MACHINE-GENERATED from each plugin
 * module's `PLAYS` keys by scripts/check-sig-plugins.cjs. Do NOT edit the
 * generated block by hand — regenerate it with:
 *     node scripts/check-sig-plugins.cjs --write
 * The same script runs in `test:rules` and FAILS the build the moment this
 * list drifts from the real merged keys (an id missing here plays the wrong
 * generated art over the hand-made one; a stale id renders no art at all), so
 * drift can never ship. This replaces the old dev-only console.warn, which was
 * stripped from production and so shipped silently.
 */
/**
 * Card id -> the module holding its art. Machine-generated alongside
 * PLUGIN_IDS.
 *
 * This is what makes per-module loading possible: Board knows both hands, so
 * it can warm exactly the modules whose art can appear this game instead of
 * the whole library (which projects to ~9.6MB of source at full coverage).
 * Eager and tiny by design - it is ids and module names, no render code.
 */
// <card-modules:generated>
export const CARD_TO_MODULE: Record<string, string> = {
  // basicPlays.tsx (296)
  "cornerstone": "basicPlays",
  "firm_footing": "basicPlays",
  "guarded_king": "basicPlays",
  "holy_hell": "basicPlays",
  "loose_pawn": "basicPlays",
  "pawn_shield": "basicPlays",
  "steady_hand": "basicPlays",
  "bulwark": "basicPlays",
  "fork_guard": "basicPlays",
  "reinforce": "basicPlays",
  "screen": "basicPlays",
  "shielded_advance": "basicPlays",
  "sidestep_king": "basicPlays",
  "chain_mail": "basicPlays",
  "deflect": "basicPlays",
  "fortress": "basicPlays",
  "iron_bishop": "basicPlays",
  "phalanx": "basicPlays",
  "wa_sigil_ward": "basicPlays",
  "duelist": "basicPlays",
  "hold_the_bridge": "basicPlays",
  "iron_wall": "basicPlays",
  "shieldmaiden": "basicPlays",
  "warding_circle": "basicPlays",
  "watermelon_rind": "basicPlays",
  "ww_high_ground": "basicPlays",
  "butterfingers": "basicPlays",
  "cold_feet": "basicPlays",
  "crossed_wires": "basicPlays",
  "foggy_glasses": "basicPlays",
  "royal_restraint": "basicPlays",
  "stage_fright": "basicPlays",
  "blunted_lance": "basicPlays",
  "lame_horses": "basicPlays",
  "rusted_hinges": "basicPlays",
  "safe_passage": "basicPlays",
  "timid_king": "basicPlays",
  "sown_salt": "basicPlays",
  "wc_backseat_driver": "basicPlays",
  "atomic_captures_small": "basicPlays",
  "hex_doll": "basicPlays",
  "wc_butterfingers": "basicPlays",
  "we_backdraft": "basicPlays",
  "cold_open": "basicPlays",
  "heavy_boots": "basicPlays",
  "knock_knees": "basicPlays",
  "molasses": "basicPlays",
  "slippery_grip": "basicPlays",
  "stiff_joints": "basicPlays",
  "anchor": "basicPlays",
  "butter_bishops": "basicPlays",
  "leaden_queen": "basicPlays",
  "seized_axles": "basicPlays",
  "short_leash": "basicPlays",
  "trench_line": "basicPlays",
  "anchored_rooks": "basicPlays",
  "blinkered_bishops": "basicPlays",
  "leaden_crown": "basicPlays",
  "magnet": "basicPlays",
  "pawn_nerf": "basicPlays",
  "spooked_steeds": "basicPlays",
  "we_static_field": "basicPlays",
  "abandoned_post": "basicPlays",
  "blockade": "basicPlays",
  "frozen_furrows": "basicPlays",
  "heavy_shackles": "basicPlays",
  "wc_quicksand_patch": "basicPlays",
  "cold_snap": "basicPlays",
  "hard_reset": "basicPlays",
  "pinned_down": "basicPlays",
  "we_frost_nip": "basicPlays",
  "frost": "basicPlays",
  "frostbite": "basicPlays",
  "snap_freeze": "basicPlays",
  "twist_the_knife": "basicPlays",
  "wa_stasis_field": "basicPlays",
  "wall": "basicPlays",
  "wc_clumsy_dash": "basicPlays",
  "wc_slip_on_ice": "basicPlays",
  "wc_stage_fright": "basicPlays",
  "cascade_freeze": "basicPlays",
  "cryostasis": "basicPlays",
  "hard_frost": "basicPlays",
  "immobilizer": "basicPlays",
  "wa_bind_the_queen": "basicPlays",
  "ww_counter_charge": "basicPlays",
  "gargoyles": "basicPlays",
  "stone_hooves": "basicPlays",
  "gorgons_glance": "basicPlays",
  "hobbled_cavalry": "basicPlays",
  "petrified_towers": "basicPlays",
  "granite_towers": "basicPlays",
  "ironbound_rook": "basicPlays",
  "statue_stable": "basicPlays",
  "stone_clergy": "basicPlays",
  "ferz_king": "basicPlays",
  "half_step": "basicPlays",
  "loyal_pawn": "basicPlays",
  "quiet_march": "basicPlays",
  "rook_slide": "basicPlays",
  "sentinel_pawn": "basicPlays",
  "sidestep": "basicPlays",
  "tempo_shuffle": "basicPlays",
  "ghost_pawn": "basicPlays",
  "pawn_push": "basicPlays",
  "phase_rook": "basicPlays",
  "reposition": "basicPlays",
  "wazir_rook": "basicPlays",
  "we_thunder_step": "basicPlays",
  "grasshopper": "basicPlays",
  "promote_now": "basicPlays",
  "queens_echo": "basicPlays",
  "rank_runner": "basicPlays",
  "vanguard": "basicPlays",
  "wa_transmute": "basicPlays",
  "we_ball_lightning": "basicPlays",
  "we_riverflow": "basicPlays",
  "ww_phalanx_advance": "basicPlays",
  "changeling": "basicPlays",
  "kingslide": "basicPlays",
  "royal_decree": "basicPlays",
  "wa_arcane_conduit": "basicPlays",
  "bishop_polish": "basicPlays",
  "diagonal_step": "basicPlays",
  "little_leap": "basicPlays",
  "nudge": "basicPlays",
  "camel_knight": "basicPlays",
  "long_knight": "basicPlays",
  "mind_nudge": "basicPlays",
  "rally": "basicPlays",
  "spring_pawn": "basicPlays",
  "teleport_knight": "basicPlays",
  "vault": "basicPlays",
  "wazir_bishop": "basicPlays",
  "wc_kangaroo_hop": "basicPlays",
  "we_updraft": "basicPlays",
  "bishop_archbishop": "basicPlays",
  "board_quake": "basicPlays",
  "cannon": "basicPlays",
  "dragon_pawn": "basicPlays",
  "hunter_knight": "basicPlays",
  "knight_nightrook": "basicPlays",
  "overclock": "basicPlays",
  "rook_chancellor": "basicPlays",
  "sliding_king": "basicPlays",
  "tidal_push": "basicPlays",
  "trampoline": "basicPlays",
  "wa_ghostwalk_bishop": "basicPlays",
  "ww_flank_march": "basicPlays",
  "ww_forced_retreat": "basicPlays",
  "ww_pontoon_bridge": "basicPlays",
  "ww_war_wagon": "basicPlays",
  "firecracker": "basicPlays",
  "giant_slayer": "basicPlays",
  "overrun": "basicPlays",
  "twin_knights": "basicPlays",
  "wa_camel_rider": "basicPlays",
  "steady_march": "basicPlays",
  "counterstep": "basicPlays",
  "double_step_army": "basicPlays",
  "pawn_storm": "basicPlays",
  "ww_pikemen": "basicPlays",
  "berolina_pawns": "basicPlays",
  "momentum": "basicPlays",
  "split_march": "basicPlays",
  "wc_moonwalk": "basicPlays",
  "army_reversal": "basicPlays",
  "solstice": "basicPlays",
  "wc_chaos_reigns": "basicPlays",
  "ww_field_fortification": "basicPlays",
  "cut_purse": "basicPlays",
  "sealed_orders": "basicPlays",
  "royal_duty": "basicPlays",
  "wa_suppress_magic": "basicPlays",
  "wc_red_tape": "basicPlays",
  "burned_dispatches": "basicPlays",
  "chain_nullify": "basicPlays",
  "dead_letter": "basicPlays",
  "mirror": "basicPlays",
  "patch_notes": "basicPlays",
  "suppress": "basicPlays",
  "wa_disrupt_ritual": "basicPlays",
  "wa_jinx": "basicPlays",
  "prep": "basicPlays",
  "trade_up": "basicPlays",
  "buff_thief_minor": "basicPlays",
  "heros_journey": "basicPlays",
  "recast": "basicPlays",
  "wa_disjunction": "basicPlays",
  "extra_glance": "basicPlays",
  "peek": "basicPlays",
  "quick_glance": "basicPlays",
  "scout": "basicPlays",
  "watchtower": "basicPlays",
  "draft_insight": "basicPlays",
  "oracles_eye": "basicPlays",
  "third_eye": "basicPlays",
  "north_star": "basicPlays",
  "wa_foresight": "basicPlays",
  "wa_mind_read": "basicPlays",
  "wa_omniscience": "basicPlays",
  "castle_early": "basicPlays",
  "drawbridge": "basicPlays",
  "toll_gate": "basicPlays",
  "long_castle_anywhere": "basicPlays",
  "no_mans_land": "basicPlays",
  "wc_shy_pieces": "basicPlays",
  "board_lock": "basicPlays",
  "bunker": "basicPlays",
  "no_trespass": "basicPlays",
  "flypaper_file": "basicPlays",
  "sealed_gate": "basicPlays",
  "second_wind": "basicPlays",
  "minor_recall": "basicPlays",
  "we_regrow": "basicPlays",
  "ww_field_hospital": "basicPlays",
  "ww_reclaim_the_fallen": "basicPlays",
  "seance": "basicPlays",
  "second_wind_major": "basicPlays",
  "will_o_wisp": "basicPlays",
  "ww_last_reserves": "basicPlays",
  "resurrect": "basicPlays",
  "resurrect_major": "basicPlays",
  "wc_lost_and_found": "basicPlays",
  "ww_recommission": "basicPlays",
  "walnut_shell": "basicPlays",
  "apple": "basicPlays",
  "banana_peel": "basicPlays",
  "coconut_bonk": "basicPlays",
  "kings_guard": "basicPlays",
  "bodyguard": "basicPlays",
  "split_bishop": "basicPlays",
  "ww_sapper_team": "basicPlays",
  "coffee": "basicPlays",
  "comet_shard": "basicPlays",
  "wa_conjure_bishop": "basicPlays",
  "ww_shieldbearers": "basicPlays",
  "wasted_hour": "basicPlays",
  "lost_weekend": "basicPlays",
  "wa_borrowed_minute": "basicPlays",
  "deep_breath": "basicPlays",
  "reprieve": "basicPlays",
  "small_mercies": "basicPlays",
  "defiance": "basicPlays",
  "held_breath": "basicPlays",
  "hunters_relief": "basicPlays",
  "slack_chain": "basicPlays",
  "break_the_nerf": "basicPlays",
  "grace_period": "basicPlays",
  "timely_lull": "basicPlays",
  "underdogs_grit": "basicPlays",
  "adrenaline": "basicPlays",
  "counter_nerf": "basicPlays",
  "respite": "basicPlays",
  "durian": "basicPlays",
  "pixie_dust": "basicPlays",
  "seelie_blessing": "basicPlays",
  "we_bramble_wall": "basicPlays",
  "we_creeping_roots": "basicPlays",
  "we_seedlings": "basicPlays",
  "faerie_ring": "basicPlays",
  "pucks_mischief": "basicPlays",
  "we_ancient_grove": "basicPlays",
  "escape_hatch": "basicPlays",
  "piece_swap": "basicPlays",
  "recall": "basicPlays",
  "ww_regroup_lines": "basicPlays",
  "guard_rotation": "basicPlays",
  "wa_blink": "basicPlays",
  "warp_home": "basicPlays",
  "warp_step": "basicPlays",
  "blink_army": "basicPlays",
  "grand_recall": "basicPlays",
  "mass_recall": "basicPlays",
  "regroup": "basicPlays",
  "total_recall": "basicPlays",
  "wa_swap_flanks": "basicPlays",
  "warp_field": "basicPlays",
  "warp_reign": "basicPlays",
  "warp_rook": "basicPlays",
  "we_riptide": "basicPlays",
  "we_undertow": "basicPlays",
  "regenerate": "basicPlays",
  "summon_knight": "basicPlays",
  "wa_conjure_scout": "basicPlays",
  "ww_outriders": "basicPlays",
  "mass_resurrect": "basicPlays",
  "phantom_rook": "basicPlays",
  "ww_forward_observer": "basicPlays",
  "ww_reserve_cavalry": "basicPlays",
  "glamour": "basicPlays",
  "piece_steal": "basicPlays",
  "wa_dominate_minor": "basicPlays",
  "wc_body_double": "basicPlays",
  "ww_defectors": "basicPlays",
  "ww_mass_defection": "basicPlays",
  // godPlays.tsx (68)
  "draft_tyranny": "godPlays",
  "sovereign_draft": "godPlays",
  "draft_supremacy": "godPlays",
  "divine_legion": "godPlays",
  "absolute_aegis": "godPlays",
  "checkmate_denial": "godPlays",
  "full_pardon": "godPlays",
  "transcendence": "godPlays",
  "mind_empire": "godPlays",
  "mass_mind_control": "godPlays",
  "throne_and_silence": "godPlays",
  "abdication_edict": "godPlays",
  "wa_dominate_major": "godPlays",
  "great_divide": "godPlays",
  "sundering": "godPlays",
  "fortress_realm": "godPlays",
  "molten_heart": "godPlays",
  "salted_earth": "godPlays",
  "unshackled_wrath": "godPlays",
  "phoenix_line": "godPlays",
  "chain_atomic": "godPlays",
  "total_atomic": "godPlays",
  "scorched_earth": "godPlays",
  "rift_storm": "godPlays",
  "queen_storm": "godPlays",
  "buff_plunder": "godPlays",
  "total_plunder": "godPlays",
  "grand_nullify": "godPlays",
  "absolute_nullify": "godPlays",
  "endless_night": "godPlays",
  "peace_of_the_grave": "godPlays",
  "withered_hands": "godPlays",
  "grand_malediction": "godPlays",
  "blighted_furrows": "godPlays",
  "culling": "godPlays",
  "poisoned_counsel": "godPlays",
  "age_of_heroes": "godPlays",
  "grand_retreat": "godPlays",
  "noble_rout": "godPlays",
  "sacked_capital": "godPlays",
  "genesis": "godPlays",
  "reality_warp": "godPlays",
  "total_warp": "godPlays",
  "warp_cataclysm": "godPlays",
  "warp_sovereign": "godPlays",
  "nerf_reversal": "godPlays",
  "celestial_alignment": "godPlays",
  "grand_conjunction": "godPlays",
  "glacial_tomb": "godPlays",
  "frozen_solid": "godPlays",
  "absolute_zero": "godPlays",
  "everfrost_shard": "godPlays",
  "ban_hammer": "godPlays",
  "dragonslayer": "godPlays",
  "world_lock": "godPlays",
  "sealed_archive": "godPlays",
  "sealed_ramparts": "godPlays",
  "leaden_limbs": "godPlays",
  "walnut_court": "godPlays",
  "obsidian_bastions": "godPlays",
  "statue_garden": "godPlays",
  "cockatrice_gaze": "godPlays",
  "chisel_curse": "godPlays",
  "crown_and_castle": "godPlays",
  "full_rewind": "godPlays",
  "endless_turn": "godPlays",
  "lost_fortnight": "godPlays",
  "sabbatical": "godPlays",
  // greatPlays.tsx (115)
  "ball_and_chain": "greatPlays",
  "royal_summons": "greatPlays",
  "palsied_hands": "greatPlays",
  "throne_bound": "greatPlays",
  "lone_sovereign": "greatPlays",
  "peasant_levy": "greatPlays",
  "court_in_exile": "greatPlays",
  "cast_a_nerf": "greatPlays",
  "royal_handicap": "greatPlays",
  "queens_handicap": "greatPlays",
  "grounded_command": "greatPlays",
  "lunar_eclipse": "greatPlays",
  "hexed_satchel": "greatPlays",
  "iron_furrow": "greatPlays",
  "leaden_fields": "greatPlays",
  "wc_voodoo_doll": "greatPlays",
  "wc_sticky_floor": "greatPlays",
  "threads_of_fate": "greatPlays",
  "mind_control": "greatPlays",
  "mind_dominion": "greatPlays",
  "medusas_verdict": "greatPlays",
  "granite_ramparts": "greatPlays",
  "stone_menagerie": "greatPlays",
  "stone_curse": "greatPlays",
  "stone_riders": "greatPlays",
  "stone_prelates": "greatPlays",
  "stone_bastions": "greatPlays",
  "queen_of_stone": "greatPlays",
  "eternal_statue": "greatPlays",
  "nerf_hammer": "greatPlays",
  "the_big_chill": "greatPlays",
  "frozen_moment": "greatPlays",
  "creeping_frost": "greatPlays",
  "glacial_flanks": "greatPlays",
  "total_whiteout": "greatPlays",
  "we_frostbite_curse": "greatPlays",
  "total_freeze": "greatPlays",
  "atomic_captures": "greatPlays",
  "atomic_reaction": "greatPlays",
  "detonation_field": "greatPlays",
  "ww_demolition_charge": "greatPlays",
  "wc_confetti_cannon": "greatPlays",
  "we_firestorm": "greatPlays",
  "giants_maul": "greatPlays",
  "scorched_middle": "greatPlays",
  "checkmate_immunity": "greatPlays",
  "iron_reign": "greatPlays",
  "ironclad": "greatPlays",
  "ww_iron_bulwark": "greatPlays",
  "ww_praetorian_guard": "greatPlays",
  "round_table": "greatPlays",
  "ww_bridgehead": "greatPlays",
  "sealed_avenues": "greatPlays",
  "dryad_grove": "greatPlays",
  "we_overgrowth": "greatPlays",
  "we_rooted": "greatPlays",
  "we_quagmire": "greatPlays",
  "thorn_hedge": "greatPlays",
  "gossamer_veil": "greatPlays",
  "starlight_ward": "greatPlays",
  "spirit_guide": "greatPlays",
  "phase_army": "greatPlays",
  "ghost_legion": "greatPlays",
  "valkyrie": "greatPlays",
  "extra_move_repeat": "greatPlays",
  "time_stop_short": "greatPlays",
  "time_rewind": "greatPlays",
  "lost_days": "greatPlays",
  "wa_stolen_hours": "greatPlays",
  "sever": "greatPlays",
  "draft_domination": "greatPlays",
  "total_nullify": "greatPlays",
  "favorable_stars": "greatPlays",
  "the_tower": "greatPlays",
  "death_arcana": "greatPlays",
  "chess_diff": "greatPlays",
  "wa_greed": "greatPlays",
  "riddle_game": "greatPlays",
  "rehab": "greatPlays",
  "parole": "greatPlays",
  "long_leash": "greatPlays",
  "wardens_bribe": "greatPlays",
  "iron_will": "greatPlays",
  "wc_wrong_way": "greatPlays",
  "wc_broken_elevator": "greatPlays",
  "unseelie_bargain": "greatPlays",
  "buff_thief": "greatPlays",
  "buff_siphon": "greatPlays",
  "wa_spelltheft": "greatPlays",
  "draft_seize": "greatPlays",
  "collapse": "greatPlays",
  "void": "greatPlays",
  "wa_sabotage": "greatPlays",
  "empty_handed": "greatPlays",
  "double_queen": "greatPlays",
  "twin_queens": "greatPlays",
  "promotion_storm": "greatPlays",
  "mass_promote_minor": "greatPlays",
  "resurrect_queen": "greatPlays",
  "legendary_forge": "greatPlays",
  "royal_ascension": "greatPlays",
  "second_king": "greatPlays",
  "wa_leaden_crown": "greatPlays",
  "overclock_major": "greatPlays",
  "ascendant_knight": "greatPlays",
  "nerf_breaker": "greatPlays",
  "fey_step": "greatPlays",
  "rift_walker": "greatPlays",
  "mirror_of_souls": "greatPlays",
  "wa_conjure_rook": "greatPlays",
  "wa_twin_familiars": "greatPlays",
  "ley_line": "greatPlays",
  "wild_hunt": "greatPlays",
  "dragon_mount": "greatPlays",
  "sahur": "greatPlays",
  // funnyPlays.tsx (16)
  "emotional_support_pawn": "funnyPlays",
  "stream_sniper": "funnyPlays",
  "lag_spike": "funnyPlays",
  "ctrl_z": "funnyPlays",
  "rubber_chicken": "funnyPlays",
  "day_one_patch": "funnyPlays",
  "battle_pass": "funnyPlays",
  "pop_up_ad": "funnyPlays",
  "mute_button": "funnyPlays",
  "skill_issue": "funnyPlays",
  "alt_f4": "funnyPlays",
  "touch_grass": "funnyPlays",
  "main_character": "funnyPlays",
  "smurf_account": "funnyPlays",
  "pay_to_win": "funnyPlays",
  "expansion_permit": "funnyPlays",
  // personalPlays.tsx (20)
  "muscle_up": "personalPlays",
  "bench_225": "personalPlays",
  "handstand_pushup": "personalPlays",
  "full_planche": "personalPlays",
  "fingertip_maltese": "personalPlays",
  "onearmmuscleupismydream": "personalPlays",
  "monkeytype": "personalPlays",
  "rubiks_cube": "personalPlays",
  "ilovewhimperingaudios": "personalPlays",
  "ilovemakingout": "personalPlays",
  "ilovechaewon": "personalPlays",
  "hyein": "personalPlays",
  "minji": "personalPlays",
  "hanni": "personalPlays",
  "danielle": "personalPlays",
  "haerin": "personalPlays",
  "i_love_cam": "personalPlays",
  "daniel_caesar": "personalPlays",
  "middle_part": "personalPlays",
  "forearm_veins": "personalPlays",
  // memePlays.tsx (9)
  "cappuccino_assassino": "memePlays",
  "ballerina_cappuccina": "memePlays",
  "la_vaca_saturno_saturnita": "memePlays",
  "frigo_camelo": "memePlays",
  "trippi_troppi": "memePlays",
  "chill_guy": "memePlays",
  "moai_head": "memePlays",
  "skibidi_flush": "memePlays",
  "tung_tung_sahur": "memePlays",
  // stubPlays.tsx (8)
  "free_retreat": "stubPlays",
  "rewind_one": "stubPlays",
  "shadow_step": "stubPlays",
  "pin_breaker": "stubPlays",
  "decoy": "stubPlays",
  "loosen_the_leash": "stubPlays",
  "piece_parole": "stubPlays",
  "half_measure": "stubPlays",
  // prankPlays.tsx (9)
  "pr_phishing": "prankPlays",
  "pr_donation_alert": "prankPlays",
  "pr_bsod": "prankPlays",
  "pr_forced_update": "prankPlays",
  "pr_defender_scan": "prankPlays",
  "pr_captcha": "prankPlays",
  "pr_popup_storm": "prankPlays",
  "pr_chain_letter": "prankPlays",
  "pr_ratiod": "prankPlays",
  // casinoPlays.tsx (7)
  "cs_slot_machine": "casinoPlays",
  "cs_roulette": "casinoPlays",
  "cs_blackjack": "casinoPlays",
  "cs_scratch_card": "casinoPlays",
  "cs_let_it_ride": "casinoPlays",
  "cs_loot_box": "casinoPlays",
  "cs_poker_bluff": "casinoPlays",
  // gamblingPlays.tsx (28)
  "gm_penny_slots": "gamblingPlays",
  "gm_heads_or_tails": "gamblingPlays",
  "gm_claw_machine": "gamblingPlays",
  "gm_raffle_ticket": "gamblingPlays",
  "gm_card_counting": "gamblingPlays",
  "gm_loaded_dice": "gamblingPlays",
  "gm_lootbox": "gamblingPlays",
  "gm_three_card_monte": "gamblingPlays",
  "gm_underdog_parlay": "gamblingPlays",
  "gm_river_card": "gamblingPlays",
  "gm_piece_roulette": "gamblingPlays",
  "gm_jackpot_pawn": "gamblingPlays",
  "gm_double_down_draft": "gamblingPlays",
  "gm_crash_game": "gamblingPlays",
  "gm_blood_wager": "gamblingPlays",
  "gm_progressive_jackpot": "gamblingPlays",
  "gm_the_house": "gamblingPlays",
  "gm_gacha_banner": "gamblingPlays",
  "gm_seven_cases": "gamblingPlays",
  "gm_martingale": "gamblingPlays",
  "gm_devils_deck": "gamblingPlays",
  "gm_break_the_bank": "gamblingPlays",
  "gm_wheel_of_the_cosmos": "gamblingPlays",
  "gm_cursed_dice": "gamblingPlays",
  "gm_rigged_raffle": "gamblingPlays",
  "gm_consolation_scratcher": "gamblingPlays",
  "gm_hardship_jackpot": "gamblingPlays",
  "gm_the_last_bet": "gamblingPlays",
  // boonPlays.tsx (72)
  "bw2_ancient_custom": "boonPlays",
  "bw2_hit_and_run": "boonPlays",
  "bw2_cornered_king": "boonPlays",
  "bw2_blood_duel": "boonPlays",
  "bw2_divine_right": "boonPlays",
  "bw2_pioneers_banner": "boonPlays",
  "bw2_diplomatic_immunity": "boonPlays",
  "bw2_deathless_oath": "boonPlays",
  "bw2_spoils_of_war": "boonPlays",
  "bw2_prisoner_exchange": "boonPlays",
  "bw2_highwaymans_toll": "boonPlays",
  "bw2_queens_testament": "boonPlays",
  "bw2_scarecrow": "boonPlays",
  "bw2_masquerade": "boonPlays",
  "bw2_alchemists_trade": "boonPlays",
  "bw2_early_coronation": "boonPlays",
  "bw2_standard_bearer": "boonPlays",
  "bw2_ascetics_bargain": "boonPlays",
  "bw2_jesters_rule": "boonPlays",
  "bw2_blood_price": "boonPlays",
  "bw2_kingmakers_pact": "boonPlays",
  "bw2_bolt_hole": "boonPlays",
  "bw2_carnival_of_masks": "boonPlays",
  "bw2_restitution": "boonPlays",
  "bw2_long_truce": "boonPlays",
  "bw2_great_return": "boonPlays",
  "bw2_shadow_reserve": "boonPlays",
  "bw2_eternal_keep": "boonPlays",
  "bw3_forced_march": "boonPlays",
  "bw3_royal_caper": "boonPlays",
  "bw3_tunnelers": "boonPlays",
  "bw3_rally_royal": "boonPlays",
  "bw3_underdogs_gambit": "boonPlays",
  "bw3_bishops_blessing": "boonPlays",
  "bw3_shield_wall": "boonPlays",
  "bw3_kings_shield": "boonPlays",
  "bw3_praetorian": "boonPlays",
  "bw3_watchword": "boonPlays",
  "bw3_vantage_point": "boonPlays",
  "bw3_hallowed_ground": "boonPlays",
  "bw3_first_blood": "boonPlays",
  "bw3_postern_gate": "boonPlays",
  "bw3_coronation_bonus": "boonPlays",
  "bw3_plunderers_ledger": "boonPlays",
  "bw3_eleventh_hour": "boonPlays",
  "bw3_deep_position": "boonPlays",
  "bw3_martyrs_gift": "boonPlays",
  "bw3_heir_apparent": "boonPlays",
  "bw3_field_knighting": "boonPlays",
  "bw3_battlefield_commission": "boonPlays",
  "bw3_ironwrights_bargain": "boonPlays",
  "bw3_second_face": "boonPlays",
  "bw3_home_guard": "boonPlays",
  "bw3_double_down": "boonPlays",
  "bw3_kings_road": "boonPlays",
  "bw3_futures_market": "boonPlays",
  "bw3_castle_in_the_storm": "boonPlays",
  "bw3_last_muster": "boonPlays",
  "bw3_funeral_pyre": "boonPlays",
  "bw3_mummers_dance": "boonPlays",
  "bw3_last_stand": "boonPlays",
  "bw3_high_stakes": "boonPlays",
  "bw3_from_the_ashes": "boonPlays",
  "bw3_kingsguard_duel": "boonPlays",
  "bw3_kings_sanctuary": "boonPlays",
  "bw3_martyrdom": "boonPlays",
  "bw3_the_reckoning": "boonPlays",
  "bw3_covenant_of_return": "boonPlays",
  "bw3_the_homecoming": "boonPlays",
  "bw3_turn_the_tide": "boonPlays",
  "bw3_pretender": "boonPlays",
  "bw3_drive_them_out": "boonPlays",
  // cursePlays.tsx (67)
  "hw2_witchs_veto": "cursePlays",
  "hw2_long_road_home": "cursePlays",
  "hw2_blood_price": "cursePlays",
  "hw2_tarnished_crown": "cursePlays",
  "hw2_war_rations": "cursePlays",
  "hw2_compounding_misery": "cursePlays",
  "hw2_bad_omen": "cursePlays",
  "hw2_tolling_bell": "cursePlays",
  "hw2_witching_hour": "cursePlays",
  "hw2_weight_of_toil": "cursePlays",
  "hw2_cold_footprints": "cursePlays",
  "hw2_creeping_blight": "cursePlays",
  "hw2_gravebloom": "cursePlays",
  "hw2_gathering_storm": "cursePlays",
  "hw2_twinned_torment": "cursePlays",
  "hw2_no_reins": "cursePlays",
  "hw2_curse_of_recoil": "cursePlays",
  "hw2_queens_ransom": "cursePlays",
  "hw2_bound_court": "cursePlays",
  "hw2_cursed_coin": "cursePlays",
  "hw2_gilded_rot": "cursePlays",
  "hw2_death_knell": "cursePlays",
  "hw2_hollow_crown": "cursePlays",
  "hw2_tide_of_ash": "cursePlays",
  "hw2_crown_of_thorns": "cursePlays",
  "hw2_pauper_crown": "cursePlays",
  "hw2_beacon_of_woe": "cursePlays",
  "hw3_wrong_foot": "cursePlays",
  "hw3_overexertion": "cursePlays",
  "hw3_toll_road": "cursePlays",
  "hw3_bloodlust": "cursePlays",
  "hw3_exiles_mark": "cursePlays",
  "hw3_debtors_mark": "cursePlays",
  "hw3_coronation_tax": "cursePlays",
  "hw3_pilgrimage": "cursePlays",
  "hw3_bounty_mark": "cursePlays",
  "hw3_feeding_frenzy": "cursePlays",
  "hw3_slow_poison": "cursePlays",
  "hw3_jammed_castle": "cursePlays",
  "hw3_time_bomb": "cursePlays",
  "hw3_collapsing_floor": "cursePlays",
  "hw3_doomed_vow": "cursePlays",
  "hw3_wandering_sentry": "cursePlays",
  "hw3_sinking_mire": "cursePlays",
  "hw3_miasma": "cursePlays",
  "hw3_roaming_void": "cursePlays",
  "hw3_wildfire": "cursePlays",
  "hw3_effigy_of_dread": "cursePlays",
  "hw3_avalanche": "cursePlays",
  "hw3_binding_oath": "cursePlays",
  "hw3_bloodbond": "cursePlays",
  "hw3_shared_fate": "cursePlays",
  "hw3_kings_guard": "cursePlays",
  "hw3_no_retreat": "cursePlays",
  "hw3_fifth_column": "cursePlays",
  "hw3_curse_hop": "cursePlays",
  "hw3_mutiny": "cursePlays",
  "hw3_defectors_mark": "cursePlays",
  "hw3_aging_blade": "cursePlays",
  "hw3_enemy_within": "cursePlays",
  "hw3_eclipse": "cursePlays",
  "hw3_hydra_hex": "cursePlays",
  "hw3_pyrrhic_toll": "cursePlays",
  "hw3_martyrs_crown": "cursePlays",
  "hw3_curse_engine": "cursePlays",
  "hw3_blood_tithe": "cursePlays",
  "hw3_inverted_crown": "cursePlays",
  // creatorPlays.tsx (5)
  "cr_stalling_bishop": "creatorPlays",
  "cr_oh_no_my_queen": "creatorPlays",
  "cr_family_game_night": "creatorPlays",
  "cr_speedrun_protocol": "creatorPlays",
  "cr_chat_picks": "creatorPlays",
  // g01HourglassPlays.tsx (32)
  "bn4_council_of_peace": "g01HourglassPlays",
  "bn4_great_armistice": "g01HourglassPlays",
  "bn4_hundred_year_lease": "g01HourglassPlays",
  "bn4_royal_we": "g01HourglassPlays",
  "hx4_royal_lockdown": "g01HourglassPlays",
  "hx4_tithe_of_silence": "g01HourglassPlays",
  "bn4_liberators_march": "g01HourglassPlays",
  "bn4_escape_artist": "g01HourglassPlays",
  "bn4_jubilee": "g01HourglassPlays",
  "bn4_keys_to_the_city": "g01HourglassPlays",
  "bn4_royal_privilege": "g01HourglassPlays",
  "bn4_midas_charter": "g01HourglassPlays",
  "bn4_year_of_jubilee": "g01HourglassPlays",
  "bn4_hundred_days": "g01HourglassPlays",
  "bn4_debtors_holiday": "g01HourglassPlays",
  "bn4_crown_jubilee": "g01HourglassPlays",
  "bn4_meek_inherit": "g01HourglassPlays",
  "bn4_unequal_treaty": "g01HourglassPlays",
  "bn4_grand_bargain": "g01HourglassPlays",
  "bn4_patrons_favor": "g01HourglassPlays",
  "bn4_queens_aegis": "g01HourglassPlays",
  "bn4_masked_ball": "g01HourglassPlays",
  "bn4_flag_on_their_wall": "g01HourglassPlays",
  "bn4_siege_mentality": "g01HourglassPlays",
  "bn4_champions_rest": "g01HourglassPlays",
  "bn4_half_moon_charter": "g01HourglassPlays",
  "bn4_moonlit_reprieve": "g01HourglassPlays",
  "bn4_pact_of_the_dawn": "g01HourglassPlays",
  "bn4_second_spring": "g01HourglassPlays",
  "hx4_debt_of_crowns": "g01HourglassPlays",
  "hx4_last_toll": "g01HourglassPlays",
  "ov_time_heist": "g01HourglassPlays",
  // g02SchedulePlays.tsx (32)
  "bn4_uphill_battle": "g02SchedulePlays",
  "bn4_wardens_retirement": "g02SchedulePlays",
  "hx4_iron_portcullis": "g02SchedulePlays",
  "ov_patient_grift": "g02SchedulePlays",
  "bn4_diplomatic_pouch": "g02SchedulePlays",
  "bn4_double_pardon": "g02SchedulePlays",
  "bn4_guards_change": "g02SchedulePlays",
  "bn4_hidden_clause": "g02SchedulePlays",
  "bn4_hollow_crown": "g02SchedulePlays",
  "bn4_long_holiday": "g02SchedulePlays",
  "bn4_masons_lodge": "g02SchedulePlays",
  "bn4_ministers_seal": "g02SchedulePlays",
  "bn4_out_on_bail": "g02SchedulePlays",
  "bn4_pillars_of_home": "g02SchedulePlays",
  "bn4_quiet_coup": "g02SchedulePlays",
  "bn4_relief_column": "g02SchedulePlays",
  "bn4_rule_of_three": "g02SchedulePlays",
  "bn4_spymasters_leave": "g02SchedulePlays",
  "bn4_tower_toll": "g02SchedulePlays",
  "hx4_sleepwalkers": "g02SchedulePlays",
  "bn4_gentlemens_agreement": "g02SchedulePlays",
  "bn4_harvest_and_fallow": "g02SchedulePlays",
  "bn4_heavy_price": "g02SchedulePlays",
  "bn4_kings_indulgence": "g02SchedulePlays",
  "bn4_leave_of_absence": "g02SchedulePlays",
  "bn4_open_season": "g02SchedulePlays",
  "bn4_retraining": "g02SchedulePlays",
  "bn4_royal_household": "g02SchedulePlays",
  "bn4_royal_writ": "g02SchedulePlays",
  "bn4_salt_in_the_wound": "g02SchedulePlays",
  "bn4_scapegoat": "g02SchedulePlays",
  "bn4_veterans_pension": "g02SchedulePlays",
  // g03CelestialPlays.tsx (32)
  "hx4_the_bell_tolls": "g03CelestialPlays",
  "ov_managers_challenge": "g03CelestialPlays",
  "ov_nesting_doll": "g03CelestialPlays",
  "bn4_bread_and_salt": "g03CelestialPlays",
  "bn4_clerical_error": "g03CelestialPlays",
  "bn4_coronation_rest": "g03CelestialPlays",
  "bn4_furlough": "g03CelestialPlays",
  "bn4_general_strike": "g03CelestialPlays",
  "bn4_harvest_rest": "g03CelestialPlays",
  "bn4_hidden_stair": "g03CelestialPlays",
  "bn4_hold_the_door": "g03CelestialPlays",
  "bn4_home_square": "g03CelestialPlays",
  "bn4_listening_post": "g03CelestialPlays",
  "bn4_paid_leave": "g03CelestialPlays",
  "bn4_scaffold_crane": "g03CelestialPlays",
  "bn4_second_skin": "g03CelestialPlays",
  "bn4_seven_league_boots": "g03CelestialPlays",
  "bn4_worry_beads": "g03CelestialPlays",
  "hx4_coronation_bill": "g03CelestialPlays",
  "ov_sleeping_draught": "g03CelestialPlays",
  "bn4_bottom_of_the_well": "g03CelestialPlays",
  "bn4_bribe_the_clerk": "g03CelestialPlays",
  "bn4_dragonslayer": "g03CelestialPlays",
  "bn4_forty_winks": "g03CelestialPlays",
  "bn4_hermits_hour": "g03CelestialPlays",
  "bn4_hush_money": "g03CelestialPlays",
  "bn4_lone_crown": "g03CelestialPlays",
  "bn4_over_the_shoulder": "g03CelestialPlays",
  "bn4_over_the_wall": "g03CelestialPlays",
  "bn4_pawns_ransom": "g03CelestialPlays",
  "bn4_rest_stop": "g03CelestialPlays",
  "bn4_sparring_rhythm": "g03CelestialPlays",
  // g04PatinaPlays.tsx (29)
  "bn4_visor_down": "g04PatinaPlays",
  "bn4_angelus_bell": "g04PatinaPlays",
  "bn4_barter_calm": "g04PatinaPlays",
  "bn4_cold_compress": "g04PatinaPlays",
  "bn4_dowagers_patience": "g04PatinaPlays",
  "bn4_ear_to_the_ground": "g04PatinaPlays",
  "bn4_hourglass_flip": "g04PatinaPlays",
  "bn4_knights_vigil": "g04PatinaPlays",
  "bn4_measured_breath": "g04PatinaPlays",
  "bn4_pawns_lullaby": "g04PatinaPlays",
  "bn4_saints_day": "g04PatinaPlays",
  "bn4_sleepy_dust": "g04PatinaPlays",
  "bn4_slipped_collar": "g04PatinaPlays",
  "bn4_spring_in_the_step": "g04PatinaPlays",
  "bn4_steady_hands": "g04PatinaPlays",
  "bn4_trophy_rest": "g04PatinaPlays",
  "ov_loan_shark": "g04PatinaPlays",
  "bn4_castle_quiet": "g04PatinaPlays",
  "bn4_check_valve": "g04PatinaPlays",
  "bn4_crowned_calm": "g04PatinaPlays",
  "bn4_first_light": "g04PatinaPlays",
  "bn4_grace_note": "g04PatinaPlays",
  "bn4_kind_omen": "g04PatinaPlays",
  "bn4_morning_stretch": "g04PatinaPlays",
  "bn4_promise_of_rest": "g04PatinaPlays",
  "bn4_quiet_after": "g04PatinaPlays",
  "bn4_shared_silence": "g04PatinaPlays",
  "bn4_small_ritual": "g04PatinaPlays",
  "bn4_two_breaths": "g04PatinaPlays",
  // g05PawnTidePlays.tsx (30)
  "bn4_endless_militia": "g05PawnTidePlays",
  "bn4_menagerie_gates": "g05PawnTidePlays",
  "bn4_drawbridge_crew": "g05PawnTidePlays",
  "bn4_field_hospital": "g05PawnTidePlays",
  "bn4_letters_home": "g05PawnTidePlays",
  "bn4_small_consolation": "g05PawnTidePlays",
  "bn4_stray_cat": "g05PawnTidePlays",
  "bn4_florists_trick": "g05PawnTidePlays",
  "bn4_changeling_child": "g05PawnTidePlays",
  "hx4_field_of_spears": "g05PawnTidePlays",
  "bn4_leapfrog": "g05PawnTidePlays",
  "ov_rapture_of_pawns": "g05PawnTidePlays",
  "bn4_matryoshka_surprise": "g05PawnTidePlays",
  "ov_trojan_pawn": "g05PawnTidePlays",
  "ov_great_migration": "g05PawnTidePlays",
  "hx4_famine_year": "g05PawnTidePlays",
  "hx4_pawn_embargo": "g05PawnTidePlays",
  "hx4_famine": "g05PawnTidePlays",
  "hx4_no_doubling": "g05PawnTidePlays",
  "hx4_one_ladle_each": "g05PawnTidePlays",
  "hx4_pied_piper": "g05PawnTidePlays",
  "hx4_echo_of_bells": "g05PawnTidePlays",
  "hx4_candle_curfew": "g05PawnTidePlays",
  "hx4_understudy_rule": "g05PawnTidePlays",
  "ov_pied_piper": "g05PawnTidePlays",
  "ov_cloud_serpent": "g05PawnTidePlays",
  "ov_locust_swarm": "g05PawnTidePlays",
  "ov_volcanic_vent": "g05PawnTidePlays",
  "ov_fireworks_barge": "g05PawnTidePlays",
  "ov_boomerang": "g05PawnTidePlays",
  // g06GroundPlays.tsx (30)
  "ov_growth_ring": "g06GroundPlays",
  "ov_mole_tunnels": "g06GroundPlays",
  "bn4_cobblers_bench": "g06GroundPlays",
  "bn4_coffee_break": "g06GroundPlays",
  "bn4_ferry_ticket": "g06GroundPlays",
  "bn4_militia_call": "g06GroundPlays",
  "bn4_over_the_hedge": "g06GroundPlays",
  "bn4_stowaway": "g06GroundPlays",
  "hx4_fear_of_open_ground": "g06GroundPlays",
  "ov_pillow_fort": "g06GroundPlays",
  "ov_sandbags": "g06GroundPlays",
  "bn4_day_laborer": "g06GroundPlays",
  "bn4_field_stitches": "g06GroundPlays",
  "bn4_half_step_back": "g06GroundPlays",
  "bn4_slow_doors": "g06GroundPlays",
  "bn4_spare_button": "g06GroundPlays",
  "bn4_vaulting_pole": "g06GroundPlays",
  "hx4_bridge_toll": "g06GroundPlays",
  "hx4_clumsy_heralds": "g06GroundPlays",
  "hx4_no_trampling": "g06GroundPlays",
  "hx4_pawn_snob": "g06GroundPlays",
  "hx4_vegetarian_vows": "g06GroundPlays",
  "hx4_wet_matches": "g06GroundPlays",
  "op_back_to_barracks": "g06GroundPlays",
  "op_chapel_warden": "g06GroundPlays",
  "op_corduroy_road": "g06GroundPlays",
  "op_downtown_premium": "g06GroundPlays",
  "op_frontier_waiver": "g06GroundPlays",
  "op_full_coverage": "g06GroundPlays",
  "op_harbor_gull": "g06GroundPlays",
  // g07SupplyPlays.tsx (30)
  "op_homestead_clause": "g07SupplyPlays",
  "op_leapfrog_lesson": "g07SupplyPlays",
  "op_market_dog": "g07SupplyPlays",
  "op_sandbag_hurdle": "g07SupplyPlays",
  "op_threshold_blessing": "g07SupplyPlays",
  "op_trellis": "g07SupplyPlays",
  "ov_masterclass": "g07SupplyPlays",
  "ov_sock_slide": "g07SupplyPlays",
  "ov_tandem_bike": "g07SupplyPlays",
  "ov_wheelbarrow": "g07SupplyPlays",
  "ov_whittle": "g07SupplyPlays",
  "bn4_muddy_boots": "g07SupplyPlays",
  "bn4_pawn_umbrella": "g07SupplyPlays",
  "bn4_shoelace_knot": "g07SupplyPlays",
  "hx4_cold_porridge": "g07SupplyPlays",
  "hx4_heavy_pockets": "g07SupplyPlays",
  "hx4_hopscotch": "g07SupplyPlays",
  "hx4_polite_infantry": "g07SupplyPlays",
  "op_airmail": "g07SupplyPlays",
  "op_back_alley": "g07SupplyPlays",
  "op_bread_for_the_table": "g07SupplyPlays",
  "op_bricklayer": "g07SupplyPlays",
  "op_bulk_postage": "g07SupplyPlays",
  "op_cellar_hatch": "g07SupplyPlays",
  "op_certified_letter": "g07SupplyPlays",
  "op_cloister_step": "g07SupplyPlays",
  "op_dead_letter_office": "g07SupplyPlays",
  "op_doorman": "g07SupplyPlays",
  "op_express_courier": "g07SupplyPlays",
  "op_ferry_crossing": "g07SupplyPlays",
  // g08CrowdPlays.tsx (27)
  "op_fetch_the_flour": "g08CrowdPlays",
  "op_fresh_footprints": "g08CrowdPlays",
  "op_gallery_row": "g08CrowdPlays",
  "op_goat_track": "g08CrowdPlays",
  "op_harbor_pilot": "g08CrowdPlays",
  "op_harborside_h": "g08CrowdPlays",
  "op_harborside_rider": "g08CrowdPlays",
  "op_homesick_private": "g08CrowdPlays",
  "op_homing_pigeon": "g08CrowdPlays",
  "op_parade_route": "g08CrowdPlays",
  "op_piggyback": "g08CrowdPlays",
  "op_pilgrim_road": "g08CrowdPlays",
  "op_regroup_at_camp": "g08CrowdPlays",
  "op_revolving_door": "g08CrowdPlays",
  "op_run_for_eggs": "g08CrowdPlays",
  "op_salt_from_the_coast": "g08CrowdPlays",
  "op_second_thoughts": "g08CrowdPlays",
  "op_servants_entrance": "g08CrowdPlays",
  "op_sidestep_and_bow": "g08CrowdPlays",
  "op_smugglers_lane": "g08CrowdPlays",
  "op_soups_on": "g08CrowdPlays",
  "op_spice_run": "g08CrowdPlays",
  "op_tactical_withdrawal": "g08CrowdPlays",
  "op_towpath": "g08CrowdPlays",
  "ov_growth_spurt": "g08CrowdPlays",
  "ov_pebble_toss": "g08CrowdPlays",
  "ov_tiny_trebuchet": "g08CrowdPlays",
  // g09FrostPlays.tsx (29)
  "bn4_long_winter": "g09FrostPlays",
  "bn4_winter_garrison": "g09FrostPlays",
  "bn4_frozen_moat": "g09FrostPlays",
  "bn4_glacier_calving": "g09FrostPlays",
  "hx4_blood_price": "g09FrostPlays",
  "hx4_eternal_toll": "g09FrostPlays",
  "hx4_kings_ransom": "g09FrostPlays",
  "hx4_tribute_demand": "g09FrostPlays",
  "hx4_doomsday_clock": "g09FrostPlays",
  "hx4_tolling_thirds": "g09FrostPlays",
  "ov_deus_ex_machina": "g09FrostPlays",
  "hx4_burned_keep": "g09FrostPlays",
  "hx4_oathbreakers_brand": "g09FrostPlays",
  "hx4_shattered_council": "g09FrostPlays",
  "hx4_frozen_reserves": "g09FrostPlays",
  "hx4_hearth_frost": "g09FrostPlays",
  "hx4_great_glacier": "g09FrostPlays",
  "hx4_reapers_due": "g09FrostPlays",
  "hx4_winter_that_stays": "g09FrostPlays",
  "hx4_watchmans_whistle": "g09FrostPlays",
  "hx4_wheel_of_ice": "g09FrostPlays",
  "hx4_glass_prison": "g09FrostPlays",
  "hx4_spiders_parlor": "g09FrostPlays",
  "hx4_poachers_snare": "g09FrostPlays",
  "hx4_kraken_arms": "g09FrostPlays",
  "hx4_lovestruck_majesty": "g09FrostPlays",
  "hx4_tempest": "g09FrostPlays",
  "hx4_lead_rain": "g09FrostPlays",
  "hx4_frozen_harbor": "g09FrostPlays",
  // g10ThawPlays.tsx (29)
  "bn4_winter_orders": "g10ThawPlays",
  "bn4_winter_palace": "g10ThawPlays",
  "hx4_avalanche_pass": "g10ThawPlays",
  "hx4_beartrap_cache": "g10ThawPlays",
  "hx4_black_lotus": "g10ThawPlays",
  "hx4_gale_warning": "g10ThawPlays",
  "hx4_glacier_gate": "g10ThawPlays",
  "hx4_grave_chill": "g10ThawPlays",
  "hx4_hundred_year_nap": "g10ThawPlays",
  "hx4_iron_maiden": "g10ThawPlays",
  "hx4_narcolepsy": "g10ThawPlays",
  "hx4_pillory": "g10ThawPlays",
  "hx4_silken_net": "g10ThawPlays",
  "hx4_thunderhead": "g10ThawPlays",
  "ov_frost_wyrm": "g10ThawPlays",
  "bn4_flash_frost": "g10ThawPlays",
  "bn4_grandmas_cookies": "g10ThawPlays",
  "bn4_prison_break": "g10ThawPlays",
  "hx4_ashen_bread": "g10ThawPlays",
  "hx4_clay_hooves": "g10ThawPlays",
  "hx4_cold_reception": "g10ThawPlays",
  "hx4_frost_heave": "g10ThawPlays",
  "hx4_grasping_ivy": "g10ThawPlays",
  "hx4_haunted_gallery": "g10ThawPlays",
  "hx4_silk_cocoon": "g10ThawPlays",
  "hx4_tithe_of_blood": "g10ThawPlays",
  "hx4_undertow": "g10ThawPlays",
  "ov_ghost_ship": "g10ThawPlays",
  "ov_winter_palace": "g10ThawPlays",
  // g11BrittlePlays.tsx (28)
  "bn4_cold_snap": "g11BrittlePlays",
  "hx4_bounty_posted": "g11BrittlePlays",
  "hx4_caught_mid_stride": "g11BrittlePlays",
  "hx4_creaking_gallows": "g11BrittlePlays",
  "hx4_pawnbrokers_lien": "g11BrittlePlays",
  "hx4_sagging_shelves": "g11BrittlePlays",
  "hx4_second_frost": "g11BrittlePlays",
  "bn4_glass_of_water": "g11BrittlePlays",
  "bn4_kettle_on": "g11BrittlePlays",
  "bn4_puddle_freeze": "g11BrittlePlays",
  "hx4_carrion_crows": "g11BrittlePlays",
  "hx4_heavy_dew": "g11BrittlePlays",
  "hx4_jam_on_the_row": "g11BrittlePlays",
  "hx4_the_ides": "g11BrittlePlays",
  "hx4_winded_destrier": "g11BrittlePlays",
  "bn4_warm_soup": "g11BrittlePlays",
  "hx4_cold_start": "g11BrittlePlays",
  "hx4_frost_footprints": "g11BrittlePlays",
  "hx4_hand_cramp": "g11BrittlePlays",
  "hx4_pebble_in_the_shoe": "g11BrittlePlays",
  "hx4_court_jester": "g11BrittlePlays",
  "hx4_dunce_detail": "g11BrittlePlays",
  "hx4_early_frost": "g11BrittlePlays",
  "hx4_mild_sting": "g11BrittlePlays",
  "hx4_sleepy_sentry": "g11BrittlePlays",
  "hx4_thin_ice_patch": "g11BrittlePlays",
  "op_first_frost": "g11BrittlePlays",
  "op_snowdrop": "g11BrittlePlays",
  // g12ClockworkPlays.tsx (27)
  "ov_board_of_directors": "g12ClockworkPlays",
  "ov_deja_vu": "g12ClockworkPlays",
  "bn4_genie_lamp": "g12ClockworkPlays",
  "ov_chess_boxing": "g12ClockworkPlays",
  "ov_mod_powers": "g12ClockworkPlays",
  "bn4_relay_baton": "g12ClockworkPlays",
  "ov_democracy": "g12ClockworkPlays",
  "ov_dev_console": "g12ClockworkPlays",
  "ov_nerfchess_the_musical": "g12ClockworkPlays",
  "ov_standing_ovation": "g12ClockworkPlays",
  "ov_the_tutorial": "g12ClockworkPlays",
  "ov_wish_fish": "g12ClockworkPlays",
  "ov_algorithm_boost": "g12ClockworkPlays",
  "ov_coliseum": "g12ClockworkPlays",
  "ov_fourth_wall_crew": "g12ClockworkPlays",
  "ov_insider_trading": "g12ClockworkPlays",
  "ov_prophecy_engine": "g12ClockworkPlays",
  "ov_speedhack": "g12ClockworkPlays",
  "bn4_grandfather_clock": "g12ClockworkPlays",
  "ov_golden_goose": "g12ClockworkPlays",
  "ov_midas_gauntlet": "g12ClockworkPlays",
  "ov_private_gallery": "g12ClockworkPlays",
  "ov_rage_bait": "g12ClockworkPlays",
  "ov_stack_overflow": "g12ClockworkPlays",
  "ov_vampire_court": "g12ClockworkPlays",
  "bn4_overtime_claim": "g12ClockworkPlays",
  "bn4_pocket_metronome": "g12ClockworkPlays",
  // g20RampartPlays.tsx (24)
  "bn4_dukes_patent": "g20RampartPlays",
  "bn4_wall_of_faith": "g20RampartPlays",
  "hx4_dead_march": "g20RampartPlays",
  "hx4_the_long_siege": "g20RampartPlays",
  "ov_world_serpent": "g20RampartPlays",
  "bn4_clay_colossus": "g20RampartPlays",
  "bn4_palace_walls": "g20RampartPlays",
  "bn4_castle_ditch": "g20RampartPlays",
  "bn4_dowry": "g20RampartPlays",
  "hx4_banquet_of_dust": "g20RampartPlays",
  "hx4_ivory_tower": "g20RampartPlays",
  "hx4_moat_diggers": "g20RampartPlays",
  "hx4_rusted_battlements": "g20RampartPlays",
  "hx4_wagon_ruts": "g20RampartPlays",
  "bn4_charm_bracelet": "g20RampartPlays",
  "bn4_pawn_bulwark": "g20RampartPlays",
  "bn4_town_walls": "g20RampartPlays",
  "hx4_feuding_towers": "g20RampartPlays",
  "hx4_wet_powder": "g20RampartPlays",
  "ov_siege_ladder": "g20RampartPlays",
  "bn4_causeway": "g20RampartPlays",
  "bn4_rampart_watch": "g20RampartPlays",
  "bn4_rook_nest": "g20RampartPlays",
  "hx4_crooked_arrow": "g20RampartPlays",
  // g22VeilPlays.tsx (21)
  "hx4_great_waltz": "g22VeilPlays",
  "hx4_donkey_ears": "g22VeilPlays",
  "hx4_eclipse": "g22VeilPlays",
  "hx4_falling_rubble": "g22VeilPlays",
  "hx4_glass_floor": "g22VeilPlays",
  "hx4_the_long_night": "g22VeilPlays",
  "ov_big_nap": "g22VeilPlays",
  "bn4_hourglass_throne": "g22VeilPlays",
  "bn4_tithe_of_time": "g22VeilPlays",
  "hx4_white_flag_hour": "g22VeilPlays",
  "bn4_smoke_break_union": "g22VeilPlays",
  "bn4_stolen_hour": "g22VeilPlays",
  "hx4_court_in_session": "g22VeilPlays",
  "hx4_drawn_curtain": "g22VeilPlays",
  "hx4_lockstep": "g22VeilPlays",
  "hx4_night_ledger": "g22VeilPlays",
  "hx4_night_watch_rota": "g22VeilPlays",
  "hx4_censors_ink": "g22VeilPlays",
  "hx4_moth_eaten_gloves": "g22VeilPlays",
  "hx4_night_soil": "g22VeilPlays",
  "hx4_slack_bowstrings": "g22VeilPlays",
  // g26ShieldPlays.tsx (32)
  "bn4_age_of_peace": "g26ShieldPlays",
  "bn4_guardian_of_the_line": "g26ShieldPlays",
  "bn4_saints_procession": "g26ShieldPlays",
  "bn4_warding_circle": "g26ShieldPlays",
  "ov_plot_armor": "g26ShieldPlays",
  "bn4_ancestral_shield": "g26ShieldPlays",
  "bn4_shieldmaidens": "g26ShieldPlays",
  "bn4_bodyguard_detail": "g26ShieldPlays",
  "bn4_color_guard": "g26ShieldPlays",
  "bn4_old_guard": "g26ShieldPlays",
  "bn4_confetti_cannon": "g26ShieldPlays",
  "bn4_quilted_armor": "g26ShieldPlays",
  "bn4_boundary_stones": "g26ShieldPlays",
  "bn4_pocket_shield": "g26ShieldPlays",
  "op_alley_cat": "g26ShieldPlays",
  "op_cloister_bell": "g26ShieldPlays",
  "op_debutante_ball": "g26ShieldPlays",
  "op_first_day_badge": "g26ShieldPlays",
  "op_gallery_docent": "g26ShieldPlays",
  "op_lady_in_waiting": "g26ShieldPlays",
  "op_lighthouse_keeper": "g26ShieldPlays",
  "op_ordination_day": "g26ShieldPlays",
  "op_parade_marshal": "g26ShieldPlays",
  "op_riding_certificate": "g26ShieldPlays",
  "op_stable_groom": "g26ShieldPlays",
  "op_stage_armor": "g26ShieldPlays",
  "op_tower_inspection": "g26ShieldPlays",
  "op_victory_lap": "g26ShieldPlays",
  "ov_traffic_cone": "g26ShieldPlays",
  "bn4_doorstop": "g26ShieldPlays",
  "op_guardian_sprite": "g26ShieldPlays",
  "ov_wet_paint": "g26ShieldPlays",
  // g27ThornPlays.tsx (27)
  "hx4_echo_chamber": "g27ThornPlays",
  "hx4_iron_ring": "g27ThornPlays",
  "hx4_maze_of_thorns": "g27ThornPlays",
  "hx4_sealed_meridian": "g27ThornPlays",
  "ov_terraform": "g27ThornPlays",
  "bn4_sting_of_the_wasp": "g27ThornPlays",
  "hx4_signal_jam": "g27ThornPlays",
  "bn4_keep_gate": "g27ThornPlays",
  "hx4_ford_crossing": "g27ThornPlays",
  "hx4_no_homecoming": "g27ThornPlays",
  "hx4_no_return": "g27ThornPlays",
  "hx4_tar_pits": "g27ThornPlays",
  "hx4_fresh_crater": "g27ThornPlays",
  "hx4_prowlers_bell": "g27ThornPlays",
  "hx4_bramble_patch": "g27ThornPlays",
  "hx4_restless_blades": "g27ThornPlays",
  "hx4_rope_bridge": "g27ThornPlays",
  "bn4_thorn_hedge": "g27ThornPlays",
  "hx4_gnat_cloud": "g27ThornPlays",
  "hx4_house_arrest": "g27ThornPlays",
  "op_garden_door": "g27ThornPlays",
  "op_garden_scarecrow": "g27ThornPlays",
  "ov_loose_floorboard": "g27ThornPlays",
  "bn4_garden_fence": "g27ThornPlays",
  "hx4_buttoned_scabbard": "g27ThornPlays",
  "op_garden_gate": "g27ThornPlays",
  "op_garden_hedge": "g27ThornPlays",
  // g29RallyPlays.tsx (24)
  "ov_elder_wyrm": "g29RallyPlays",
  "bn4_house_of_banners": "g29RallyPlays",
  "ov_symphony_of_the_legion": "g29RallyPlays",
  "bn4_life_insurance": "g29RallyPlays",
  "hx4_siren_song": "g29RallyPlays",
  "bn4_forward_banners": "g29RallyPlays",
  "bn4_war_room_map": "g29RallyPlays",
  "hx4_soggy_invaders": "g29RallyPlays",
  "hx4_elbow_room": "g29RallyPlays",
  "hx4_moths_in_the_banner": "g29RallyPlays",
  "ov_moat_digger": "g29RallyPlays",
  "ov_second_breakfast": "g29RallyPlays",
  "op_bridle_path": "g29RallyPlays",
  "op_drawbridge_in": "g29RallyPlays",
  "op_edge_of_the_map": "g29RallyPlays",
  "op_freight_elevator": "g29RallyPlays",
  "op_grand_march": "g29RallyPlays",
  "op_harbor_walk": "g29RallyPlays",
  "op_old_post_road": "g29RallyPlays",
  "op_palace_gate": "g29RallyPlays",
  "op_quickstep": "g29RallyPlays",
  "op_squires_errand": "g29RallyPlays",
  "op_team_photo": "g29RallyPlays",
  "op_waltz_left": "g29RallyPlays",
  // g31ChancePlays.tsx (20)
  "bn4_costume_trunk": "g31ChancePlays",
  "bn4_bottled_courage": "g31ChancePlays",
  "hx4_ferrymans_coin": "g31ChancePlays",
  "bn4_rubber_duck": "g31ChancePlays",
  "bn4_lucky_coin": "g31ChancePlays",
  "op_chairs_on_tables": "g31ChancePlays",
  "op_crystal_ball": "g31ChancePlays",
  "op_dowsing_rod": "g31ChancePlays",
  "op_evil_eye_bead": "g31ChancePlays",
  "op_fools_gold": "g31ChancePlays",
  "op_four_leaf_clover": "g31ChancePlays",
  "op_gossip_charm": "g31ChancePlays",
  "op_horseshoe_nail": "g31ChancePlays",
  "op_private_booth": "g31ChancePlays",
  "op_rabbits_foot": "g31ChancePlays",
  "op_starboard_chart": "g31ChancePlays",
  "op_sunday_best": "g31ChancePlays",
  "op_tea_leaves": "g31ChancePlays",
  "op_wishbone": "g31ChancePlays",
  "ov_lucky_penny": "g31ChancePlays",
};
// </card-modules:generated>

// <plugin-ids:generated>
export const PLUGIN_IDS: readonly string[] = [
  // basicPlays.tsx (296)
  "cornerstone", "firm_footing", "guarded_king", "holy_hell", "loose_pawn", "pawn_shield",
  "steady_hand", "bulwark", "fork_guard", "reinforce", "screen", "shielded_advance",
  "sidestep_king", "chain_mail", "deflect", "fortress", "iron_bishop", "phalanx",
  "wa_sigil_ward", "duelist", "hold_the_bridge", "iron_wall", "shieldmaiden", "warding_circle",
  "watermelon_rind", "ww_high_ground", "butterfingers", "cold_feet", "crossed_wires", "foggy_glasses",
  "royal_restraint", "stage_fright", "blunted_lance", "lame_horses", "rusted_hinges", "safe_passage",
  "timid_king", "sown_salt", "wc_backseat_driver", "atomic_captures_small", "hex_doll", "wc_butterfingers",
  "we_backdraft", "cold_open", "heavy_boots", "knock_knees", "molasses", "slippery_grip",
  "stiff_joints", "anchor", "butter_bishops", "leaden_queen", "seized_axles", "short_leash",
  "trench_line", "anchored_rooks", "blinkered_bishops", "leaden_crown", "magnet", "pawn_nerf",
  "spooked_steeds", "we_static_field", "abandoned_post", "blockade", "frozen_furrows", "heavy_shackles",
  "wc_quicksand_patch", "cold_snap", "hard_reset", "pinned_down", "we_frost_nip", "frost",
  "frostbite", "snap_freeze", "twist_the_knife", "wa_stasis_field", "wall", "wc_clumsy_dash",
  "wc_slip_on_ice", "wc_stage_fright", "cascade_freeze", "cryostasis", "hard_frost", "immobilizer",
  "wa_bind_the_queen", "ww_counter_charge", "gargoyles", "stone_hooves", "gorgons_glance", "hobbled_cavalry",
  "petrified_towers", "granite_towers", "ironbound_rook", "statue_stable", "stone_clergy", "ferz_king",
  "half_step", "loyal_pawn", "quiet_march", "rook_slide", "sentinel_pawn", "sidestep",
  "tempo_shuffle", "ghost_pawn", "pawn_push", "phase_rook", "reposition", "wazir_rook",
  "we_thunder_step", "grasshopper", "promote_now", "queens_echo", "rank_runner", "vanguard",
  "wa_transmute", "we_ball_lightning", "we_riverflow", "ww_phalanx_advance", "changeling", "kingslide",
  "royal_decree", "wa_arcane_conduit", "bishop_polish", "diagonal_step", "little_leap", "nudge",
  "camel_knight", "long_knight", "mind_nudge", "rally", "spring_pawn", "teleport_knight",
  "vault", "wazir_bishop", "wc_kangaroo_hop", "we_updraft", "bishop_archbishop", "board_quake",
  "cannon", "dragon_pawn", "hunter_knight", "knight_nightrook", "overclock", "rook_chancellor",
  "sliding_king", "tidal_push", "trampoline", "wa_ghostwalk_bishop", "ww_flank_march", "ww_forced_retreat",
  "ww_pontoon_bridge", "ww_war_wagon", "firecracker", "giant_slayer", "overrun", "twin_knights",
  "wa_camel_rider", "steady_march", "counterstep", "double_step_army", "pawn_storm", "ww_pikemen",
  "berolina_pawns", "momentum", "split_march", "wc_moonwalk", "army_reversal", "solstice",
  "wc_chaos_reigns", "ww_field_fortification", "cut_purse", "sealed_orders", "royal_duty", "wa_suppress_magic",
  "wc_red_tape", "burned_dispatches", "chain_nullify", "dead_letter", "mirror", "patch_notes",
  "suppress", "wa_disrupt_ritual", "wa_jinx", "prep", "trade_up", "buff_thief_minor",
  "heros_journey", "recast", "wa_disjunction", "extra_glance", "peek", "quick_glance",
  "scout", "watchtower", "draft_insight", "oracles_eye", "third_eye", "north_star",
  "wa_foresight", "wa_mind_read", "wa_omniscience", "castle_early", "drawbridge", "toll_gate",
  "long_castle_anywhere", "no_mans_land", "wc_shy_pieces", "board_lock", "bunker", "no_trespass",
  "flypaper_file", "sealed_gate", "second_wind", "minor_recall", "we_regrow", "ww_field_hospital",
  "ww_reclaim_the_fallen", "seance", "second_wind_major", "will_o_wisp", "ww_last_reserves", "resurrect",
  "resurrect_major", "wc_lost_and_found", "ww_recommission", "walnut_shell", "apple", "banana_peel",
  "coconut_bonk", "kings_guard", "bodyguard", "split_bishop", "ww_sapper_team", "coffee",
  "comet_shard", "wa_conjure_bishop", "ww_shieldbearers", "wasted_hour", "lost_weekend", "wa_borrowed_minute",
  "deep_breath", "reprieve", "small_mercies", "defiance", "held_breath", "hunters_relief",
  "slack_chain", "break_the_nerf", "grace_period", "timely_lull", "underdogs_grit", "adrenaline",
  "counter_nerf", "respite", "durian", "pixie_dust", "seelie_blessing", "we_bramble_wall",
  "we_creeping_roots", "we_seedlings", "faerie_ring", "pucks_mischief", "we_ancient_grove", "escape_hatch",
  "piece_swap", "recall", "ww_regroup_lines", "guard_rotation", "wa_blink", "warp_home",
  "warp_step", "blink_army", "grand_recall", "mass_recall", "regroup", "total_recall",
  "wa_swap_flanks", "warp_field", "warp_reign", "warp_rook", "we_riptide", "we_undertow",
  "regenerate", "summon_knight", "wa_conjure_scout", "ww_outriders", "mass_resurrect", "phantom_rook",
  "ww_forward_observer", "ww_reserve_cavalry", "glamour", "piece_steal", "wa_dominate_minor", "wc_body_double",
  "ww_defectors", "ww_mass_defection",
  // godPlays.tsx (68)
  "draft_tyranny", "sovereign_draft", "draft_supremacy", "divine_legion", "absolute_aegis", "checkmate_denial",
  "full_pardon", "transcendence", "mind_empire", "mass_mind_control", "throne_and_silence", "abdication_edict",
  "wa_dominate_major", "great_divide", "sundering", "fortress_realm", "molten_heart", "salted_earth",
  "unshackled_wrath", "phoenix_line", "chain_atomic", "total_atomic", "scorched_earth", "rift_storm",
  "queen_storm", "buff_plunder", "total_plunder", "grand_nullify", "absolute_nullify", "endless_night",
  "peace_of_the_grave", "withered_hands", "grand_malediction", "blighted_furrows", "culling", "poisoned_counsel",
  "age_of_heroes", "grand_retreat", "noble_rout", "sacked_capital", "genesis", "reality_warp",
  "total_warp", "warp_cataclysm", "warp_sovereign", "nerf_reversal", "celestial_alignment", "grand_conjunction",
  "glacial_tomb", "frozen_solid", "absolute_zero", "everfrost_shard", "ban_hammer", "dragonslayer",
  "world_lock", "sealed_archive", "sealed_ramparts", "leaden_limbs", "walnut_court", "obsidian_bastions",
  "statue_garden", "cockatrice_gaze", "chisel_curse", "crown_and_castle", "full_rewind", "endless_turn",
  "lost_fortnight", "sabbatical",
  // greatPlays.tsx (115)
  "ball_and_chain", "royal_summons", "palsied_hands", "throne_bound", "lone_sovereign", "peasant_levy",
  "court_in_exile", "cast_a_nerf", "royal_handicap", "queens_handicap", "grounded_command", "lunar_eclipse",
  "hexed_satchel", "iron_furrow", "leaden_fields", "wc_voodoo_doll", "wc_sticky_floor", "threads_of_fate",
  "mind_control", "mind_dominion", "medusas_verdict", "granite_ramparts", "stone_menagerie", "stone_curse",
  "stone_riders", "stone_prelates", "stone_bastions", "queen_of_stone", "eternal_statue", "nerf_hammer",
  "the_big_chill", "frozen_moment", "creeping_frost", "glacial_flanks", "total_whiteout", "we_frostbite_curse",
  "total_freeze", "atomic_captures", "atomic_reaction", "detonation_field", "ww_demolition_charge", "wc_confetti_cannon",
  "we_firestorm", "giants_maul", "scorched_middle", "checkmate_immunity", "iron_reign", "ironclad",
  "ww_iron_bulwark", "ww_praetorian_guard", "round_table", "ww_bridgehead", "sealed_avenues", "dryad_grove",
  "we_overgrowth", "we_rooted", "we_quagmire", "thorn_hedge", "gossamer_veil", "starlight_ward",
  "spirit_guide", "phase_army", "ghost_legion", "valkyrie", "extra_move_repeat", "time_stop_short",
  "time_rewind", "lost_days", "wa_stolen_hours", "sever", "draft_domination", "total_nullify",
  "favorable_stars", "the_tower", "death_arcana", "chess_diff", "wa_greed", "riddle_game",
  "rehab", "parole", "long_leash", "wardens_bribe", "iron_will", "wc_wrong_way",
  "wc_broken_elevator", "unseelie_bargain", "buff_thief", "buff_siphon", "wa_spelltheft", "draft_seize",
  "collapse", "void", "wa_sabotage", "empty_handed", "double_queen", "twin_queens",
  "promotion_storm", "mass_promote_minor", "resurrect_queen", "legendary_forge", "royal_ascension", "second_king",
  "wa_leaden_crown", "overclock_major", "ascendant_knight", "nerf_breaker", "fey_step", "rift_walker",
  "mirror_of_souls", "wa_conjure_rook", "wa_twin_familiars", "ley_line", "wild_hunt", "dragon_mount",
  "sahur",
  // funnyPlays.tsx (16)
  "emotional_support_pawn", "stream_sniper", "lag_spike", "ctrl_z", "rubber_chicken", "day_one_patch",
  "battle_pass", "pop_up_ad", "mute_button", "skill_issue", "alt_f4", "touch_grass",
  "main_character", "smurf_account", "pay_to_win", "expansion_permit",
  // personalPlays.tsx (20)
  "muscle_up", "bench_225", "handstand_pushup", "full_planche", "fingertip_maltese", "onearmmuscleupismydream",
  "monkeytype", "rubiks_cube", "ilovewhimperingaudios", "ilovemakingout", "ilovechaewon", "hyein",
  "minji", "hanni", "danielle", "haerin", "i_love_cam", "daniel_caesar",
  "middle_part", "forearm_veins",
  // memePlays.tsx (9)
  "cappuccino_assassino", "ballerina_cappuccina", "la_vaca_saturno_saturnita", "frigo_camelo", "trippi_troppi", "chill_guy",
  "moai_head", "skibidi_flush", "tung_tung_sahur",
  // stubPlays.tsx (8)
  "free_retreat", "rewind_one", "shadow_step", "pin_breaker", "decoy", "loosen_the_leash",
  "piece_parole", "half_measure",
  // prankPlays.tsx (9)
  "pr_phishing", "pr_donation_alert", "pr_bsod", "pr_forced_update", "pr_defender_scan", "pr_captcha",
  "pr_popup_storm", "pr_chain_letter", "pr_ratiod",
  // casinoPlays.tsx (7)
  "cs_slot_machine", "cs_roulette", "cs_blackjack", "cs_scratch_card", "cs_let_it_ride", "cs_loot_box",
  "cs_poker_bluff",
  // gamblingPlays.tsx (28)
  "gm_penny_slots", "gm_heads_or_tails", "gm_claw_machine", "gm_raffle_ticket", "gm_card_counting", "gm_loaded_dice",
  "gm_lootbox", "gm_three_card_monte", "gm_underdog_parlay", "gm_river_card", "gm_piece_roulette", "gm_jackpot_pawn",
  "gm_double_down_draft", "gm_crash_game", "gm_blood_wager", "gm_progressive_jackpot", "gm_the_house", "gm_gacha_banner",
  "gm_seven_cases", "gm_martingale", "gm_devils_deck", "gm_break_the_bank", "gm_wheel_of_the_cosmos", "gm_cursed_dice",
  "gm_rigged_raffle", "gm_consolation_scratcher", "gm_hardship_jackpot", "gm_the_last_bet",
  // boonPlays.tsx (72)
  "bw2_ancient_custom", "bw2_hit_and_run", "bw2_cornered_king", "bw2_blood_duel", "bw2_divine_right", "bw2_pioneers_banner",
  "bw2_diplomatic_immunity", "bw2_deathless_oath", "bw2_spoils_of_war", "bw2_prisoner_exchange", "bw2_highwaymans_toll", "bw2_queens_testament",
  "bw2_scarecrow", "bw2_masquerade", "bw2_alchemists_trade", "bw2_early_coronation", "bw2_standard_bearer", "bw2_ascetics_bargain",
  "bw2_jesters_rule", "bw2_blood_price", "bw2_kingmakers_pact", "bw2_bolt_hole", "bw2_carnival_of_masks", "bw2_restitution",
  "bw2_long_truce", "bw2_great_return", "bw2_shadow_reserve", "bw2_eternal_keep", "bw3_forced_march", "bw3_royal_caper",
  "bw3_tunnelers", "bw3_rally_royal", "bw3_underdogs_gambit", "bw3_bishops_blessing", "bw3_shield_wall", "bw3_kings_shield",
  "bw3_praetorian", "bw3_watchword", "bw3_vantage_point", "bw3_hallowed_ground", "bw3_first_blood", "bw3_postern_gate",
  "bw3_coronation_bonus", "bw3_plunderers_ledger", "bw3_eleventh_hour", "bw3_deep_position", "bw3_martyrs_gift", "bw3_heir_apparent",
  "bw3_field_knighting", "bw3_battlefield_commission", "bw3_ironwrights_bargain", "bw3_second_face", "bw3_home_guard", "bw3_double_down",
  "bw3_kings_road", "bw3_futures_market", "bw3_castle_in_the_storm", "bw3_last_muster", "bw3_funeral_pyre", "bw3_mummers_dance",
  "bw3_last_stand", "bw3_high_stakes", "bw3_from_the_ashes", "bw3_kingsguard_duel", "bw3_kings_sanctuary", "bw3_martyrdom",
  "bw3_the_reckoning", "bw3_covenant_of_return", "bw3_the_homecoming", "bw3_turn_the_tide", "bw3_pretender", "bw3_drive_them_out",
  // cursePlays.tsx (67)
  "hw2_witchs_veto", "hw2_long_road_home", "hw2_blood_price", "hw2_tarnished_crown", "hw2_war_rations", "hw2_compounding_misery",
  "hw2_bad_omen", "hw2_tolling_bell", "hw2_witching_hour", "hw2_weight_of_toil", "hw2_cold_footprints", "hw2_creeping_blight",
  "hw2_gravebloom", "hw2_gathering_storm", "hw2_twinned_torment", "hw2_no_reins", "hw2_curse_of_recoil", "hw2_queens_ransom",
  "hw2_bound_court", "hw2_cursed_coin", "hw2_gilded_rot", "hw2_death_knell", "hw2_hollow_crown", "hw2_tide_of_ash",
  "hw2_crown_of_thorns", "hw2_pauper_crown", "hw2_beacon_of_woe", "hw3_wrong_foot", "hw3_overexertion", "hw3_toll_road",
  "hw3_bloodlust", "hw3_exiles_mark", "hw3_debtors_mark", "hw3_coronation_tax", "hw3_pilgrimage", "hw3_bounty_mark",
  "hw3_feeding_frenzy", "hw3_slow_poison", "hw3_jammed_castle", "hw3_time_bomb", "hw3_collapsing_floor", "hw3_doomed_vow",
  "hw3_wandering_sentry", "hw3_sinking_mire", "hw3_miasma", "hw3_roaming_void", "hw3_wildfire", "hw3_effigy_of_dread",
  "hw3_avalanche", "hw3_binding_oath", "hw3_bloodbond", "hw3_shared_fate", "hw3_kings_guard", "hw3_no_retreat",
  "hw3_fifth_column", "hw3_curse_hop", "hw3_mutiny", "hw3_defectors_mark", "hw3_aging_blade", "hw3_enemy_within",
  "hw3_eclipse", "hw3_hydra_hex", "hw3_pyrrhic_toll", "hw3_martyrs_crown", "hw3_curse_engine", "hw3_blood_tithe",
  "hw3_inverted_crown",
  // creatorPlays.tsx (5)
  "cr_stalling_bishop", "cr_oh_no_my_queen", "cr_family_game_night", "cr_speedrun_protocol", "cr_chat_picks",
  // g01HourglassPlays.tsx (32)
  "bn4_council_of_peace", "bn4_great_armistice", "bn4_hundred_year_lease", "bn4_royal_we", "hx4_royal_lockdown", "hx4_tithe_of_silence",
  "bn4_liberators_march", "bn4_escape_artist", "bn4_jubilee", "bn4_keys_to_the_city", "bn4_royal_privilege", "bn4_midas_charter",
  "bn4_year_of_jubilee", "bn4_hundred_days", "bn4_debtors_holiday", "bn4_crown_jubilee", "bn4_meek_inherit", "bn4_unequal_treaty",
  "bn4_grand_bargain", "bn4_patrons_favor", "bn4_queens_aegis", "bn4_masked_ball", "bn4_flag_on_their_wall", "bn4_siege_mentality",
  "bn4_champions_rest", "bn4_half_moon_charter", "bn4_moonlit_reprieve", "bn4_pact_of_the_dawn", "bn4_second_spring", "hx4_debt_of_crowns",
  "hx4_last_toll", "ov_time_heist",
  // g02SchedulePlays.tsx (32)
  "bn4_uphill_battle", "bn4_wardens_retirement", "hx4_iron_portcullis", "ov_patient_grift", "bn4_diplomatic_pouch", "bn4_double_pardon",
  "bn4_guards_change", "bn4_hidden_clause", "bn4_hollow_crown", "bn4_long_holiday", "bn4_masons_lodge", "bn4_ministers_seal",
  "bn4_out_on_bail", "bn4_pillars_of_home", "bn4_quiet_coup", "bn4_relief_column", "bn4_rule_of_three", "bn4_spymasters_leave",
  "bn4_tower_toll", "hx4_sleepwalkers", "bn4_gentlemens_agreement", "bn4_harvest_and_fallow", "bn4_heavy_price", "bn4_kings_indulgence",
  "bn4_leave_of_absence", "bn4_open_season", "bn4_retraining", "bn4_royal_household", "bn4_royal_writ", "bn4_salt_in_the_wound",
  "bn4_scapegoat", "bn4_veterans_pension",
  // g03CelestialPlays.tsx (32)
  "hx4_the_bell_tolls", "ov_managers_challenge", "ov_nesting_doll", "bn4_bread_and_salt", "bn4_clerical_error", "bn4_coronation_rest",
  "bn4_furlough", "bn4_general_strike", "bn4_harvest_rest", "bn4_hidden_stair", "bn4_hold_the_door", "bn4_home_square",
  "bn4_listening_post", "bn4_paid_leave", "bn4_scaffold_crane", "bn4_second_skin", "bn4_seven_league_boots", "bn4_worry_beads",
  "hx4_coronation_bill", "ov_sleeping_draught", "bn4_bottom_of_the_well", "bn4_bribe_the_clerk", "bn4_dragonslayer", "bn4_forty_winks",
  "bn4_hermits_hour", "bn4_hush_money", "bn4_lone_crown", "bn4_over_the_shoulder", "bn4_over_the_wall", "bn4_pawns_ransom",
  "bn4_rest_stop", "bn4_sparring_rhythm",
  // g04PatinaPlays.tsx (29)
  "bn4_visor_down", "bn4_angelus_bell", "bn4_barter_calm", "bn4_cold_compress", "bn4_dowagers_patience", "bn4_ear_to_the_ground",
  "bn4_hourglass_flip", "bn4_knights_vigil", "bn4_measured_breath", "bn4_pawns_lullaby", "bn4_saints_day", "bn4_sleepy_dust",
  "bn4_slipped_collar", "bn4_spring_in_the_step", "bn4_steady_hands", "bn4_trophy_rest", "ov_loan_shark", "bn4_castle_quiet",
  "bn4_check_valve", "bn4_crowned_calm", "bn4_first_light", "bn4_grace_note", "bn4_kind_omen", "bn4_morning_stretch",
  "bn4_promise_of_rest", "bn4_quiet_after", "bn4_shared_silence", "bn4_small_ritual", "bn4_two_breaths",
  // g05PawnTidePlays.tsx (30)
  "bn4_endless_militia", "bn4_menagerie_gates", "bn4_drawbridge_crew", "bn4_field_hospital", "bn4_letters_home", "bn4_small_consolation",
  "bn4_stray_cat", "bn4_florists_trick", "bn4_changeling_child", "hx4_field_of_spears", "bn4_leapfrog", "ov_rapture_of_pawns",
  "bn4_matryoshka_surprise", "ov_trojan_pawn", "ov_great_migration", "hx4_famine_year", "hx4_pawn_embargo", "hx4_famine",
  "hx4_no_doubling", "hx4_one_ladle_each", "hx4_pied_piper", "hx4_echo_of_bells", "hx4_candle_curfew", "hx4_understudy_rule",
  "ov_pied_piper", "ov_cloud_serpent", "ov_locust_swarm", "ov_volcanic_vent", "ov_fireworks_barge", "ov_boomerang",
  // g06GroundPlays.tsx (30)
  "ov_growth_ring", "ov_mole_tunnels", "bn4_cobblers_bench", "bn4_coffee_break", "bn4_ferry_ticket", "bn4_militia_call",
  "bn4_over_the_hedge", "bn4_stowaway", "hx4_fear_of_open_ground", "ov_pillow_fort", "ov_sandbags", "bn4_day_laborer",
  "bn4_field_stitches", "bn4_half_step_back", "bn4_slow_doors", "bn4_spare_button", "bn4_vaulting_pole", "hx4_bridge_toll",
  "hx4_clumsy_heralds", "hx4_no_trampling", "hx4_pawn_snob", "hx4_vegetarian_vows", "hx4_wet_matches", "op_back_to_barracks",
  "op_chapel_warden", "op_corduroy_road", "op_downtown_premium", "op_frontier_waiver", "op_full_coverage", "op_harbor_gull",
  // g07SupplyPlays.tsx (30)
  "op_homestead_clause", "op_leapfrog_lesson", "op_market_dog", "op_sandbag_hurdle", "op_threshold_blessing", "op_trellis",
  "ov_masterclass", "ov_sock_slide", "ov_tandem_bike", "ov_wheelbarrow", "ov_whittle", "bn4_muddy_boots",
  "bn4_pawn_umbrella", "bn4_shoelace_knot", "hx4_cold_porridge", "hx4_heavy_pockets", "hx4_hopscotch", "hx4_polite_infantry",
  "op_airmail", "op_back_alley", "op_bread_for_the_table", "op_bricklayer", "op_bulk_postage", "op_cellar_hatch",
  "op_certified_letter", "op_cloister_step", "op_dead_letter_office", "op_doorman", "op_express_courier", "op_ferry_crossing",
  // g08CrowdPlays.tsx (27)
  "op_fetch_the_flour", "op_fresh_footprints", "op_gallery_row", "op_goat_track", "op_harbor_pilot", "op_harborside_h",
  "op_harborside_rider", "op_homesick_private", "op_homing_pigeon", "op_parade_route", "op_piggyback", "op_pilgrim_road",
  "op_regroup_at_camp", "op_revolving_door", "op_run_for_eggs", "op_salt_from_the_coast", "op_second_thoughts", "op_servants_entrance",
  "op_sidestep_and_bow", "op_smugglers_lane", "op_soups_on", "op_spice_run", "op_tactical_withdrawal", "op_towpath",
  "ov_growth_spurt", "ov_pebble_toss", "ov_tiny_trebuchet",
  // g09FrostPlays.tsx (29)
  "bn4_long_winter", "bn4_winter_garrison", "bn4_frozen_moat", "bn4_glacier_calving", "hx4_blood_price", "hx4_eternal_toll",
  "hx4_kings_ransom", "hx4_tribute_demand", "hx4_doomsday_clock", "hx4_tolling_thirds", "ov_deus_ex_machina", "hx4_burned_keep",
  "hx4_oathbreakers_brand", "hx4_shattered_council", "hx4_frozen_reserves", "hx4_hearth_frost", "hx4_great_glacier", "hx4_reapers_due",
  "hx4_winter_that_stays", "hx4_watchmans_whistle", "hx4_wheel_of_ice", "hx4_glass_prison", "hx4_spiders_parlor", "hx4_poachers_snare",
  "hx4_kraken_arms", "hx4_lovestruck_majesty", "hx4_tempest", "hx4_lead_rain", "hx4_frozen_harbor",
  // g10ThawPlays.tsx (29)
  "bn4_winter_orders", "bn4_winter_palace", "hx4_avalanche_pass", "hx4_beartrap_cache", "hx4_black_lotus", "hx4_gale_warning",
  "hx4_glacier_gate", "hx4_grave_chill", "hx4_hundred_year_nap", "hx4_iron_maiden", "hx4_narcolepsy", "hx4_pillory",
  "hx4_silken_net", "hx4_thunderhead", "ov_frost_wyrm", "bn4_flash_frost", "bn4_grandmas_cookies", "bn4_prison_break",
  "hx4_ashen_bread", "hx4_clay_hooves", "hx4_cold_reception", "hx4_frost_heave", "hx4_grasping_ivy", "hx4_haunted_gallery",
  "hx4_silk_cocoon", "hx4_tithe_of_blood", "hx4_undertow", "ov_ghost_ship", "ov_winter_palace",
  // g11BrittlePlays.tsx (28)
  "bn4_cold_snap", "hx4_bounty_posted", "hx4_caught_mid_stride", "hx4_creaking_gallows", "hx4_pawnbrokers_lien", "hx4_sagging_shelves",
  "hx4_second_frost", "bn4_glass_of_water", "bn4_kettle_on", "bn4_puddle_freeze", "hx4_carrion_crows", "hx4_heavy_dew",
  "hx4_jam_on_the_row", "hx4_the_ides", "hx4_winded_destrier", "bn4_warm_soup", "hx4_cold_start", "hx4_frost_footprints",
  "hx4_hand_cramp", "hx4_pebble_in_the_shoe", "hx4_court_jester", "hx4_dunce_detail", "hx4_early_frost", "hx4_mild_sting",
  "hx4_sleepy_sentry", "hx4_thin_ice_patch", "op_first_frost", "op_snowdrop",
  // g12ClockworkPlays.tsx (27)
  "ov_board_of_directors", "ov_deja_vu", "bn4_genie_lamp", "ov_chess_boxing", "ov_mod_powers", "bn4_relay_baton",
  "ov_democracy", "ov_dev_console", "ov_nerfchess_the_musical", "ov_standing_ovation", "ov_the_tutorial", "ov_wish_fish",
  "ov_algorithm_boost", "ov_coliseum", "ov_fourth_wall_crew", "ov_insider_trading", "ov_prophecy_engine", "ov_speedhack",
  "bn4_grandfather_clock", "ov_golden_goose", "ov_midas_gauntlet", "ov_private_gallery", "ov_rage_bait", "ov_stack_overflow",
  "ov_vampire_court", "bn4_overtime_claim", "bn4_pocket_metronome",
  // g20RampartPlays.tsx (24)
  "bn4_dukes_patent", "bn4_wall_of_faith", "hx4_dead_march", "hx4_the_long_siege", "ov_world_serpent", "bn4_clay_colossus",
  "bn4_palace_walls", "bn4_castle_ditch", "bn4_dowry", "hx4_banquet_of_dust", "hx4_ivory_tower", "hx4_moat_diggers",
  "hx4_rusted_battlements", "hx4_wagon_ruts", "bn4_charm_bracelet", "bn4_pawn_bulwark", "bn4_town_walls", "hx4_feuding_towers",
  "hx4_wet_powder", "ov_siege_ladder", "bn4_causeway", "bn4_rampart_watch", "bn4_rook_nest", "hx4_crooked_arrow",
  // g22VeilPlays.tsx (21)
  "hx4_great_waltz", "hx4_donkey_ears", "hx4_eclipse", "hx4_falling_rubble", "hx4_glass_floor", "hx4_the_long_night",
  "ov_big_nap", "bn4_hourglass_throne", "bn4_tithe_of_time", "hx4_white_flag_hour", "bn4_smoke_break_union", "bn4_stolen_hour",
  "hx4_court_in_session", "hx4_drawn_curtain", "hx4_lockstep", "hx4_night_ledger", "hx4_night_watch_rota", "hx4_censors_ink",
  "hx4_moth_eaten_gloves", "hx4_night_soil", "hx4_slack_bowstrings",
  // g26ShieldPlays.tsx (32)
  "bn4_age_of_peace", "bn4_guardian_of_the_line", "bn4_saints_procession", "bn4_warding_circle", "ov_plot_armor", "bn4_ancestral_shield",
  "bn4_shieldmaidens", "bn4_bodyguard_detail", "bn4_color_guard", "bn4_old_guard", "bn4_confetti_cannon", "bn4_quilted_armor",
  "bn4_boundary_stones", "bn4_pocket_shield", "op_alley_cat", "op_cloister_bell", "op_debutante_ball", "op_first_day_badge",
  "op_gallery_docent", "op_lady_in_waiting", "op_lighthouse_keeper", "op_ordination_day", "op_parade_marshal", "op_riding_certificate",
  "op_stable_groom", "op_stage_armor", "op_tower_inspection", "op_victory_lap", "ov_traffic_cone", "bn4_doorstop",
  "op_guardian_sprite", "ov_wet_paint",
  // g27ThornPlays.tsx (27)
  "hx4_echo_chamber", "hx4_iron_ring", "hx4_maze_of_thorns", "hx4_sealed_meridian", "ov_terraform", "bn4_sting_of_the_wasp",
  "hx4_signal_jam", "bn4_keep_gate", "hx4_ford_crossing", "hx4_no_homecoming", "hx4_no_return", "hx4_tar_pits",
  "hx4_fresh_crater", "hx4_prowlers_bell", "hx4_bramble_patch", "hx4_restless_blades", "hx4_rope_bridge", "bn4_thorn_hedge",
  "hx4_gnat_cloud", "hx4_house_arrest", "op_garden_door", "op_garden_scarecrow", "ov_loose_floorboard", "bn4_garden_fence",
  "hx4_buttoned_scabbard", "op_garden_gate", "op_garden_hedge",
  // g29RallyPlays.tsx (24)
  "ov_elder_wyrm", "bn4_house_of_banners", "ov_symphony_of_the_legion", "bn4_life_insurance", "hx4_siren_song", "bn4_forward_banners",
  "bn4_war_room_map", "hx4_soggy_invaders", "hx4_elbow_room", "hx4_moths_in_the_banner", "ov_moat_digger", "ov_second_breakfast",
  "op_bridle_path", "op_drawbridge_in", "op_edge_of_the_map", "op_freight_elevator", "op_grand_march", "op_harbor_walk",
  "op_old_post_road", "op_palace_gate", "op_quickstep", "op_squires_errand", "op_team_photo", "op_waltz_left",
  // g31ChancePlays.tsx (20)
  "bn4_costume_trunk", "bn4_bottled_courage", "hx4_ferrymans_coin", "bn4_rubber_duck", "bn4_lucky_coin", "op_chairs_on_tables",
  "op_crystal_ball", "op_dowsing_rod", "op_evil_eye_bead", "op_fools_gold", "op_four_leaf_clover", "op_gossip_charm",
  "op_horseshoe_nail", "op_private_booth", "op_rabbits_foot", "op_starboard_chart", "op_sunday_best", "op_tea_leaves",
  "op_wishbone", "ov_lucky_penny",
];
// </plugin-ids:generated>

export const PLUGIN_ID_SET: ReadonlySet<string> = new Set(PLUGIN_IDS);
