// Generates src/lib/sitemapDates.gen.ts: the real last-modified date of every
// static route in the sitemap, taken from git (the newest commit touching the
// route's source files, see src/lib/sitemapRoutes.ts). The sitemap used to
// stamp every URL with the time of the request (F247), which tells a crawler
// nothing and teaches it to ignore <lastmod>.
//
//   ./node_modules/.bin/tsx scripts/gen-sitemap-dates.ts          write the file
//   ./node_modules/.bin/tsx scripts/gen-sitemap-dates.ts --check  fail if it is not current
//
// Codex card pages carry no <lastmod>: a card is one entry among dozens in a
// shared library file, so no honest per-card date exists. /updates and
// /puzzles are dated at request time from their own data (the newest update
// entry, today's puzzle).

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { STATIC_ROUTES, sourcesOf } from "../src/lib/sitemapRoutes";

const ROOT = join(__dirname, "..");
const OUT = join(ROOT, "src", "lib", "sitemapDates.gen.ts");

function lastCommitDate(files: string[]): string | null {
  const present = files.filter((f) => existsSync(join(ROOT, f)));
  if (!present.length) return null;
  const out = execFileSync("git", ["log", "-1", "--format=%cs", "--", ...present], { cwd: ROOT, encoding: "utf8" }).trim();
  return /^\d{4}-\d{2}-\d{2}$/.test(out) ? out : null;
}

const dates: Record<string, string> = {};
const missing: string[] = [];
for (const route of STATIC_ROUTES) {
  if (route.path === "/updates" || route.path === "/puzzles") continue;
  const d = lastCommitDate(sourcesOf(route));
  if (d) dates[route.path] = d;
  else missing.push(route.path);
}

const body = `// GENERATED by scripts/gen-sitemap-dates.ts from git history. Do not edit by hand.
// The newest commit date of each static route's source files, for <lastmod>.

export const ROUTE_DATES: Record<string, string> = ${JSON.stringify(dates, null, 2)};
`;

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== body) {
    console.error("src/lib/sitemapDates.gen.ts is out of date: run ./node_modules/.bin/tsx scripts/gen-sitemap-dates.ts");
    process.exit(1);
  }
  console.log(`sitemap dates current (${Object.keys(dates).length} routes)`);
} else {
  writeFileSync(OUT, body);
  console.log(`wrote ${Object.keys(dates).length} route dates${missing.length ? `; no history for ${missing.join(", ")}` : ""}`);
}
